;; clorb-idl

(in-package :clorb)

(defclass IDL-COMPILER () 
  ((include-directories :initform *default-include-directories*
                        :initarg :include-directories
                        :accessor include-directories)))


(defgeneric load-repository (idl-compiler repository file))

(defvar *default-idl-compiler* nil)

(defvar *default-exclude* '("::CORBA"))

(defun corba:idl (file &key print (eval t) output package-decl
                         only (exclude *default-exclude*)
                         (skeleton t) target
                         (compiler *default-idl-compiler*)
                         ((pprint-dispatch *print-pprint-dispatch*) *target-pprint-dispatch*))
  (let ((repository (make-instance 'repository)))
    (load-repository compiler repository file)
    (flet ((lookup (name) (op:lookup repository name)))
      (let* ((target (make-instance (or target (if skeleton 'all-target 'static-stub-target))
                       :excludes (mapcar #'lookup exclude)))
             (code (if only
                     (make-progn (mapcar (lambda (name) (target-code (lookup name) target))
                                         (mklist only)))
                     (target-code repository target))))
        (flet ((execute-code ()
                 (unless (and (consp code) (eq (car code) 'progn))
                   (setq code `(progn code)))
                 (dolist (x (cdr code))
                   (when x
                     (when print (terpri) (pprint x))
                     (when eval (eval x))))
                 (when print (terpri))))
          (cond (output
                 (setq print t)
                 (with-open-file (*standard-output* output :direction :output
                                                    :if-exists :supersede)
                   (format t ";;;; Code generated by CLORB~%")
                   (pprint '(in-package :clorb))
                   (when package-decl
                     (pprint (target-ensure-packages target)))
                   (execute-code)))
                (t
                 (execute-code))))))
      (add-idl-repository *internal-interface-repository*
                          (truename file)
                          repository)
      repository))


#|
(CORBA:IDL "clorb:idl;interface_repository.idl" 
           :output "clorb:src;y-ifr-base.lisp" 
           :eval nil
           :exclude nil
           :skeleton nil)
|#
;;; clorb-idl.lisp ends here
