
(IN-PACKAGE :CLORB)

(DEFINE-STRUCT OMG.ORG/CORBA:INTERFACEDESCRIPTION
 :ID "IDL:omg.org/CORBA/InterfaceDescription:1.0"
 :NAME "InterfaceDescription"
 :MEMBERS (("name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) NAME)
           ("id" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID) ID)
           ("defined_in" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID)
            DEFINED_IN)
           ("version" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:VERSIONSPEC) VERSION)
           ("base_interfaces" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYIDSEQ)
            BASE_INTERFACES)))

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:ATTRDESCRIPTIONSEQ
  "IDL:omg.org/CORBA/AttrDescriptionSeq:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CORBA/AttrDescriptionSeq:1.0"
      "AttrDescriptionSeq"
      (MAKE-SEQUENCE-TYPECODE
        (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ATTRIBUTEDESCRIPTION)
        0))))

(DEFTYPE OMG.ORG/CORBA:ATTRDESCRIPTIONSEQ () 'SEQUENCE)

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:OPDESCRIPTIONSEQ
  "IDL:omg.org/CORBA/OpDescriptionSeq:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CORBA/OpDescriptionSeq:1.0"
      "OpDescriptionSeq"
      (MAKE-SEQUENCE-TYPECODE
        (SYMBOL-TYPECODE 'OMG.ORG/CORBA:OPERATIONDESCRIPTION)
        0))))

(DEFTYPE OMG.ORG/CORBA:OPDESCRIPTIONSEQ () 'SEQUENCE)

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:REPOSITORYIDSEQ
  "IDL:omg.org/CORBA/RepositoryIdSeq:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CORBA/RepositoryIdSeq:1.0"
      "RepositoryIdSeq"
      (MAKE-SEQUENCE-TYPECODE
        (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID)
        0))))

(DEFTYPE OMG.ORG/CORBA:REPOSITORYIDSEQ () 'SEQUENCE)

(DEFINE-STRUCT OMG.ORG/CORBA:OPERATIONDESCRIPTION
 :ID "IDL:omg.org/CORBA/OperationDescription:1.0"
 :NAME "OperationDescription"
 :MEMBERS (("name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) NAME)
           ("id" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID) ID)
           ("defined_in" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID)
            DEFINED_IN)
           ("version" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:VERSIONSPEC) VERSION)
           ("result" OMG.ORG/CORBA:TC_TYPECODE RESULT)
           ("mode" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:OPERATIONMODE) MODE)
           ("contexts" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTEXTIDSEQ) CONTEXTS)
           ("parameters" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:PARDESCRIPTIONSEQ)
            PARAMETERS)
           ("exceptions" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:EXCDESCRIPTIONSEQ)
            EXCEPTIONS)))

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:EXCDESCRIPTIONSEQ
  "IDL:omg.org/CORBA/ExcDescriptionSeq:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CORBA/ExcDescriptionSeq:1.0"
      "ExcDescriptionSeq"
      (MAKE-SEQUENCE-TYPECODE
        (SYMBOL-TYPECODE 'OMG.ORG/CORBA:EXCEPTIONDESCRIPTION)
        0))))

(DEFTYPE OMG.ORG/CORBA:EXCDESCRIPTIONSEQ () 'SEQUENCE)

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:EXCEPTIONDEFSEQ
  "IDL:omg.org/CORBA/ExceptionDefSeq:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CORBA/ExceptionDefSeq:1.0"
      "ExceptionDefSeq"
      (MAKE-SEQUENCE-TYPECODE
        (SYMBOL-TYPECODE 'OMG.ORG/CORBA:EXCEPTIONDEF)
        0))))

(DEFTYPE OMG.ORG/CORBA:EXCEPTIONDEFSEQ () 'SEQUENCE)

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:CONTEXTIDSEQ
  "IDL:omg.org/CORBA/ContextIdSeq:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CORBA/ContextIdSeq:1.0"
      "ContextIdSeq"
      (MAKE-SEQUENCE-TYPECODE
        (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTEXTIDENTIFIER)
        0))))

(DEFTYPE OMG.ORG/CORBA:CONTEXTIDSEQ () 'SEQUENCE)

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:CONTEXTIDENTIFIER
  "IDL:omg.org/CORBA/ContextIdentifier:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CORBA/ContextIdentifier:1.0"
      "ContextIdentifier"
      (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER))))

(DEFTYPE OMG.ORG/CORBA:CONTEXTIDENTIFIER () 'OMG.ORG/CORBA:IDENTIFIER)

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:PARDESCRIPTIONSEQ
  "IDL:omg.org/CORBA/ParDescriptionSeq:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CORBA/ParDescriptionSeq:1.0"
      "ParDescriptionSeq"
      (MAKE-SEQUENCE-TYPECODE
        (SYMBOL-TYPECODE 'OMG.ORG/CORBA:PARAMETERDESCRIPTION)
        0))))

(DEFTYPE OMG.ORG/CORBA:PARDESCRIPTIONSEQ () 'SEQUENCE)

(DEFINE-STRUCT OMG.ORG/CORBA:PARAMETERDESCRIPTION
 :ID "IDL:omg.org/CORBA/ParameterDescription:1.0"
 :NAME "ParameterDescription"
 :MEMBERS (("name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) NAME)
           ("type" OMG.ORG/CORBA:TC_TYPECODE TYPE)
           ("type_def" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE) TYPE_DEF)
           ("mode" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:PARAMETERMODE) MODE)))

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:PARAMETERMODE
  "IDL:omg.org/CORBA/ParameterMode:1.0"
  (MAKE-TYPECODE
    :TK_ENUM
    "IDL:omg.org/CORBA/ParameterMode:1.0"
    "ParameterMode"
    '("PARAM_IN" "PARAM_OUT" "PARAM_INOUT")))

(DEFTYPE OMG.ORG/CORBA:PARAMETERMODE ()
  '(MEMBER :PARAM_IN :PARAM_OUT :PARAM_INOUT))

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:OPERATIONMODE
  "IDL:omg.org/CORBA/OperationMode:1.0"
  (MAKE-TYPECODE
    :TK_ENUM
    "IDL:omg.org/CORBA/OperationMode:1.0"
    "OperationMode"
    '("OP_NORMAL" "OP_ONEWAY")))

(DEFTYPE OMG.ORG/CORBA:OPERATIONMODE () '(MEMBER :OP_NORMAL :OP_ONEWAY))

(DEFINE-STRUCT OMG.ORG/CORBA:ATTRIBUTEDESCRIPTION
 :ID "IDL:omg.org/CORBA/AttributeDescription:1.0"
 :NAME "AttributeDescription"
 :MEMBERS (("name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) NAME)
           ("id" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID) ID)
           ("defined_in" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID)
            DEFINED_IN)
           ("version" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:VERSIONSPEC) VERSION)
           ("type" OMG.ORG/CORBA:TC_TYPECODE TYPE)
           ("mode" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ATTRIBUTEMODE) MODE)))

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:ATTRIBUTEMODE
  "IDL:omg.org/CORBA/AttributeMode:1.0"
  (MAKE-TYPECODE
    :TK_ENUM
    "IDL:omg.org/CORBA/AttributeMode:1.0"
    "AttributeMode"
    '("ATTR_NORMAL" "ATTR_READONLY")))

(DEFTYPE OMG.ORG/CORBA:ATTRIBUTEMODE () '(MEMBER :ATTR_NORMAL :ATTR_READONLY))

(DEFINE-STRUCT OMG.ORG/CORBA:EXCEPTIONDESCRIPTION
 :ID "IDL:omg.org/CORBA/ExceptionDescription:1.0"
 :NAME "ExceptionDescription"
 :MEMBERS (("name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) NAME)
           ("id" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID) ID)
           ("defined_in" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID)
            DEFINED_IN)
           ("version" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:VERSIONSPEC) VERSION)
           ("type" OMG.ORG/CORBA:TC_TYPECODE TYPE)))

(DEFINE-STRUCT OMG.ORG/CORBA:TYPEDESCRIPTION
 :ID "IDL:omg.org/CORBA/TypeDescription:1.0"
 :NAME "TypeDescription"
 :MEMBERS (("name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) NAME)
           ("id" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID) ID)
           ("defined_in" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID)
            DEFINED_IN)
           ("version" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:VERSIONSPEC) VERSION)
           ("type" OMG.ORG/CORBA:TC_TYPECODE TYPE)))

(DEFINE-STRUCT OMG.ORG/CORBA:CONSTANTDESCRIPTION
 :ID "IDL:omg.org/CORBA/ConstantDescription:1.0"
 :NAME "ConstantDescription"
 :MEMBERS (("name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) NAME)
           ("id" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID) ID)
           ("defined_in" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID)
            DEFINED_IN)
           ("version" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:VERSIONSPEC) VERSION)
           ("type" OMG.ORG/CORBA:TC_TYPECODE TYPE)
           ("value" OMG.ORG/CORBA:TC_ANY VALUE)))

(DEFINE-STRUCT OMG.ORG/CORBA:MODULEDESCRIPTION
 :ID "IDL:omg.org/CORBA/ModuleDescription:1.0"
 :NAME "ModuleDescription"
 :MEMBERS (("name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) NAME)
           ("id" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID) ID)
           ("defined_in" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID)
            DEFINED_IN)
           ("version" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:VERSIONSPEC) VERSION)))

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:PRIMITIVEKIND
  "IDL:omg.org/CORBA/PrimitiveKind:1.0"
  (MAKE-TYPECODE
    :TK_ENUM
    "IDL:omg.org/CORBA/PrimitiveKind:1.0"
    "PrimitiveKind"
    '("pk_null" "pk_void" "pk_short" "pk_long" "pk_ushort" "pk_ulong"
      "pk_float" "pk_double" "pk_boolean" "pk_char" "pk_octet" "pk_any"
      "pk_TypeCode" "pk_Principal" "pk_string" "pk_objref" "pk_longlong"
      "pk_ulonglong" "pk_longdouble" "pk_wchar" "pk_wstring")))

(DEFTYPE OMG.ORG/CORBA:PRIMITIVEKIND ()
  '(MEMBER :PK_NULL
           :PK_VOID
           :PK_SHORT
           :PK_LONG
           :PK_USHORT
           :PK_ULONG
           :PK_FLOAT
           :PK_DOUBLE
           :PK_BOOLEAN
           :PK_CHAR
           :PK_OCTET
           :PK_ANY
           :PK_TYPECODE
           :PK_PRINCIPAL
           :PK_STRING
           :PK_OBJREF
           :PK_LONGLONG
           :PK_ULONGLONG
           :PK_LONGDOUBLE
           :PK_WCHAR
           :PK_WSTRING))

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:ENUMMEMBERSEQ
  "IDL:omg.org/CORBA/EnumMemberSeq:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CORBA/EnumMemberSeq:1.0"
      "EnumMemberSeq"
      (MAKE-SEQUENCE-TYPECODE (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) 0))))

(DEFTYPE OMG.ORG/CORBA:ENUMMEMBERSEQ () 'SEQUENCE)

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:UNIONMEMBERSEQ
  "IDL:omg.org/CORBA/UnionMemberSeq:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CORBA/UnionMemberSeq:1.0"
      "UnionMemberSeq"
      (MAKE-SEQUENCE-TYPECODE (SYMBOL-TYPECODE 'OMG.ORG/CORBA:UNIONMEMBER) 0))))

(DEFTYPE OMG.ORG/CORBA:UNIONMEMBERSEQ () 'SEQUENCE)

(DEFINE-STRUCT OMG.ORG/CORBA:UNIONMEMBER
 :ID "IDL:omg.org/CORBA/UnionMember:1.0"
 :NAME "UnionMember"
 :MEMBERS (("name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) NAME)
           ("label" OMG.ORG/CORBA:TC_ANY LABEL)
           ("type" OMG.ORG/CORBA:TC_TYPECODE TYPE)
           ("type_def" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE) TYPE_DEF)))

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:STRUCTMEMBERSEQ
  "IDL:omg.org/CORBA/StructMemberSeq:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CORBA/StructMemberSeq:1.0"
      "StructMemberSeq"
      (MAKE-SEQUENCE-TYPECODE
        (SYMBOL-TYPECODE 'OMG.ORG/CORBA:STRUCTMEMBER)
        0))))

(DEFTYPE OMG.ORG/CORBA:STRUCTMEMBERSEQ () 'SEQUENCE)

(DEFINE-STRUCT OMG.ORG/CORBA:STRUCTMEMBER
 :ID "IDL:omg.org/CORBA/StructMember:1.0"
 :NAME "StructMember"
 :MEMBERS (("name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) NAME)
           ("type" OMG.ORG/CORBA:TC_TYPECODE TYPE)
           ("type_def" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE) TYPE_DEF)))

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:CONTAINEDSEQ
  "IDL:omg.org/CORBA/ContainedSeq:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CORBA/ContainedSeq:1.0"
      "ContainedSeq"
      (MAKE-SEQUENCE-TYPECODE (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTAINED) 0))))

(DEFTYPE OMG.ORG/CORBA:CONTAINEDSEQ () 'SEQUENCE)

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:INTERFACEDEFSEQ
  "IDL:omg.org/CORBA/InterfaceDefSeq:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CORBA/InterfaceDefSeq:1.0"
      "InterfaceDefSeq"
      (MAKE-SEQUENCE-TYPECODE
        (SYMBOL-TYPECODE 'OMG.ORG/CORBA:INTERFACEDEF)
        0))))

(DEFTYPE OMG.ORG/CORBA:INTERFACEDEFSEQ () 'SEQUENCE)

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:VERSIONSPEC
  "IDL:omg.org/CORBA/VersionSpec:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CORBA/VersionSpec:1.0"
      "VersionSpec"
      OMG.ORG/CORBA:TC_STRING)))

(DEFTYPE OMG.ORG/CORBA:VERSIONSPEC () 'OMG.ORG/CORBA:STRING)

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:DEFINITIONKIND
  "IDL:omg.org/CORBA/DefinitionKind:1.0"
  (MAKE-TYPECODE
    :TK_ENUM
    "IDL:omg.org/CORBA/DefinitionKind:1.0"
    "DefinitionKind"
    '("dk_none" "dk_all" "dk_Attribute" "dk_Constant" "dk_Exception"
      "dk_Interface" "dk_Module" "dk_Operation" "dk_Typedef" "dk_Alias"
      "dk_Struct" "dk_Union" "dk_Enum" "dk_Primitive" "dk_String" "dk_Sequence"
      "dk_Array" "dk_Repository" "dk_Wstring" "dk_Fixed")))

(DEFTYPE OMG.ORG/CORBA:DEFINITIONKIND ()
  '(MEMBER :DK_NONE
           :DK_ALL
           :DK_ATTRIBUTE
           :DK_CONSTANT
           :DK_EXCEPTION
           :DK_INTERFACE
           :DK_MODULE
           :DK_OPERATION
           :DK_TYPEDEF
           :DK_ALIAS
           :DK_STRUCT
           :DK_UNION
           :DK_ENUM
           :DK_PRIMITIVE
           :DK_STRING
           :DK_SEQUENCE
           :DK_ARRAY
           :DK_REPOSITORY
           :DK_WSTRING
           :DK_FIXED))

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:REPOSITORYID
  "IDL:omg.org/CORBA/RepositoryId:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CORBA/RepositoryId:1.0"
      "RepositoryId"
      OMG.ORG/CORBA:TC_STRING)))

(DEFTYPE OMG.ORG/CORBA:REPOSITORYID () 'OMG.ORG/CORBA:STRING)

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:SCOPEDNAME
  "IDL:omg.org/CORBA/ScopedName:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CORBA/ScopedName:1.0"
      "ScopedName"
      OMG.ORG/CORBA:TC_STRING)))

(DEFTYPE OMG.ORG/CORBA:SCOPEDNAME () 'OMG.ORG/CORBA:STRING)

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:IDENTIFIER
  "IDL:omg.org/CORBA/Identifier:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CORBA/Identifier:1.0"
      "Identifier"
      OMG.ORG/CORBA:TC_STRING)))

(DEFTYPE OMG.ORG/CORBA:IDENTIFIER () 'OMG.ORG/CORBA:STRING)

(DEFINE-INTERFACE OMG.ORG/CORBA:IROBJECT (OBJECT)
 :PROXY (OMG.ORG/CORBA:IROBJECT-PROXY OMG.ORG/CORBA:IROBJECT
         OMG.ORG/CORBA:PROXY)
 :ID "IDL:omg.org/CORBA/IRObject:1.0"
 :NAME "IRObject")

(DEFINE-METHOD "DESTROY" ((OBJ OMG.ORG/CORBA:IROBJECT-PROXY))
  (STATIC-CALL ("destroy" OBJ)
   :OUTPUT ((OUTPUT))
   :INPUT ((INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "DEF_KIND" ((OBJ OMG.ORG/CORBA:IROBJECT-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_def_kind"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:DEFINITIONKIND)))

(DEFINE-INTERFACE OMG.ORG/CORBA:IDLTYPE (OMG.ORG/CORBA:IROBJECT)
 :PROXY (OMG.ORG/CORBA:IDLTYPE-PROXY OMG.ORG/CORBA:IDLTYPE
         OMG.ORG/CORBA:IROBJECT-PROXY)
 :ID "IDL:omg.org/CORBA/IDLType:1.0"
 :NAME "IDLType")

(DEFINE-METHOD "TYPE" ((OBJ OMG.ORG/CORBA:IDLTYPE-PROXY))
  (GET-ATTRIBUTE OBJ "_get_type" OMG.ORG/CORBA:TC_TYPECODE))

(DEFINE-INTERFACE OMG.ORG/CORBA:CONTAINER (OMG.ORG/CORBA:IROBJECT)
 :PROXY (OMG.ORG/CORBA:CONTAINER-PROXY OMG.ORG/CORBA:CONTAINER
         OMG.ORG/CORBA:IROBJECT-PROXY)
 :ID "IDL:omg.org/CORBA/Container:1.0"
 :NAME "Container")

(DEFINE-METHOD "CREATE_INTERFACE" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY) _ID
                                   _NAME _VERSION _BASE_INTERFACES)
  (STATIC-CALL ("create_interface" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _ID OUTPUT) (MARSHAL-STRING _NAME OUTPUT)
            (MARSHAL-STRING _VERSION OUTPUT)
            (MARSHAL-SEQUENCE
              _BASE_INTERFACES
              (LAMBDA (OBJ BUFFER)
                (MARSHAL OBJ
                         (SYMBOL-TYPECODE 'OMG.ORG/CORBA:INTERFACEDEF)
                         BUFFER))
              OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:INTERFACEDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_ALIAS" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY) _ID _NAME
                               _VERSION _ORIGINAL_TYPE)
  (STATIC-CALL ("create_alias" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _ID OUTPUT) (MARSHAL-STRING _NAME OUTPUT)
            (MARSHAL-STRING _VERSION OUTPUT)
            (MARSHAL _ORIGINAL_TYPE
                     (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
                     OUTPUT))
   :INPUT ((INPUT) (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ALIASDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_ENUM" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY) _ID _NAME
                              _VERSION _MEMBERS)
  (STATIC-CALL ("create_enum" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _ID OUTPUT) (MARSHAL-STRING _NAME OUTPUT)
            (MARSHAL-STRING _VERSION OUTPUT)
            (MARSHAL-SEQUENCE _MEMBERS #'MARSHAL-STRING OUTPUT))
   :INPUT ((INPUT) (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ENUMDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_UNION" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY) _ID _NAME
                               _VERSION _DISCRIMINATOR_TYPE _MEMBERS)
  (STATIC-CALL ("create_union" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _ID OUTPUT) (MARSHAL-STRING _NAME OUTPUT)
            (MARSHAL-STRING _VERSION OUTPUT)
            (MARSHAL _DISCRIMINATOR_TYPE
                     (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
                     OUTPUT)
            (MARSHAL-SEQUENCE
              _MEMBERS
              (LAMBDA (OBJ BUFFER)
                (MARSHAL OBJ
                         (SYMBOL-TYPECODE 'OMG.ORG/CORBA:UNIONMEMBER)
                         BUFFER))
              OUTPUT))
   :INPUT ((INPUT) (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:UNIONDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_EXCEPTION" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY) _ID
                                   _NAME _VERSION _MEMBERS)
  (STATIC-CALL ("create_exception" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _ID OUTPUT) (MARSHAL-STRING _NAME OUTPUT)
            (MARSHAL-STRING _VERSION OUTPUT)
            (MARSHAL-SEQUENCE
              _MEMBERS
              (LAMBDA (OBJ BUFFER)
                (MARSHAL OBJ
                         (SYMBOL-TYPECODE 'OMG.ORG/CORBA:STRUCTMEMBER)
                         BUFFER))
              OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:EXCEPTIONDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_STRUCT" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY) _ID _NAME
                                _VERSION _MEMBERS)
  (STATIC-CALL ("create_struct" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _ID OUTPUT) (MARSHAL-STRING _NAME OUTPUT)
            (MARSHAL-STRING _VERSION OUTPUT)
            (MARSHAL-SEQUENCE
              _MEMBERS
              (LAMBDA (OBJ BUFFER)
                (MARSHAL OBJ
                         (SYMBOL-TYPECODE 'OMG.ORG/CORBA:STRUCTMEMBER)
                         BUFFER))
              OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:STRUCTDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_CONSTANT" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY) _ID _NAME
                                  _VERSION _TYPE _VALUE)
  (STATIC-CALL ("create_constant" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _ID OUTPUT) (MARSHAL-STRING _NAME OUTPUT)
            (MARSHAL-STRING _VERSION OUTPUT)
            (MARSHAL _TYPE (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE) OUTPUT)
            (MARSHAL _VALUE OMG.ORG/CORBA:TC_ANY OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONSTANTDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_MODULE" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY) _ID _NAME
                                _VERSION)
  (STATIC-CALL ("create_module" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _ID OUTPUT) (MARSHAL-STRING _NAME OUTPUT)
            (MARSHAL-STRING _VERSION OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:MODULEDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "DESCRIBE_CONTENTS" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY)
                                    _LIMIT_TYPE _EXCLUDE_INHERITED
                                    _MAX_RETURNED_OBJS)
  (STATIC-CALL ("describe_contents" OBJ)
   :OUTPUT ((OUTPUT)
            (MARSHAL _LIMIT_TYPE
                     (SYMBOL-TYPECODE 'OMG.ORG/CORBA:DEFINITIONKIND)
                     OUTPUT)
            (MARSHAL-BOOL _EXCLUDE_INHERITED OUTPUT)
            (MARSHAL-LONG _MAX_RETURNED_OBJS OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL-SEQUENCE
             (LAMBDA (BUFFER)
               (UNMARSHAL (SYMBOL-TYPECODE
                            'OMG.ORG/CORBA:CONTAINER/DESCRIPTION)
                          BUFFER))
             INPUT))
   :EXCEPTIONS NIL))

(SET-SYMBOL-ID/TYPECODE
  'OMG.ORG/CORBA:CONTAINER/DESCRIPTIONSEQ
  "IDL:omg.org/CORBA/Container/DescriptionSeq:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CORBA/Container/DescriptionSeq:1.0"
      "DescriptionSeq"
      (MAKE-SEQUENCE-TYPECODE
        (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTAINER/DESCRIPTION)
        0))))

(DEFTYPE OMG.ORG/CORBA:CONTAINER/DESCRIPTIONSEQ () 'SEQUENCE)

(DEFINE-STRUCT OMG.ORG/CORBA:CONTAINER/DESCRIPTION
 :ID "IDL:omg.org/CORBA/Container/Description:1.0"
 :NAME "Description"
 :MEMBERS (("contained_object" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTAINED)
            CONTAINED_OBJECT)
           ("kind" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:DEFINITIONKIND) KIND)
           ("value" OMG.ORG/CORBA:TC_ANY VALUE)))

(DEFINE-METHOD "LOOKUP_NAME" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY) _SEARCH_NAME
                              _LEVELS_TO_SEARCH _LIMIT_TYPE _EXCLUDE_INHERITED)
  (STATIC-CALL ("lookup_name" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _SEARCH_NAME OUTPUT)
            (MARSHAL-LONG _LEVELS_TO_SEARCH OUTPUT)
            (MARSHAL _LIMIT_TYPE
                     (SYMBOL-TYPECODE 'OMG.ORG/CORBA:DEFINITIONKIND)
                     OUTPUT)
            (MARSHAL-BOOL _EXCLUDE_INHERITED OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL-SEQUENCE
             (LAMBDA (BUFFER)
               (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTAINED) BUFFER))
             INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CONTENTS" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY) _LIMIT_TYPE
                           _EXCLUDE_INHERITED)
  (STATIC-CALL ("contents" OBJ)
   :OUTPUT ((OUTPUT)
            (MARSHAL _LIMIT_TYPE
                     (SYMBOL-TYPECODE 'OMG.ORG/CORBA:DEFINITIONKIND)
                     OUTPUT)
            (MARSHAL-BOOL _EXCLUDE_INHERITED OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL-SEQUENCE
             (LAMBDA (BUFFER)
               (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTAINED) BUFFER))
             INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "LOOKUP" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY) _SEARCH_NAME)
  (STATIC-CALL ("lookup" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _SEARCH_NAME OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTAINED) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-INTERFACE OMG.ORG/CORBA:CONTAINED (OMG.ORG/CORBA:IROBJECT)
 :PROXY (OMG.ORG/CORBA:CONTAINED-PROXY OMG.ORG/CORBA:CONTAINED
         OMG.ORG/CORBA:IROBJECT-PROXY)
 :ID "IDL:omg.org/CORBA/Contained:1.0"
 :NAME "Contained")

(DEFINE-METHOD "MOVE" ((OBJ OMG.ORG/CORBA:CONTAINED-PROXY) _NEW_CONTAINER
                       _NEW_NAME _NEW_VERSION)
  (STATIC-CALL ("move" OBJ)
   :OUTPUT ((OUTPUT)
            (MARSHAL _NEW_CONTAINER
                     (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTAINER)
                     OUTPUT)
            (MARSHAL-STRING _NEW_NAME OUTPUT)
            (MARSHAL-STRING _NEW_VERSION OUTPUT))
   :INPUT ((INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "DESCRIBE" ((OBJ OMG.ORG/CORBA:CONTAINED-PROXY))
  (STATIC-CALL ("describe" OBJ)
   :OUTPUT ((OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTAINED/DESCRIPTION)
                      INPUT))
   :EXCEPTIONS NIL))

(DEFINE-STRUCT OMG.ORG/CORBA:CONTAINED/DESCRIPTION
 :ID "IDL:omg.org/CORBA/Contained/Description:1.0"
 :NAME "Description"
 :MEMBERS (("kind" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:DEFINITIONKIND) KIND)
           ("value" OMG.ORG/CORBA:TC_ANY VALUE)))

(DEFINE-METHOD "CONTAINING_REPOSITORY" ((OBJ OMG.ORG/CORBA:CONTAINED-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_containing_repository"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORY)))

(DEFINE-METHOD "ABSOLUTE_NAME" ((OBJ OMG.ORG/CORBA:CONTAINED-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_absolute_name"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:SCOPEDNAME)))

(DEFINE-METHOD "DEFINED_IN" ((OBJ OMG.ORG/CORBA:CONTAINED-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_defined_in"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTAINER)))

(DEFINE-METHOD "VERSION" ((OBJ OMG.ORG/CORBA:CONTAINED-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_version"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:VERSIONSPEC)))

(DEFINE-METHOD (SETF "VERSION") (NEWVAL (OBJ OMG.ORG/CORBA:CONTAINED-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_version"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:VERSIONSPEC)
    NEWVAL))

(DEFINE-METHOD "NAME" ((OBJ OMG.ORG/CORBA:CONTAINED-PROXY))
  (GET-ATTRIBUTE OBJ "_get_name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER)))

(DEFINE-METHOD (SETF "NAME") (NEWVAL (OBJ OMG.ORG/CORBA:CONTAINED-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_name"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER)
    NEWVAL))

(DEFINE-METHOD "ID" ((OBJ OMG.ORG/CORBA:CONTAINED-PROXY))
  (GET-ATTRIBUTE OBJ "_get_id" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID)))

(DEFINE-METHOD (SETF "ID") (NEWVAL (OBJ OMG.ORG/CORBA:CONTAINED-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_id"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID)
    NEWVAL))

(DEFINE-INTERFACE OMG.ORG/CORBA:INTERFACEDEF (OMG.ORG/CORBA:CONTAINER
                                              OMG.ORG/CORBA:CONTAINED
                                              OMG.ORG/CORBA:IDLTYPE)
 :PROXY (OMG.ORG/CORBA:INTERFACEDEF-PROXY OMG.ORG/CORBA:INTERFACEDEF
         OMG.ORG/CORBA:CONTAINER-PROXY OMG.ORG/CORBA:CONTAINED-PROXY
         OMG.ORG/CORBA:IDLTYPE-PROXY)
 :ID "IDL:omg.org/CORBA/InterfaceDef:1.0"
 :NAME "InterfaceDef")

(DEFINE-METHOD "CREATE_OPERATION" ((OBJ OMG.ORG/CORBA:INTERFACEDEF-PROXY) _ID
                                   _NAME _VERSION _RESULT _MODE _PARAMS
                                   _EXCEPTIONS _CONTEXTS)
  (STATIC-CALL ("create_operation" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _ID OUTPUT) (MARSHAL-STRING _NAME OUTPUT)
            (MARSHAL-STRING _VERSION OUTPUT)
            (MARSHAL _RESULT (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE) OUTPUT)
            (MARSHAL _MODE
                     (SYMBOL-TYPECODE 'OMG.ORG/CORBA:OPERATIONMODE)
                     OUTPUT)
            (MARSHAL-SEQUENCE
              _PARAMS
              (LAMBDA (OBJ BUFFER)
                (MARSHAL OBJ
                         (SYMBOL-TYPECODE 'OMG.ORG/CORBA:PARAMETERDESCRIPTION)
                         BUFFER))
              OUTPUT)
            (MARSHAL-SEQUENCE
              _EXCEPTIONS
              (LAMBDA (OBJ BUFFER)
                (MARSHAL OBJ
                         (SYMBOL-TYPECODE 'OMG.ORG/CORBA:EXCEPTIONDEF)
                         BUFFER))
              OUTPUT)
            (MARSHAL-SEQUENCE _CONTEXTS #'MARSHAL-STRING OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:OPERATIONDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_ATTRIBUTE" ((OBJ OMG.ORG/CORBA:INTERFACEDEF-PROXY) _ID
                                   _NAME _VERSION _TYPE _MODE)
  (STATIC-CALL ("create_attribute" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _ID OUTPUT) (MARSHAL-STRING _NAME OUTPUT)
            (MARSHAL-STRING _VERSION OUTPUT)
            (MARSHAL _TYPE (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE) OUTPUT)
            (MARSHAL _MODE
                     (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ATTRIBUTEMODE)
                     OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ATTRIBUTEDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "DESCRIBE_INTERFACE" ((OBJ OMG.ORG/CORBA:INTERFACEDEF-PROXY))
  (STATIC-CALL ("describe_interface" OBJ)
   :OUTPUT ((OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE
                        'OMG.ORG/CORBA:INTERFACEDEF/FULLINTERFACEDESCRIPTION)
                      INPUT))
   :EXCEPTIONS NIL))

(DEFINE-STRUCT OMG.ORG/CORBA:INTERFACEDEF/FULLINTERFACEDESCRIPTION
 :ID "IDL:omg.org/CORBA/InterfaceDef/FullInterfaceDescription:1.0"
 :NAME "FullInterfaceDescription"
 :MEMBERS (("name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) NAME)
           ("id" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID) ID)
           ("defined_in" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID)
            DEFINED_IN)
           ("version" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:VERSIONSPEC) VERSION)
           ("operations" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:OPDESCRIPTIONSEQ)
            OPERATIONS)
           ("attributes" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ATTRDESCRIPTIONSEQ)
            ATTRIBUTES)
           ("base_interfaces" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYIDSEQ)
            BASE_INTERFACES)
           ("type" OMG.ORG/CORBA:TC_TYPECODE TYPE)))

(DEFINE-METHOD "IS_A" ((OBJ OMG.ORG/CORBA:INTERFACEDEF-PROXY) _INTERFACE_ID)
  (STATIC-CALL ("is_a" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _INTERFACE_ID OUTPUT))
   :INPUT ((INPUT) (UNMARSHAL-BOOL INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "BASE_INTERFACES" ((OBJ OMG.ORG/CORBA:INTERFACEDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_base_interfaces"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:INTERFACEDEFSEQ)))

(DEFINE-METHOD (SETF "BASE_INTERFACES") (NEWVAL
                                         (OBJ
                                          OMG.ORG/CORBA:INTERFACEDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_base_interfaces"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:INTERFACEDEFSEQ)
    NEWVAL))

(DEFINE-INTERFACE OMG.ORG/CORBA:OPERATIONDEF (OMG.ORG/CORBA:CONTAINED)
 :PROXY (OMG.ORG/CORBA:OPERATIONDEF-PROXY OMG.ORG/CORBA:OPERATIONDEF
         OMG.ORG/CORBA:CONTAINED-PROXY)
 :ID "IDL:omg.org/CORBA/OperationDef:1.0"
 :NAME "OperationDef")

(DEFINE-METHOD "EXCEPTIONS" ((OBJ OMG.ORG/CORBA:OPERATIONDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_exceptions"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:EXCEPTIONDEFSEQ)))

(DEFINE-METHOD (SETF "EXCEPTIONS") (NEWVAL
                                    (OBJ OMG.ORG/CORBA:OPERATIONDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_exceptions"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:EXCEPTIONDEFSEQ)
    NEWVAL))

(DEFINE-METHOD "CONTEXTS" ((OBJ OMG.ORG/CORBA:OPERATIONDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_contexts"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTEXTIDSEQ)))

(DEFINE-METHOD (SETF "CONTEXTS") (NEWVAL
                                  (OBJ OMG.ORG/CORBA:OPERATIONDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_contexts"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTEXTIDSEQ)
    NEWVAL))

(DEFINE-METHOD "MODE" ((OBJ OMG.ORG/CORBA:OPERATIONDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_mode"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:OPERATIONMODE)))

(DEFINE-METHOD (SETF "MODE") (NEWVAL (OBJ OMG.ORG/CORBA:OPERATIONDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_mode"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:OPERATIONMODE)
    NEWVAL))

(DEFINE-METHOD "PARAMS" ((OBJ OMG.ORG/CORBA:OPERATIONDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_params"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:PARDESCRIPTIONSEQ)))

(DEFINE-METHOD (SETF "PARAMS") (NEWVAL (OBJ OMG.ORG/CORBA:OPERATIONDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_params"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:PARDESCRIPTIONSEQ)
    NEWVAL))

(DEFINE-METHOD "RESULT_DEF" ((OBJ OMG.ORG/CORBA:OPERATIONDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_result_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)))

(DEFINE-METHOD (SETF "RESULT_DEF") (NEWVAL
                                    (OBJ OMG.ORG/CORBA:OPERATIONDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_result_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
    NEWVAL))

(DEFINE-METHOD "RESULT" ((OBJ OMG.ORG/CORBA:OPERATIONDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_result" OMG.ORG/CORBA:TC_TYPECODE))

(DEFINE-INTERFACE OMG.ORG/CORBA:ATTRIBUTEDEF (OMG.ORG/CORBA:CONTAINED)
 :PROXY (OMG.ORG/CORBA:ATTRIBUTEDEF-PROXY OMG.ORG/CORBA:ATTRIBUTEDEF
         OMG.ORG/CORBA:CONTAINED-PROXY)
 :ID "IDL:omg.org/CORBA/AttributeDef:1.0"
 :NAME "AttributeDef")

(DEFINE-METHOD "MODE" ((OBJ OMG.ORG/CORBA:ATTRIBUTEDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_mode"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ATTRIBUTEMODE)))

(DEFINE-METHOD (SETF "MODE") (NEWVAL (OBJ OMG.ORG/CORBA:ATTRIBUTEDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_mode"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ATTRIBUTEMODE)
    NEWVAL))

(DEFINE-METHOD "TYPE_DEF" ((OBJ OMG.ORG/CORBA:ATTRIBUTEDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_type_def" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)))

(DEFINE-METHOD (SETF "TYPE_DEF") (NEWVAL
                                  (OBJ OMG.ORG/CORBA:ATTRIBUTEDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_type_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
    NEWVAL))

(DEFINE-METHOD "TYPE" ((OBJ OMG.ORG/CORBA:ATTRIBUTEDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_type" OMG.ORG/CORBA:TC_TYPECODE))

(DEFINE-INTERFACE OMG.ORG/CORBA:EXCEPTIONDEF (OMG.ORG/CORBA:CONTAINED)
 :PROXY (OMG.ORG/CORBA:EXCEPTIONDEF-PROXY OMG.ORG/CORBA:EXCEPTIONDEF
         OMG.ORG/CORBA:CONTAINED-PROXY)
 :ID "IDL:omg.org/CORBA/ExceptionDef:1.0"
 :NAME "ExceptionDef")

(DEFINE-METHOD "MEMBERS" ((OBJ OMG.ORG/CORBA:EXCEPTIONDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_members"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:STRUCTMEMBERSEQ)))

(DEFINE-METHOD (SETF "MEMBERS") (NEWVAL (OBJ OMG.ORG/CORBA:EXCEPTIONDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_members"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:STRUCTMEMBERSEQ)
    NEWVAL))

(DEFINE-METHOD "TYPE" ((OBJ OMG.ORG/CORBA:EXCEPTIONDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_type" OMG.ORG/CORBA:TC_TYPECODE))

(DEFINE-INTERFACE OMG.ORG/CORBA:ARRAYDEF (OMG.ORG/CORBA:IDLTYPE)
 :PROXY (OMG.ORG/CORBA:ARRAYDEF-PROXY OMG.ORG/CORBA:ARRAYDEF
         OMG.ORG/CORBA:IDLTYPE-PROXY)
 :ID "IDL:omg.org/CORBA/ArrayDef:1.0"
 :NAME "ArrayDef")

(DEFINE-METHOD "ELEMENT_TYPE_DEF" ((OBJ OMG.ORG/CORBA:ARRAYDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_element_type_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)))

(DEFINE-METHOD (SETF "ELEMENT_TYPE_DEF") (NEWVAL
                                          (OBJ OMG.ORG/CORBA:ARRAYDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_element_type_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
    NEWVAL))

(DEFINE-METHOD "ELEMENT_TYPE" ((OBJ OMG.ORG/CORBA:ARRAYDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_element_type" OMG.ORG/CORBA:TC_TYPECODE))

(DEFINE-METHOD "LENGTH" ((OBJ OMG.ORG/CORBA:ARRAYDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_length" OMG.ORG/CORBA:TC_ULONG))

(DEFINE-METHOD (SETF "LENGTH") (NEWVAL (OBJ OMG.ORG/CORBA:ARRAYDEF-PROXY))
  (SET-ATTRIBUTE OBJ "_set_length" OMG.ORG/CORBA:TC_ULONG NEWVAL))

(DEFINE-INTERFACE OMG.ORG/CORBA:SEQUENCEDEF (OMG.ORG/CORBA:IDLTYPE)
 :PROXY (OMG.ORG/CORBA:SEQUENCEDEF-PROXY OMG.ORG/CORBA:SEQUENCEDEF
         OMG.ORG/CORBA:IDLTYPE-PROXY)
 :ID "IDL:omg.org/CORBA/SequenceDef:1.0"
 :NAME "SequenceDef")

(DEFINE-METHOD "ELEMENT_TYPE_DEF" ((OBJ OMG.ORG/CORBA:SEQUENCEDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_element_type_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)))

(DEFINE-METHOD (SETF "ELEMENT_TYPE_DEF") (NEWVAL
                                          (OBJ
                                           OMG.ORG/CORBA:SEQUENCEDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_element_type_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
    NEWVAL))

(DEFINE-METHOD "ELEMENT_TYPE" ((OBJ OMG.ORG/CORBA:SEQUENCEDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_element_type" OMG.ORG/CORBA:TC_TYPECODE))

(DEFINE-METHOD "BOUND" ((OBJ OMG.ORG/CORBA:SEQUENCEDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_bound" OMG.ORG/CORBA:TC_ULONG))

(DEFINE-METHOD (SETF "BOUND") (NEWVAL (OBJ OMG.ORG/CORBA:SEQUENCEDEF-PROXY))
  (SET-ATTRIBUTE OBJ "_set_bound" OMG.ORG/CORBA:TC_ULONG NEWVAL))

(DEFINE-INTERFACE OMG.ORG/CORBA:FIXEDDEF (OMG.ORG/CORBA:IDLTYPE)
 :PROXY (OMG.ORG/CORBA:FIXEDDEF-PROXY OMG.ORG/CORBA:FIXEDDEF
         OMG.ORG/CORBA:IDLTYPE-PROXY)
 :ID "IDL:omg.org/CORBA/FixedDef:1.0"
 :NAME "FixedDef")

(DEFINE-METHOD "SCALE" ((OBJ OMG.ORG/CORBA:FIXEDDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_scale" OMG.ORG/CORBA:TC_SHORT))

(DEFINE-METHOD (SETF "SCALE") (NEWVAL (OBJ OMG.ORG/CORBA:FIXEDDEF-PROXY))
  (SET-ATTRIBUTE OBJ "_set_scale" OMG.ORG/CORBA:TC_SHORT NEWVAL))

(DEFINE-METHOD "DIGITS" ((OBJ OMG.ORG/CORBA:FIXEDDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_digits" OMG.ORG/CORBA:TC_USHORT))

(DEFINE-METHOD (SETF "DIGITS") (NEWVAL (OBJ OMG.ORG/CORBA:FIXEDDEF-PROXY))
  (SET-ATTRIBUTE OBJ "_set_digits" OMG.ORG/CORBA:TC_USHORT NEWVAL))

(DEFINE-INTERFACE OMG.ORG/CORBA:WSTRINGDEF (OMG.ORG/CORBA:IDLTYPE)
 :PROXY (OMG.ORG/CORBA:WSTRINGDEF-PROXY OMG.ORG/CORBA:WSTRINGDEF
         OMG.ORG/CORBA:IDLTYPE-PROXY)
 :ID "IDL:omg.org/CORBA/WstringDef:1.0"
 :NAME "WstringDef")

(DEFINE-METHOD "BOUND" ((OBJ OMG.ORG/CORBA:WSTRINGDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_bound" OMG.ORG/CORBA:TC_ULONG))

(DEFINE-METHOD (SETF "BOUND") (NEWVAL (OBJ OMG.ORG/CORBA:WSTRINGDEF-PROXY))
  (SET-ATTRIBUTE OBJ "_set_bound" OMG.ORG/CORBA:TC_ULONG NEWVAL))

(DEFINE-INTERFACE OMG.ORG/CORBA:STRINGDEF (OMG.ORG/CORBA:IDLTYPE)
 :PROXY (OMG.ORG/CORBA:STRINGDEF-PROXY OMG.ORG/CORBA:STRINGDEF
         OMG.ORG/CORBA:IDLTYPE-PROXY)
 :ID "IDL:omg.org/CORBA/StringDef:1.0"
 :NAME "StringDef")

(DEFINE-METHOD "BOUND" ((OBJ OMG.ORG/CORBA:STRINGDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_bound" OMG.ORG/CORBA:TC_ULONG))

(DEFINE-METHOD (SETF "BOUND") (NEWVAL (OBJ OMG.ORG/CORBA:STRINGDEF-PROXY))
  (SET-ATTRIBUTE OBJ "_set_bound" OMG.ORG/CORBA:TC_ULONG NEWVAL))

(DEFINE-INTERFACE OMG.ORG/CORBA:PRIMITIVEDEF (OMG.ORG/CORBA:IDLTYPE)
 :PROXY (OMG.ORG/CORBA:PRIMITIVEDEF-PROXY OMG.ORG/CORBA:PRIMITIVEDEF
         OMG.ORG/CORBA:IDLTYPE-PROXY)
 :ID "IDL:omg.org/CORBA/PrimitiveDef:1.0"
 :NAME "PrimitiveDef")

(DEFINE-METHOD "KIND" ((OBJ OMG.ORG/CORBA:PRIMITIVEDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_kind"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:PRIMITIVEKIND)))

(DEFINE-INTERFACE OMG.ORG/CORBA:TYPEDEFDEF (OMG.ORG/CORBA:CONTAINED
                                            OMG.ORG/CORBA:IDLTYPE)
 :PROXY (OMG.ORG/CORBA:TYPEDEFDEF-PROXY OMG.ORG/CORBA:TYPEDEFDEF
         OMG.ORG/CORBA:CONTAINED-PROXY OMG.ORG/CORBA:IDLTYPE-PROXY)
 :ID "IDL:omg.org/CORBA/TypedefDef:1.0"
 :NAME "TypedefDef")

(DEFINE-INTERFACE OMG.ORG/CORBA:CONSTANTDEF (OMG.ORG/CORBA:CONTAINED)
 :PROXY (OMG.ORG/CORBA:CONSTANTDEF-PROXY OMG.ORG/CORBA:CONSTANTDEF
         OMG.ORG/CORBA:CONTAINED-PROXY)
 :ID "IDL:omg.org/CORBA/ConstantDef:1.0"
 :NAME "ConstantDef")

(DEFINE-METHOD "VALUE" ((OBJ OMG.ORG/CORBA:CONSTANTDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_value" OMG.ORG/CORBA:TC_ANY))

(DEFINE-METHOD (SETF "VALUE") (NEWVAL (OBJ OMG.ORG/CORBA:CONSTANTDEF-PROXY))
  (SET-ATTRIBUTE OBJ "_set_value" OMG.ORG/CORBA:TC_ANY NEWVAL))

(DEFINE-METHOD "TYPE_DEF" ((OBJ OMG.ORG/CORBA:CONSTANTDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_type_def" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)))

(DEFINE-METHOD (SETF "TYPE_DEF") (NEWVAL (OBJ OMG.ORG/CORBA:CONSTANTDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_type_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
    NEWVAL))

(DEFINE-METHOD "TYPE" ((OBJ OMG.ORG/CORBA:CONSTANTDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_type" OMG.ORG/CORBA:TC_TYPECODE))

(DEFINE-INTERFACE OMG.ORG/CORBA:MODULEDEF (OMG.ORG/CORBA:CONTAINER
                                           OMG.ORG/CORBA:CONTAINED)
 :PROXY (OMG.ORG/CORBA:MODULEDEF-PROXY OMG.ORG/CORBA:MODULEDEF
         OMG.ORG/CORBA:CONTAINER-PROXY OMG.ORG/CORBA:CONTAINED-PROXY)
 :ID "IDL:omg.org/CORBA/ModuleDef:1.0"
 :NAME "ModuleDef")

(DEFINE-INTERFACE OMG.ORG/CORBA:REPOSITORY (OMG.ORG/CORBA:CONTAINER)
 :PROXY (OMG.ORG/CORBA:REPOSITORY-PROXY OMG.ORG/CORBA:REPOSITORY
         OMG.ORG/CORBA:CONTAINER-PROXY)
 :ID "IDL:omg.org/CORBA/Repository:1.0"
 :NAME "Repository")

(DEFINE-METHOD "CREATE_FIXED" ((OBJ OMG.ORG/CORBA:REPOSITORY-PROXY) _DIGITS
                               _SCALE)
  (STATIC-CALL ("create_fixed" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-USHORT _DIGITS OUTPUT)
            (MARSHAL-SHORT _SCALE OUTPUT))
   :INPUT ((INPUT) (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:FIXEDDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_ARRAY" ((OBJ OMG.ORG/CORBA:REPOSITORY-PROXY) _LENGTH
                               _ELEMENT_TYPE)
  (STATIC-CALL ("create_array" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-ULONG _LENGTH OUTPUT)
            (MARSHAL _ELEMENT_TYPE
                     (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
                     OUTPUT))
   :INPUT ((INPUT) (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ARRAYDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_SEQUENCE" ((OBJ OMG.ORG/CORBA:REPOSITORY-PROXY) _BOUND
                                  _ELEMENT_TYPE)
  (STATIC-CALL ("create_sequence" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-ULONG _BOUND OUTPUT)
            (MARSHAL _ELEMENT_TYPE
                     (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
                     OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:SEQUENCEDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_WSTRING" ((OBJ OMG.ORG/CORBA:REPOSITORY-PROXY) _BOUND)
  (STATIC-CALL ("create_wstring" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-ULONG _BOUND OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:WSTRINGDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_STRING" ((OBJ OMG.ORG/CORBA:REPOSITORY-PROXY) _BOUND)
  (STATIC-CALL ("create_string" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-ULONG _BOUND OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:STRINGDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "GET_PRIMITIVE" ((OBJ OMG.ORG/CORBA:REPOSITORY-PROXY) _KIND)
  (STATIC-CALL ("get_primitive" OBJ)
   :OUTPUT ((OUTPUT)
            (MARSHAL _KIND
                     (SYMBOL-TYPECODE 'OMG.ORG/CORBA:PRIMITIVEKIND)
                     OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:PRIMITIVEDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "LOOKUP_ID" ((OBJ OMG.ORG/CORBA:REPOSITORY-PROXY) _SEARCH_ID)
  (STATIC-CALL ("lookup_id" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _SEARCH_ID OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTAINED) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-INTERFACE OMG.ORG/CORBA:ALIASDEF (OMG.ORG/CORBA:TYPEDEFDEF)
 :PROXY (OMG.ORG/CORBA:ALIASDEF-PROXY OMG.ORG/CORBA:ALIASDEF
         OMG.ORG/CORBA:TYPEDEFDEF-PROXY)
 :ID "IDL:omg.org/CORBA/AliasDef:1.0"
 :NAME "AliasDef")

(DEFINE-METHOD "ORIGINAL_TYPE_DEF" ((OBJ OMG.ORG/CORBA:ALIASDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_original_type_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)))

(DEFINE-METHOD (SETF "ORIGINAL_TYPE_DEF") (NEWVAL
                                           (OBJ OMG.ORG/CORBA:ALIASDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_original_type_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
    NEWVAL))

(DEFINE-INTERFACE OMG.ORG/CORBA:ENUMDEF (OMG.ORG/CORBA:TYPEDEFDEF)
 :PROXY (OMG.ORG/CORBA:ENUMDEF-PROXY OMG.ORG/CORBA:ENUMDEF
         OMG.ORG/CORBA:TYPEDEFDEF-PROXY)
 :ID "IDL:omg.org/CORBA/EnumDef:1.0"
 :NAME "EnumDef")

(DEFINE-METHOD "MEMBERS" ((OBJ OMG.ORG/CORBA:ENUMDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_members"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ENUMMEMBERSEQ)))

(DEFINE-METHOD (SETF "MEMBERS") (NEWVAL (OBJ OMG.ORG/CORBA:ENUMDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_members"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ENUMMEMBERSEQ)
    NEWVAL))

(DEFINE-INTERFACE OMG.ORG/CORBA:UNIONDEF (OMG.ORG/CORBA:TYPEDEFDEF)
 :PROXY (OMG.ORG/CORBA:UNIONDEF-PROXY OMG.ORG/CORBA:UNIONDEF
         OMG.ORG/CORBA:TYPEDEFDEF-PROXY)
 :ID "IDL:omg.org/CORBA/UnionDef:1.0"
 :NAME "UnionDef")

(DEFINE-METHOD "MEMBERS" ((OBJ OMG.ORG/CORBA:UNIONDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_members"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:UNIONMEMBERSEQ)))

(DEFINE-METHOD (SETF "MEMBERS") (NEWVAL (OBJ OMG.ORG/CORBA:UNIONDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_members"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:UNIONMEMBERSEQ)
    NEWVAL))

(DEFINE-METHOD "DISCRIMINATOR_TYPE_DEF" ((OBJ OMG.ORG/CORBA:UNIONDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_discriminator_type_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)))

(DEFINE-METHOD (SETF "DISCRIMINATOR_TYPE_DEF") (NEWVAL
                                                (OBJ
                                                 OMG.ORG/CORBA:UNIONDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_discriminator_type_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
    NEWVAL))

(DEFINE-METHOD "DISCRIMINATOR_TYPE" ((OBJ OMG.ORG/CORBA:UNIONDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_discriminator_type" OMG.ORG/CORBA:TC_TYPECODE))

(DEFINE-INTERFACE OMG.ORG/CORBA:STRUCTDEF (OMG.ORG/CORBA:TYPEDEFDEF)
 :PROXY (OMG.ORG/CORBA:STRUCTDEF-PROXY OMG.ORG/CORBA:STRUCTDEF
         OMG.ORG/CORBA:TYPEDEFDEF-PROXY)
 :ID "IDL:omg.org/CORBA/StructDef:1.0"
 :NAME "StructDef")

(DEFINE-METHOD "MEMBERS" ((OBJ OMG.ORG/CORBA:STRUCTDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_members"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:STRUCTMEMBERSEQ)))

(DEFINE-METHOD (SETF "MEMBERS") (NEWVAL (OBJ OMG.ORG/CORBA:STRUCTDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_members"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:STRUCTMEMBERSEQ)
    NEWVAL))
