
(IN-PACKAGE :CLORB)

(DEFINE-STRUCT OMG.ORG/CORBA:INTERFACEDESCRIPTION
 :ID "IDL:omg.org/CORBA/InterfaceDescription:1.0"
 :NAME "InterfaceDescription"
 :MEMBERS (("name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) NAME)
           ("id" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID) ID)
           ("defined_in" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID)
            DEFINED_IN)
           ("version" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:VERSIONSPEC) VERSION)
           ("base_interfaces" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYIDSEQ)
            BASE_INTERFACES))
 :READ ((BUFFER)
        (OMG.ORG/CORBA:INTERFACEDESCRIPTION
          :NAME
          (UNMARSHAL-STRING BUFFER)
          :ID
          (UNMARSHAL-STRING BUFFER)
          :DEFINED_IN
          (UNMARSHAL-STRING BUFFER)
          :VERSION
          (UNMARSHAL-STRING BUFFER)
          :BASE_INTERFACES
          (UNMARSHAL-SEQUENCE #'UNMARSHAL-STRING BUFFER)))
 :WRITE ((OBJ BUFFER) (MARSHAL-STRING (OMG.ORG/FEATURES:NAME OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:ID OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:DEFINED_IN OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:VERSION OBJ) BUFFER)
         (MARSHAL-SEQUENCE
           (OMG.ORG/FEATURES:BASE_INTERFACES OBJ)
           #'MARSHAL-STRING
           BUFFER)))

(DEFINE-ALIAS OMG.ORG/CORBA:ATTRDESCRIPTIONSEQ
 :ID "IDL:omg.org/CORBA/AttrDescriptionSeq:1.0"
 :NAME "AttrDescriptionSeq"
 :TYPE SEQUENCE
 :TYPECODE (create-sequence-tc
             0
             (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ATTRIBUTEDESCRIPTION)))

(DEFINE-ALIAS OMG.ORG/CORBA:OPDESCRIPTIONSEQ
 :ID "IDL:omg.org/CORBA/OpDescriptionSeq:1.0"
 :NAME "OpDescriptionSeq"
 :TYPE SEQUENCE
 :TYPECODE (create-sequence-tc
             0
             (SYMBOL-TYPECODE 'OMG.ORG/CORBA:OPERATIONDESCRIPTION)))

(DEFINE-ALIAS OMG.ORG/CORBA:REPOSITORYIDSEQ
 :ID "IDL:omg.org/CORBA/RepositoryIdSeq:1.0"
 :NAME "RepositoryIdSeq"
 :TYPE SEQUENCE
 :TYPECODE (create-sequence-tc
             0
             (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID)))

(DEFINE-STRUCT OMG.ORG/CORBA:OPERATIONDESCRIPTION
 :ID "IDL:omg.org/CORBA/OperationDescription:1.0"
 :NAME "OperationDescription"
 :MEMBERS (("name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) NAME)
           ("id" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID) ID)
           ("defined_in" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID)
            DEFINED_IN)
           ("version" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:VERSIONSPEC) VERSION)
           ("result" OMG.ORG/CORBA:TC_TYPECODE RESULT)
           ("mode" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:OPERATIONMODE) MODE)
           ("contexts" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTEXTIDSEQ) CONTEXTS)
           ("parameters" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:PARDESCRIPTIONSEQ)
            PARAMETERS)
           ("exceptions" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:EXCDESCRIPTIONSEQ)
            EXCEPTIONS))
 :READ ((BUFFER)
        (OMG.ORG/CORBA:OPERATIONDESCRIPTION
          :NAME
          (UNMARSHAL-STRING BUFFER)
          :ID
          (UNMARSHAL-STRING BUFFER)
          :DEFINED_IN
          (UNMARSHAL-STRING BUFFER)
          :VERSION
          (UNMARSHAL-STRING BUFFER)
          :RESULT
          (UNMARSHAL OMG.ORG/CORBA:TC_TYPECODE BUFFER)
          :MODE
          (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:OPERATIONMODE) BUFFER)
          :CONTEXTS
          (UNMARSHAL-SEQUENCE #'UNMARSHAL-STRING BUFFER)
          :PARAMETERS
          (UNMARSHAL-SEQUENCE
            (LAMBDA (BUFFER)
              (STRUCT-READ 'OMG.ORG/CORBA:PARAMETERDESCRIPTION BUFFER))
            BUFFER)
          :EXCEPTIONS
          (UNMARSHAL-SEQUENCE
            (LAMBDA (BUFFER)
              (STRUCT-READ 'OMG.ORG/CORBA:EXCEPTIONDESCRIPTION BUFFER))
            BUFFER)))
 :WRITE ((OBJ BUFFER) (MARSHAL-STRING (OMG.ORG/FEATURES:NAME OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:ID OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:DEFINED_IN OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:VERSION OBJ) BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:RESULT OBJ)
                  OMG.ORG/CORBA:TC_TYPECODE
                  BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:MODE OBJ)
                  (SYMBOL-TYPECODE 'OMG.ORG/CORBA:OPERATIONMODE)
                  BUFFER)
         (MARSHAL-SEQUENCE
           (OMG.ORG/FEATURES:CONTEXTS OBJ)
           #'MARSHAL-STRING
           BUFFER)
         (MARSHAL-SEQUENCE
           (OMG.ORG/FEATURES:PARAMETERS OBJ)
           (LAMBDA (OBJ BUFFER)
             (STRUCT-WRITE OBJ 'OMG.ORG/CORBA:PARAMETERDESCRIPTION BUFFER))
           BUFFER)
         (MARSHAL-SEQUENCE
           (OMG.ORG/FEATURES:EXCEPTIONS OBJ)
           (LAMBDA (OBJ BUFFER)
             (STRUCT-WRITE OBJ 'OMG.ORG/CORBA:EXCEPTIONDESCRIPTION BUFFER))
           BUFFER)))

(DEFINE-ALIAS OMG.ORG/CORBA:EXCDESCRIPTIONSEQ
 :ID "IDL:omg.org/CORBA/ExcDescriptionSeq:1.0"
 :NAME "ExcDescriptionSeq"
 :TYPE SEQUENCE
 :TYPECODE (create-sequence-tc
             0
             (SYMBOL-TYPECODE 'OMG.ORG/CORBA:EXCEPTIONDESCRIPTION)))

(DEFINE-ALIAS OMG.ORG/CORBA:EXCEPTIONDEFSEQ
 :ID "IDL:omg.org/CORBA/ExceptionDefSeq:1.0"
 :NAME "ExceptionDefSeq"
 :TYPE SEQUENCE
 :TYPECODE (create-sequence-tc
             0
             (SYMBOL-TYPECODE 'OMG.ORG/CORBA:EXCEPTIONDEF)))

(DEFINE-ALIAS OMG.ORG/CORBA:CONTEXTIDSEQ
 :ID "IDL:omg.org/CORBA/ContextIdSeq:1.0"
 :NAME "ContextIdSeq"
 :TYPE SEQUENCE
 :TYPECODE (create-sequence-tc
             0
             (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTEXTIDENTIFIER)))

(DEFINE-ALIAS OMG.ORG/CORBA:CONTEXTIDENTIFIER
 :ID "IDL:omg.org/CORBA/ContextIdentifier:1.0"
 :NAME "ContextIdentifier"
 :TYPE OMG.ORG/CORBA:IDENTIFIER
 :TYPECODE (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER))

(DEFINE-ALIAS OMG.ORG/CORBA:PARDESCRIPTIONSEQ
 :ID "IDL:omg.org/CORBA/ParDescriptionSeq:1.0"
 :NAME "ParDescriptionSeq"
 :TYPE SEQUENCE
 :TYPECODE (create-sequence-tc
             0
             (SYMBOL-TYPECODE 'OMG.ORG/CORBA:PARAMETERDESCRIPTION)))

(DEFINE-STRUCT OMG.ORG/CORBA:PARAMETERDESCRIPTION
 :ID "IDL:omg.org/CORBA/ParameterDescription:1.0"
 :NAME "ParameterDescription"
 :MEMBERS (("name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) NAME)
           ("type" OMG.ORG/CORBA:TC_TYPECODE TYPE)
           ("type_def" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE) TYPE_DEF)
           ("mode" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:PARAMETERMODE) MODE))
 :READ ((BUFFER)
        (OMG.ORG/CORBA:PARAMETERDESCRIPTION
          :NAME
          (UNMARSHAL-STRING BUFFER)
          :TYPE
          (UNMARSHAL OMG.ORG/CORBA:TC_TYPECODE BUFFER)
          :TYPE_DEF
          (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE) BUFFER)
          :MODE
          (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:PARAMETERMODE) BUFFER)))
 :WRITE ((OBJ BUFFER) (MARSHAL-STRING (OMG.ORG/FEATURES:NAME OBJ) BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:TYPE OBJ) OMG.ORG/CORBA:TC_TYPECODE BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:TYPE_DEF OBJ)
                  (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
                  BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:MODE OBJ)
                  (SYMBOL-TYPECODE 'OMG.ORG/CORBA:PARAMETERMODE)
                  BUFFER)))

(DEFINE-ENUM OMG.ORG/CORBA:PARAMETERMODE
 :ID "IDL:omg.org/CORBA/ParameterMode:1.0"
 :NAME "ParameterMode"
 :MEMBERS ("PARAM_IN" "PARAM_OUT" "PARAM_INOUT"))

(DEFINE-ENUM OMG.ORG/CORBA:OPERATIONMODE
 :ID "IDL:omg.org/CORBA/OperationMode:1.0"
 :NAME "OperationMode"
 :MEMBERS ("OP_NORMAL" "OP_ONEWAY"))

(DEFINE-STRUCT OMG.ORG/CORBA:ATTRIBUTEDESCRIPTION
 :ID "IDL:omg.org/CORBA/AttributeDescription:1.0"
 :NAME "AttributeDescription"
 :MEMBERS (("name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) NAME)
           ("id" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID) ID)
           ("defined_in" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID)
            DEFINED_IN)
           ("version" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:VERSIONSPEC) VERSION)
           ("type" OMG.ORG/CORBA:TC_TYPECODE TYPE)
           ("mode" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ATTRIBUTEMODE) MODE))
 :READ ((BUFFER)
        (OMG.ORG/CORBA:ATTRIBUTEDESCRIPTION
          :NAME
          (UNMARSHAL-STRING BUFFER)
          :ID
          (UNMARSHAL-STRING BUFFER)
          :DEFINED_IN
          (UNMARSHAL-STRING BUFFER)
          :VERSION
          (UNMARSHAL-STRING BUFFER)
          :TYPE
          (UNMARSHAL OMG.ORG/CORBA:TC_TYPECODE BUFFER)
          :MODE
          (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ATTRIBUTEMODE) BUFFER)))
 :WRITE ((OBJ BUFFER) (MARSHAL-STRING (OMG.ORG/FEATURES:NAME OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:ID OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:DEFINED_IN OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:VERSION OBJ) BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:TYPE OBJ) OMG.ORG/CORBA:TC_TYPECODE BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:MODE OBJ)
                  (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ATTRIBUTEMODE)
                  BUFFER)))

(DEFINE-ENUM OMG.ORG/CORBA:ATTRIBUTEMODE
 :ID "IDL:omg.org/CORBA/AttributeMode:1.0"
 :NAME "AttributeMode"
 :MEMBERS ("ATTR_NORMAL" "ATTR_READONLY"))

(DEFINE-STRUCT OMG.ORG/CORBA:EXCEPTIONDESCRIPTION
 :ID "IDL:omg.org/CORBA/ExceptionDescription:1.0"
 :NAME "ExceptionDescription"
 :MEMBERS (("name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) NAME)
           ("id" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID) ID)
           ("defined_in" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID)
            DEFINED_IN)
           ("version" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:VERSIONSPEC) VERSION)
           ("type" OMG.ORG/CORBA:TC_TYPECODE TYPE))
 :READ ((BUFFER)
        (OMG.ORG/CORBA:EXCEPTIONDESCRIPTION
          :NAME
          (UNMARSHAL-STRING BUFFER)
          :ID
          (UNMARSHAL-STRING BUFFER)
          :DEFINED_IN
          (UNMARSHAL-STRING BUFFER)
          :VERSION
          (UNMARSHAL-STRING BUFFER)
          :TYPE
          (UNMARSHAL OMG.ORG/CORBA:TC_TYPECODE BUFFER)))
 :WRITE ((OBJ BUFFER) (MARSHAL-STRING (OMG.ORG/FEATURES:NAME OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:ID OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:DEFINED_IN OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:VERSION OBJ) BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:TYPE OBJ)
                  OMG.ORG/CORBA:TC_TYPECODE
                  BUFFER)))

(DEFINE-STRUCT OMG.ORG/CORBA:TYPEDESCRIPTION
 :ID "IDL:omg.org/CORBA/TypeDescription:1.0"
 :NAME "TypeDescription"
 :MEMBERS (("name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) NAME)
           ("id" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID) ID)
           ("defined_in" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID)
            DEFINED_IN)
           ("version" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:VERSIONSPEC) VERSION)
           ("type" OMG.ORG/CORBA:TC_TYPECODE TYPE))
 :READ ((BUFFER)
        (OMG.ORG/CORBA:TYPEDESCRIPTION
          :NAME
          (UNMARSHAL-STRING BUFFER)
          :ID
          (UNMARSHAL-STRING BUFFER)
          :DEFINED_IN
          (UNMARSHAL-STRING BUFFER)
          :VERSION
          (UNMARSHAL-STRING BUFFER)
          :TYPE
          (UNMARSHAL OMG.ORG/CORBA:TC_TYPECODE BUFFER)))
 :WRITE ((OBJ BUFFER) (MARSHAL-STRING (OMG.ORG/FEATURES:NAME OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:ID OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:DEFINED_IN OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:VERSION OBJ) BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:TYPE OBJ)
                  OMG.ORG/CORBA:TC_TYPECODE
                  BUFFER)))

(DEFINE-STRUCT OMG.ORG/CORBA:CONSTANTDESCRIPTION
 :ID "IDL:omg.org/CORBA/ConstantDescription:1.0"
 :NAME "ConstantDescription"
 :MEMBERS (("name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) NAME)
           ("id" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID) ID)
           ("defined_in" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID)
            DEFINED_IN)
           ("version" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:VERSIONSPEC) VERSION)
           ("type" OMG.ORG/CORBA:TC_TYPECODE TYPE)
           ("value" OMG.ORG/CORBA:TC_ANY VALUE))
 :READ ((BUFFER)
        (OMG.ORG/CORBA:CONSTANTDESCRIPTION
          :NAME
          (UNMARSHAL-STRING BUFFER)
          :ID
          (UNMARSHAL-STRING BUFFER)
          :DEFINED_IN
          (UNMARSHAL-STRING BUFFER)
          :VERSION
          (UNMARSHAL-STRING BUFFER)
          :TYPE
          (UNMARSHAL OMG.ORG/CORBA:TC_TYPECODE BUFFER)
          :VALUE
          (UNMARSHAL OMG.ORG/CORBA:TC_ANY BUFFER)))
 :WRITE ((OBJ BUFFER) (MARSHAL-STRING (OMG.ORG/FEATURES:NAME OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:ID OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:DEFINED_IN OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:VERSION OBJ) BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:TYPE OBJ) OMG.ORG/CORBA:TC_TYPECODE BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:VALUE OBJ) OMG.ORG/CORBA:TC_ANY BUFFER)))

(DEFINE-STRUCT OMG.ORG/CORBA:MODULEDESCRIPTION
 :ID "IDL:omg.org/CORBA/ModuleDescription:1.0"
 :NAME "ModuleDescription"
 :MEMBERS (("name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) NAME)
           ("id" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID) ID)
           ("defined_in" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID)
            DEFINED_IN)
           ("version" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:VERSIONSPEC) VERSION))
 :READ ((BUFFER)
        (OMG.ORG/CORBA:MODULEDESCRIPTION
          :NAME
          (UNMARSHAL-STRING BUFFER)
          :ID
          (UNMARSHAL-STRING BUFFER)
          :DEFINED_IN
          (UNMARSHAL-STRING BUFFER)
          :VERSION
          (UNMARSHAL-STRING BUFFER)))
 :WRITE ((OBJ BUFFER) (MARSHAL-STRING (OMG.ORG/FEATURES:NAME OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:ID OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:DEFINED_IN OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:VERSION OBJ) BUFFER)))

(DEFINE-ENUM OMG.ORG/CORBA:PRIMITIVEKIND
 :ID "IDL:omg.org/CORBA/PrimitiveKind:1.0"
 :NAME "PrimitiveKind"
 :MEMBERS ("pk_null" "pk_void" "pk_short" "pk_long" "pk_ushort" "pk_ulong"
           "pk_float" "pk_double" "pk_boolean" "pk_char" "pk_octet" "pk_any"
           "pk_TypeCode" "pk_Principal" "pk_string" "pk_objref" "pk_longlong"
           "pk_ulonglong" "pk_longdouble" "pk_wchar" "pk_wstring"))

(DEFINE-ALIAS OMG.ORG/CORBA:ENUMMEMBERSEQ
 :ID "IDL:omg.org/CORBA/EnumMemberSeq:1.0"
 :NAME "EnumMemberSeq"
 :TYPE SEQUENCE
 :TYPECODE (create-sequence-tc
             0
             (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER)))

(DEFINE-ALIAS OMG.ORG/CORBA:UNIONMEMBERSEQ
 :ID "IDL:omg.org/CORBA/UnionMemberSeq:1.0"
 :NAME "UnionMemberSeq"
 :TYPE SEQUENCE
 :TYPECODE (create-sequence-tc
             0
             (SYMBOL-TYPECODE 'OMG.ORG/CORBA:UNIONMEMBER)))

(DEFINE-STRUCT OMG.ORG/CORBA:UNIONMEMBER
 :ID "IDL:omg.org/CORBA/UnionMember:1.0"
 :NAME "UnionMember"
 :MEMBERS (("name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) NAME)
           ("label" OMG.ORG/CORBA:TC_ANY LABEL)
           ("type" OMG.ORG/CORBA:TC_TYPECODE TYPE)
           ("type_def" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE) TYPE_DEF))
 :READ ((BUFFER)
        (OMG.ORG/CORBA:UNIONMEMBER :NAME
                                   (UNMARSHAL-STRING BUFFER)
                                   :LABEL
                                   (UNMARSHAL OMG.ORG/CORBA:TC_ANY BUFFER)
                                   :TYPE
                                   (UNMARSHAL OMG.ORG/CORBA:TC_TYPECODE BUFFER)
                                   :TYPE_DEF
                                   (UNMARSHAL (SYMBOL-TYPECODE
                                               'OMG.ORG/CORBA:IDLTYPE)
                                              BUFFER)))
 :WRITE ((OBJ BUFFER) (MARSHAL-STRING (OMG.ORG/FEATURES:NAME OBJ) BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:LABEL OBJ) OMG.ORG/CORBA:TC_ANY BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:TYPE OBJ) OMG.ORG/CORBA:TC_TYPECODE BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:TYPE_DEF OBJ)
                  (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
                  BUFFER)))

(DEFINE-ALIAS OMG.ORG/CORBA:STRUCTMEMBERSEQ
 :ID "IDL:omg.org/CORBA/StructMemberSeq:1.0"
 :NAME "StructMemberSeq"
 :TYPE SEQUENCE
 :TYPECODE (create-sequence-tc
             0
             (SYMBOL-TYPECODE 'OMG.ORG/CORBA:STRUCTMEMBER)))

(DEFINE-STRUCT OMG.ORG/CORBA:STRUCTMEMBER
 :ID "IDL:omg.org/CORBA/StructMember:1.0"
 :NAME "StructMember"
 :MEMBERS (("name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) NAME)
           ("type" OMG.ORG/CORBA:TC_TYPECODE TYPE)
           ("type_def" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE) TYPE_DEF))
 :READ ((BUFFER)
        (OMG.ORG/CORBA:STRUCTMEMBER :NAME
                                    (UNMARSHAL-STRING BUFFER)
                                    :TYPE
                                    (UNMARSHAL OMG.ORG/CORBA:TC_TYPECODE
                                               BUFFER)
                                    :TYPE_DEF
                                    (UNMARSHAL (SYMBOL-TYPECODE
                                                'OMG.ORG/CORBA:IDLTYPE)
                                               BUFFER)))
 :WRITE ((OBJ BUFFER) (MARSHAL-STRING (OMG.ORG/FEATURES:NAME OBJ) BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:TYPE OBJ) OMG.ORG/CORBA:TC_TYPECODE BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:TYPE_DEF OBJ)
                  (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
                  BUFFER)))

(DEFINE-ALIAS OMG.ORG/CORBA:CONTAINEDSEQ
 :ID "IDL:omg.org/CORBA/ContainedSeq:1.0"
 :NAME "ContainedSeq"
 :TYPE SEQUENCE
 :TYPECODE (create-sequence-tc
             0
             (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTAINED)))

(DEFINE-ALIAS OMG.ORG/CORBA:INTERFACEDEFSEQ
 :ID "IDL:omg.org/CORBA/InterfaceDefSeq:1.0"
 :NAME "InterfaceDefSeq"
 :TYPE SEQUENCE
 :TYPECODE (create-sequence-tc
             0
             (SYMBOL-TYPECODE 'OMG.ORG/CORBA:INTERFACEDEF)))

(DEFINE-ALIAS OMG.ORG/CORBA:VERSIONSPEC
 :ID "IDL:omg.org/CORBA/VersionSpec:1.0"
 :NAME "VersionSpec"
 :TYPE OMG.ORG/CORBA:STRING
 :TYPECODE OMG.ORG/CORBA:TC_STRING)

(DEFINE-ENUM OMG.ORG/CORBA:DEFINITIONKIND
 :ID "IDL:omg.org/CORBA/DefinitionKind:1.0"
 :NAME "DefinitionKind"
 :MEMBERS ("dk_none" "dk_all" "dk_Attribute" "dk_Constant" "dk_Exception"
           "dk_Interface" "dk_Module" "dk_Operation" "dk_Typedef" "dk_Alias"
           "dk_Struct" "dk_Union" "dk_Enum" "dk_Primitive" "dk_String"
           "dk_Sequence" "dk_Array" "dk_Repository" "dk_Wstring" "dk_Fixed"))

(DEFINE-ALIAS OMG.ORG/CORBA:REPOSITORYID
 :ID "IDL:omg.org/CORBA/RepositoryId:1.0"
 :NAME "RepositoryId"
 :TYPE OMG.ORG/CORBA:STRING
 :TYPECODE OMG.ORG/CORBA:TC_STRING)

(DEFINE-ALIAS OMG.ORG/CORBA:SCOPEDNAME
 :ID "IDL:omg.org/CORBA/ScopedName:1.0"
 :NAME "ScopedName"
 :TYPE OMG.ORG/CORBA:STRING
 :TYPECODE OMG.ORG/CORBA:TC_STRING)

(DEFINE-ALIAS OMG.ORG/CORBA:IDENTIFIER
 :ID "IDL:omg.org/CORBA/Identifier:1.0"
 :NAME "Identifier"
 :TYPE OMG.ORG/CORBA:STRING
 :TYPECODE OMG.ORG/CORBA:TC_STRING)

(DEFINE-INTERFACE OMG.ORG/CORBA:IROBJECT (OBJECT)
 :PROXY (OMG.ORG/CORBA:IROBJECT-PROXY OMG.ORG/CORBA:IROBJECT
         OMG.ORG/CORBA:PROXY)
 :ID "IDL:omg.org/CORBA/IRObject:1.0"
 :NAME "IRObject")

(DEFINE-METHOD "DESTROY" ((OBJ OMG.ORG/CORBA:IROBJECT-PROXY))
  (STATIC-CALL ("destroy" OBJ)
   :OUTPUT ((OUTPUT))
   :INPUT ((INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "DEF_KIND" ((OBJ OMG.ORG/CORBA:IROBJECT-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_def_kind"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:DEFINITIONKIND)))

(DEFINE-INTERFACE OMG.ORG/CORBA:IDLTYPE (OMG.ORG/CORBA:IROBJECT)
 :PROXY (OMG.ORG/CORBA:IDLTYPE-PROXY OMG.ORG/CORBA:IDLTYPE
         OMG.ORG/CORBA:IROBJECT-PROXY)
 :ID "IDL:omg.org/CORBA/IDLType:1.0"
 :NAME "IDLType")

(DEFINE-METHOD "TYPE" ((OBJ OMG.ORG/CORBA:IDLTYPE-PROXY))
  (GET-ATTRIBUTE OBJ "_get_type" OMG.ORG/CORBA:TC_TYPECODE))

(DEFINE-INTERFACE OMG.ORG/CORBA:CONTAINER (OMG.ORG/CORBA:IROBJECT)
 :PROXY (OMG.ORG/CORBA:CONTAINER-PROXY OMG.ORG/CORBA:CONTAINER
         OMG.ORG/CORBA:IROBJECT-PROXY)
 :ID "IDL:omg.org/CORBA/Container:1.0"
 :NAME "Container")

(DEFINE-METHOD "CREATE_INTERFACE" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY) _ID
                                   _NAME _VERSION _BASE_INTERFACES)
  (STATIC-CALL ("create_interface" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _ID OUTPUT) (MARSHAL-STRING _NAME OUTPUT)
            (MARSHAL-STRING _VERSION OUTPUT)
            (MARSHAL-SEQUENCE
              _BASE_INTERFACES
              (LAMBDA (OBJ BUFFER)
                (MARSHAL OBJ
                         (SYMBOL-TYPECODE 'OMG.ORG/CORBA:INTERFACEDEF)
                         BUFFER))
              OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:INTERFACEDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_ALIAS" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY) _ID _NAME
                               _VERSION _ORIGINAL_TYPE)
  (STATIC-CALL ("create_alias" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _ID OUTPUT) (MARSHAL-STRING _NAME OUTPUT)
            (MARSHAL-STRING _VERSION OUTPUT)
            (MARSHAL _ORIGINAL_TYPE
                     (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
                     OUTPUT))
   :INPUT ((INPUT) (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ALIASDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_ENUM" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY) _ID _NAME
                              _VERSION _MEMBERS)
  (STATIC-CALL ("create_enum" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _ID OUTPUT) (MARSHAL-STRING _NAME OUTPUT)
            (MARSHAL-STRING _VERSION OUTPUT)
            (MARSHAL-SEQUENCE _MEMBERS #'MARSHAL-STRING OUTPUT))
   :INPUT ((INPUT) (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ENUMDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_UNION" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY) _ID _NAME
                               _VERSION _DISCRIMINATOR_TYPE _MEMBERS)
  (STATIC-CALL ("create_union" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _ID OUTPUT) (MARSHAL-STRING _NAME OUTPUT)
            (MARSHAL-STRING _VERSION OUTPUT)
            (MARSHAL _DISCRIMINATOR_TYPE
                     (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
                     OUTPUT)
            (MARSHAL-SEQUENCE
              _MEMBERS
              (LAMBDA (OBJ BUFFER)
                (STRUCT-WRITE OBJ 'OMG.ORG/CORBA:UNIONMEMBER BUFFER))
              OUTPUT))
   :INPUT ((INPUT) (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:UNIONDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_EXCEPTION" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY) _ID
                                   _NAME _VERSION _MEMBERS)
  (STATIC-CALL ("create_exception" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _ID OUTPUT) (MARSHAL-STRING _NAME OUTPUT)
            (MARSHAL-STRING _VERSION OUTPUT)
            (MARSHAL-SEQUENCE
              _MEMBERS
              (LAMBDA (OBJ BUFFER)
                (STRUCT-WRITE OBJ 'OMG.ORG/CORBA:STRUCTMEMBER BUFFER))
              OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:EXCEPTIONDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_STRUCT" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY) _ID _NAME
                                _VERSION _MEMBERS)
  (STATIC-CALL ("create_struct" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _ID OUTPUT) (MARSHAL-STRING _NAME OUTPUT)
            (MARSHAL-STRING _VERSION OUTPUT)
            (MARSHAL-SEQUENCE
              _MEMBERS
              (LAMBDA (OBJ BUFFER)
                (STRUCT-WRITE OBJ 'OMG.ORG/CORBA:STRUCTMEMBER BUFFER))
              OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:STRUCTDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_CONSTANT" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY) _ID _NAME
                                  _VERSION _TYPE _VALUE)
  (STATIC-CALL ("create_constant" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _ID OUTPUT) (MARSHAL-STRING _NAME OUTPUT)
            (MARSHAL-STRING _VERSION OUTPUT)
            (MARSHAL _TYPE (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE) OUTPUT)
            (MARSHAL _VALUE OMG.ORG/CORBA:TC_ANY OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONSTANTDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_MODULE" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY) _ID _NAME
                                _VERSION)
  (STATIC-CALL ("create_module" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _ID OUTPUT) (MARSHAL-STRING _NAME OUTPUT)
            (MARSHAL-STRING _VERSION OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:MODULEDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "DESCRIBE_CONTENTS" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY)
                                    _LIMIT_TYPE _EXCLUDE_INHERITED
                                    _MAX_RETURNED_OBJS)
  (STATIC-CALL ("describe_contents" OBJ)
   :OUTPUT ((OUTPUT)
            (MARSHAL _LIMIT_TYPE
                     (SYMBOL-TYPECODE 'OMG.ORG/CORBA:DEFINITIONKIND)
                     OUTPUT)
            (MARSHAL-BOOL _EXCLUDE_INHERITED OUTPUT)
            (MARSHAL-LONG _MAX_RETURNED_OBJS OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL-SEQUENCE
             (LAMBDA (BUFFER)
               (STRUCT-READ 'OMG.ORG/CORBA:CONTAINER/DESCRIPTION BUFFER))
             INPUT))
   :EXCEPTIONS NIL))

(DEFINE-ALIAS OMG.ORG/CORBA:CONTAINER/DESCRIPTIONSEQ
 :ID "IDL:omg.org/CORBA/Container/DescriptionSeq:1.0"
 :NAME "DescriptionSeq"
 :TYPE SEQUENCE
 :TYPECODE (create-sequence-tc
             0
             (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTAINER/DESCRIPTION)))

(DEFINE-STRUCT OMG.ORG/CORBA:CONTAINER/DESCRIPTION
 :ID "IDL:omg.org/CORBA/Container/Description:1.0"
 :NAME "Description"
 :MEMBERS (("contained_object" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTAINED)
            CONTAINED_OBJECT)
           ("kind" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:DEFINITIONKIND) KIND)
           ("value" OMG.ORG/CORBA:TC_ANY VALUE))
 :READ ((BUFFER)
        (OMG.ORG/CORBA:CONTAINER/DESCRIPTION
          :CONTAINED_OBJECT
          (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTAINED) BUFFER)
          :KIND
          (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:DEFINITIONKIND) BUFFER)
          :VALUE
          (UNMARSHAL OMG.ORG/CORBA:TC_ANY BUFFER)))
 :WRITE ((OBJ BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:CONTAINED_OBJECT OBJ)
                  (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTAINED)
                  BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:KIND OBJ)
                  (SYMBOL-TYPECODE 'OMG.ORG/CORBA:DEFINITIONKIND)
                  BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:VALUE OBJ) OMG.ORG/CORBA:TC_ANY BUFFER)))

(DEFINE-METHOD "LOOKUP_NAME" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY) _SEARCH_NAME
                              _LEVELS_TO_SEARCH _LIMIT_TYPE _EXCLUDE_INHERITED)
  (STATIC-CALL ("lookup_name" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _SEARCH_NAME OUTPUT)
            (MARSHAL-LONG _LEVELS_TO_SEARCH OUTPUT)
            (MARSHAL _LIMIT_TYPE
                     (SYMBOL-TYPECODE 'OMG.ORG/CORBA:DEFINITIONKIND)
                     OUTPUT)
            (MARSHAL-BOOL _EXCLUDE_INHERITED OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL-SEQUENCE
             (LAMBDA (BUFFER)
               (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTAINED) BUFFER))
             INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CONTENTS" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY) _LIMIT_TYPE
                           _EXCLUDE_INHERITED)
  (STATIC-CALL ("contents" OBJ)
   :OUTPUT ((OUTPUT)
            (MARSHAL _LIMIT_TYPE
                     (SYMBOL-TYPECODE 'OMG.ORG/CORBA:DEFINITIONKIND)
                     OUTPUT)
            (MARSHAL-BOOL _EXCLUDE_INHERITED OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL-SEQUENCE
             (LAMBDA (BUFFER)
               (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTAINED) BUFFER))
             INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "LOOKUP" ((OBJ OMG.ORG/CORBA:CONTAINER-PROXY) _SEARCH_NAME)
  (STATIC-CALL ("lookup" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _SEARCH_NAME OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTAINED) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-INTERFACE OMG.ORG/CORBA:CONTAINED (OMG.ORG/CORBA:IROBJECT)
 :PROXY (OMG.ORG/CORBA:CONTAINED-PROXY OMG.ORG/CORBA:CONTAINED
         OMG.ORG/CORBA:IROBJECT-PROXY)
 :ID "IDL:omg.org/CORBA/Contained:1.0"
 :NAME "Contained")

(DEFINE-METHOD "MOVE" ((OBJ OMG.ORG/CORBA:CONTAINED-PROXY) _NEW_CONTAINER
                       _NEW_NAME _NEW_VERSION)
  (STATIC-CALL ("move" OBJ)
   :OUTPUT ((OUTPUT)
            (MARSHAL _NEW_CONTAINER
                     (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTAINER)
                     OUTPUT)
            (MARSHAL-STRING _NEW_NAME OUTPUT)
            (MARSHAL-STRING _NEW_VERSION OUTPUT))
   :INPUT ((INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "DESCRIBE" ((OBJ OMG.ORG/CORBA:CONTAINED-PROXY))
  (STATIC-CALL ("describe" OBJ)
   :OUTPUT ((OUTPUT))
   :INPUT ((INPUT) (STRUCT-READ 'OMG.ORG/CORBA:CONTAINED/DESCRIPTION INPUT))
   :EXCEPTIONS NIL))

(DEFINE-STRUCT OMG.ORG/CORBA:CONTAINED/DESCRIPTION
 :ID "IDL:omg.org/CORBA/Contained/Description:1.0"
 :NAME "Description"
 :MEMBERS (("kind" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:DEFINITIONKIND) KIND)
           ("value" OMG.ORG/CORBA:TC_ANY VALUE))
 :READ ((BUFFER)
        (OMG.ORG/CORBA:CONTAINED/DESCRIPTION
          :KIND
          (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:DEFINITIONKIND) BUFFER)
          :VALUE
          (UNMARSHAL OMG.ORG/CORBA:TC_ANY BUFFER)))
 :WRITE ((OBJ BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:KIND OBJ)
                  (SYMBOL-TYPECODE 'OMG.ORG/CORBA:DEFINITIONKIND)
                  BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:VALUE OBJ) OMG.ORG/CORBA:TC_ANY BUFFER)))

(DEFINE-METHOD "CONTAINING_REPOSITORY" ((OBJ OMG.ORG/CORBA:CONTAINED-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_containing_repository"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORY)))

(DEFINE-METHOD "ABSOLUTE_NAME" ((OBJ OMG.ORG/CORBA:CONTAINED-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_absolute_name"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:SCOPEDNAME)))

(DEFINE-METHOD "DEFINED_IN" ((OBJ OMG.ORG/CORBA:CONTAINED-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_defined_in"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTAINER)))

(DEFINE-METHOD "VERSION" ((OBJ OMG.ORG/CORBA:CONTAINED-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_version"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:VERSIONSPEC)))

(DEFINE-METHOD (SETF "VERSION") (NEWVAL (OBJ OMG.ORG/CORBA:CONTAINED-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_version"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:VERSIONSPEC)
    NEWVAL))

(DEFINE-METHOD "NAME" ((OBJ OMG.ORG/CORBA:CONTAINED-PROXY))
  (GET-ATTRIBUTE OBJ "_get_name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER)))

(DEFINE-METHOD (SETF "NAME") (NEWVAL (OBJ OMG.ORG/CORBA:CONTAINED-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_name"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER)
    NEWVAL))

(DEFINE-METHOD "ID" ((OBJ OMG.ORG/CORBA:CONTAINED-PROXY))
  (GET-ATTRIBUTE OBJ "_get_id" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID)))

(DEFINE-METHOD (SETF "ID") (NEWVAL (OBJ OMG.ORG/CORBA:CONTAINED-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_id"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID)
    NEWVAL))

(DEFINE-INTERFACE OMG.ORG/CORBA:INTERFACEDEF (OMG.ORG/CORBA:CONTAINER
                                              OMG.ORG/CORBA:CONTAINED
                                              OMG.ORG/CORBA:IDLTYPE)
 :PROXY (OMG.ORG/CORBA:INTERFACEDEF-PROXY OMG.ORG/CORBA:INTERFACEDEF
         OMG.ORG/CORBA:CONTAINER-PROXY OMG.ORG/CORBA:CONTAINED-PROXY
         OMG.ORG/CORBA:IDLTYPE-PROXY)
 :ID "IDL:omg.org/CORBA/InterfaceDef:1.0"
 :NAME "InterfaceDef")

(DEFINE-METHOD "CREATE_OPERATION" ((OBJ OMG.ORG/CORBA:INTERFACEDEF-PROXY) _ID
                                   _NAME _VERSION _RESULT _MODE _PARAMS
                                   _EXCEPTIONS _CONTEXTS)
  (STATIC-CALL ("create_operation" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _ID OUTPUT) (MARSHAL-STRING _NAME OUTPUT)
            (MARSHAL-STRING _VERSION OUTPUT)
            (MARSHAL _RESULT (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE) OUTPUT)
            (MARSHAL _MODE
                     (SYMBOL-TYPECODE 'OMG.ORG/CORBA:OPERATIONMODE)
                     OUTPUT)
            (MARSHAL-SEQUENCE
              _PARAMS
              (LAMBDA (OBJ BUFFER)
                (STRUCT-WRITE OBJ 'OMG.ORG/CORBA:PARAMETERDESCRIPTION BUFFER))
              OUTPUT)
            (MARSHAL-SEQUENCE
              _EXCEPTIONS
              (LAMBDA (OBJ BUFFER)
                (MARSHAL OBJ
                         (SYMBOL-TYPECODE 'OMG.ORG/CORBA:EXCEPTIONDEF)
                         BUFFER))
              OUTPUT)
            (MARSHAL-SEQUENCE _CONTEXTS #'MARSHAL-STRING OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:OPERATIONDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_ATTRIBUTE" ((OBJ OMG.ORG/CORBA:INTERFACEDEF-PROXY) _ID
                                   _NAME _VERSION _TYPE _MODE)
  (STATIC-CALL ("create_attribute" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _ID OUTPUT) (MARSHAL-STRING _NAME OUTPUT)
            (MARSHAL-STRING _VERSION OUTPUT)
            (MARSHAL _TYPE (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE) OUTPUT)
            (MARSHAL _MODE
                     (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ATTRIBUTEMODE)
                     OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ATTRIBUTEDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "DESCRIBE_INTERFACE" ((OBJ OMG.ORG/CORBA:INTERFACEDEF-PROXY))
  (STATIC-CALL ("describe_interface" OBJ)
   :OUTPUT ((OUTPUT))
   :INPUT ((INPUT)
           (STRUCT-READ 'OMG.ORG/CORBA:INTERFACEDEF/FULLINTERFACEDESCRIPTION
                        INPUT))
   :EXCEPTIONS NIL))

(DEFINE-STRUCT OMG.ORG/CORBA:INTERFACEDEF/FULLINTERFACEDESCRIPTION
 :ID "IDL:omg.org/CORBA/InterfaceDef/FullInterfaceDescription:1.0"
 :NAME "FullInterfaceDescription"
 :MEMBERS (("name" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDENTIFIER) NAME)
           ("id" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID) ID)
           ("defined_in" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYID)
            DEFINED_IN)
           ("version" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:VERSIONSPEC) VERSION)
           ("operations" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:OPDESCRIPTIONSEQ)
            OPERATIONS)
           ("attributes" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ATTRDESCRIPTIONSEQ)
            ATTRIBUTES)
           ("base_interfaces" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:REPOSITORYIDSEQ)
            BASE_INTERFACES)
           ("type" OMG.ORG/CORBA:TC_TYPECODE TYPE))
 :READ ((BUFFER)
        (OMG.ORG/CORBA:INTERFACEDEF/FULLINTERFACEDESCRIPTION
          :NAME
          (UNMARSHAL-STRING BUFFER)
          :ID
          (UNMARSHAL-STRING BUFFER)
          :DEFINED_IN
          (UNMARSHAL-STRING BUFFER)
          :VERSION
          (UNMARSHAL-STRING BUFFER)
          :OPERATIONS
          (UNMARSHAL-SEQUENCE
            (LAMBDA (BUFFER)
              (STRUCT-READ 'OMG.ORG/CORBA:OPERATIONDESCRIPTION BUFFER))
            BUFFER)
          :ATTRIBUTES
          (UNMARSHAL-SEQUENCE
            (LAMBDA (BUFFER)
              (STRUCT-READ 'OMG.ORG/CORBA:ATTRIBUTEDESCRIPTION BUFFER))
            BUFFER)
          :BASE_INTERFACES
          (UNMARSHAL-SEQUENCE #'UNMARSHAL-STRING BUFFER)
          :TYPE
          (UNMARSHAL OMG.ORG/CORBA:TC_TYPECODE BUFFER)))
 :WRITE ((OBJ BUFFER) (MARSHAL-STRING (OMG.ORG/FEATURES:NAME OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:ID OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:DEFINED_IN OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:VERSION OBJ) BUFFER)
         (MARSHAL-SEQUENCE
           (OMG.ORG/FEATURES:OPERATIONS OBJ)
           (LAMBDA (OBJ BUFFER)
             (STRUCT-WRITE OBJ 'OMG.ORG/CORBA:OPERATIONDESCRIPTION BUFFER))
           BUFFER)
         (MARSHAL-SEQUENCE
           (OMG.ORG/FEATURES:ATTRIBUTES OBJ)
           (LAMBDA (OBJ BUFFER)
             (STRUCT-WRITE OBJ 'OMG.ORG/CORBA:ATTRIBUTEDESCRIPTION BUFFER))
           BUFFER)
         (MARSHAL-SEQUENCE
           (OMG.ORG/FEATURES:BASE_INTERFACES OBJ)
           #'MARSHAL-STRING
           BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:TYPE OBJ)
                  OMG.ORG/CORBA:TC_TYPECODE
                  BUFFER)))

(DEFINE-METHOD "IS_A" ((OBJ OMG.ORG/CORBA:INTERFACEDEF-PROXY) _INTERFACE_ID)
  (STATIC-CALL ("is_a" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _INTERFACE_ID OUTPUT))
   :INPUT ((INPUT) (UNMARSHAL-BOOL INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "BASE_INTERFACES" ((OBJ OMG.ORG/CORBA:INTERFACEDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_base_interfaces"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:INTERFACEDEFSEQ)))

(DEFINE-METHOD (SETF "BASE_INTERFACES") (NEWVAL
                                         (OBJ
                                          OMG.ORG/CORBA:INTERFACEDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_base_interfaces"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:INTERFACEDEFSEQ)
    NEWVAL))

(DEFINE-INTERFACE OMG.ORG/CORBA:OPERATIONDEF (OMG.ORG/CORBA:CONTAINED)
 :PROXY (OMG.ORG/CORBA:OPERATIONDEF-PROXY OMG.ORG/CORBA:OPERATIONDEF
         OMG.ORG/CORBA:CONTAINED-PROXY)
 :ID "IDL:omg.org/CORBA/OperationDef:1.0"
 :NAME "OperationDef")

(DEFINE-METHOD "EXCEPTIONS" ((OBJ OMG.ORG/CORBA:OPERATIONDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_exceptions"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:EXCEPTIONDEFSEQ)))

(DEFINE-METHOD (SETF "EXCEPTIONS") (NEWVAL
                                    (OBJ OMG.ORG/CORBA:OPERATIONDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_exceptions"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:EXCEPTIONDEFSEQ)
    NEWVAL))

(DEFINE-METHOD "CONTEXTS" ((OBJ OMG.ORG/CORBA:OPERATIONDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_contexts"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTEXTIDSEQ)))

(DEFINE-METHOD (SETF "CONTEXTS") (NEWVAL
                                  (OBJ OMG.ORG/CORBA:OPERATIONDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_contexts"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTEXTIDSEQ)
    NEWVAL))

(DEFINE-METHOD "MODE" ((OBJ OMG.ORG/CORBA:OPERATIONDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_mode"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:OPERATIONMODE)))

(DEFINE-METHOD (SETF "MODE") (NEWVAL (OBJ OMG.ORG/CORBA:OPERATIONDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_mode"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:OPERATIONMODE)
    NEWVAL))

(DEFINE-METHOD "PARAMS" ((OBJ OMG.ORG/CORBA:OPERATIONDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_params"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:PARDESCRIPTIONSEQ)))

(DEFINE-METHOD (SETF "PARAMS") (NEWVAL (OBJ OMG.ORG/CORBA:OPERATIONDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_params"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:PARDESCRIPTIONSEQ)
    NEWVAL))

(DEFINE-METHOD "RESULT_DEF" ((OBJ OMG.ORG/CORBA:OPERATIONDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_result_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)))

(DEFINE-METHOD (SETF "RESULT_DEF") (NEWVAL
                                    (OBJ OMG.ORG/CORBA:OPERATIONDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_result_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
    NEWVAL))

(DEFINE-METHOD "RESULT" ((OBJ OMG.ORG/CORBA:OPERATIONDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_result" OMG.ORG/CORBA:TC_TYPECODE))

(DEFINE-INTERFACE OMG.ORG/CORBA:ATTRIBUTEDEF (OMG.ORG/CORBA:CONTAINED)
 :PROXY (OMG.ORG/CORBA:ATTRIBUTEDEF-PROXY OMG.ORG/CORBA:ATTRIBUTEDEF
         OMG.ORG/CORBA:CONTAINED-PROXY)
 :ID "IDL:omg.org/CORBA/AttributeDef:1.0"
 :NAME "AttributeDef")

(DEFINE-METHOD "MODE" ((OBJ OMG.ORG/CORBA:ATTRIBUTEDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_mode"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ATTRIBUTEMODE)))

(DEFINE-METHOD (SETF "MODE") (NEWVAL (OBJ OMG.ORG/CORBA:ATTRIBUTEDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_mode"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ATTRIBUTEMODE)
    NEWVAL))

(DEFINE-METHOD "TYPE_DEF" ((OBJ OMG.ORG/CORBA:ATTRIBUTEDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_type_def" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)))

(DEFINE-METHOD (SETF "TYPE_DEF") (NEWVAL
                                  (OBJ OMG.ORG/CORBA:ATTRIBUTEDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_type_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
    NEWVAL))

(DEFINE-METHOD "TYPE" ((OBJ OMG.ORG/CORBA:ATTRIBUTEDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_type" OMG.ORG/CORBA:TC_TYPECODE))

(DEFINE-INTERFACE OMG.ORG/CORBA:EXCEPTIONDEF (OMG.ORG/CORBA:CONTAINED)
 :PROXY (OMG.ORG/CORBA:EXCEPTIONDEF-PROXY OMG.ORG/CORBA:EXCEPTIONDEF
         OMG.ORG/CORBA:CONTAINED-PROXY)
 :ID "IDL:omg.org/CORBA/ExceptionDef:1.0"
 :NAME "ExceptionDef")

(DEFINE-METHOD "MEMBERS" ((OBJ OMG.ORG/CORBA:EXCEPTIONDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_members"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:STRUCTMEMBERSEQ)))

(DEFINE-METHOD (SETF "MEMBERS") (NEWVAL (OBJ OMG.ORG/CORBA:EXCEPTIONDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_members"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:STRUCTMEMBERSEQ)
    NEWVAL))

(DEFINE-METHOD "TYPE" ((OBJ OMG.ORG/CORBA:EXCEPTIONDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_type" OMG.ORG/CORBA:TC_TYPECODE))

(DEFINE-INTERFACE OMG.ORG/CORBA:ARRAYDEF (OMG.ORG/CORBA:IDLTYPE)
 :PROXY (OMG.ORG/CORBA:ARRAYDEF-PROXY OMG.ORG/CORBA:ARRAYDEF
         OMG.ORG/CORBA:IDLTYPE-PROXY)
 :ID "IDL:omg.org/CORBA/ArrayDef:1.0"
 :NAME "ArrayDef")

(DEFINE-METHOD "ELEMENT_TYPE_DEF" ((OBJ OMG.ORG/CORBA:ARRAYDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_element_type_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)))

(DEFINE-METHOD (SETF "ELEMENT_TYPE_DEF") (NEWVAL
                                          (OBJ OMG.ORG/CORBA:ARRAYDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_element_type_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
    NEWVAL))

(DEFINE-METHOD "ELEMENT_TYPE" ((OBJ OMG.ORG/CORBA:ARRAYDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_element_type" OMG.ORG/CORBA:TC_TYPECODE))

(DEFINE-METHOD "LENGTH" ((OBJ OMG.ORG/CORBA:ARRAYDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_length" OMG.ORG/CORBA:TC_ULONG))

(DEFINE-METHOD (SETF "LENGTH") (NEWVAL (OBJ OMG.ORG/CORBA:ARRAYDEF-PROXY))
  (SET-ATTRIBUTE OBJ "_set_length" OMG.ORG/CORBA:TC_ULONG NEWVAL))

(DEFINE-INTERFACE OMG.ORG/CORBA:SEQUENCEDEF (OMG.ORG/CORBA:IDLTYPE)
 :PROXY (OMG.ORG/CORBA:SEQUENCEDEF-PROXY OMG.ORG/CORBA:SEQUENCEDEF
         OMG.ORG/CORBA:IDLTYPE-PROXY)
 :ID "IDL:omg.org/CORBA/SequenceDef:1.0"
 :NAME "SequenceDef")

(DEFINE-METHOD "ELEMENT_TYPE_DEF" ((OBJ OMG.ORG/CORBA:SEQUENCEDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_element_type_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)))

(DEFINE-METHOD (SETF "ELEMENT_TYPE_DEF") (NEWVAL
                                          (OBJ
                                           OMG.ORG/CORBA:SEQUENCEDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_element_type_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
    NEWVAL))

(DEFINE-METHOD "ELEMENT_TYPE" ((OBJ OMG.ORG/CORBA:SEQUENCEDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_element_type" OMG.ORG/CORBA:TC_TYPECODE))

(DEFINE-METHOD "BOUND" ((OBJ OMG.ORG/CORBA:SEQUENCEDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_bound" OMG.ORG/CORBA:TC_ULONG))

(DEFINE-METHOD (SETF "BOUND") (NEWVAL (OBJ OMG.ORG/CORBA:SEQUENCEDEF-PROXY))
  (SET-ATTRIBUTE OBJ "_set_bound" OMG.ORG/CORBA:TC_ULONG NEWVAL))

(DEFINE-INTERFACE OMG.ORG/CORBA:FIXEDDEF (OMG.ORG/CORBA:IDLTYPE)
 :PROXY (OMG.ORG/CORBA:FIXEDDEF-PROXY OMG.ORG/CORBA:FIXEDDEF
         OMG.ORG/CORBA:IDLTYPE-PROXY)
 :ID "IDL:omg.org/CORBA/FixedDef:1.0"
 :NAME "FixedDef")

(DEFINE-METHOD "SCALE" ((OBJ OMG.ORG/CORBA:FIXEDDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_scale" OMG.ORG/CORBA:TC_SHORT))

(DEFINE-METHOD (SETF "SCALE") (NEWVAL (OBJ OMG.ORG/CORBA:FIXEDDEF-PROXY))
  (SET-ATTRIBUTE OBJ "_set_scale" OMG.ORG/CORBA:TC_SHORT NEWVAL))

(DEFINE-METHOD "DIGITS" ((OBJ OMG.ORG/CORBA:FIXEDDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_digits" OMG.ORG/CORBA:TC_USHORT))

(DEFINE-METHOD (SETF "DIGITS") (NEWVAL (OBJ OMG.ORG/CORBA:FIXEDDEF-PROXY))
  (SET-ATTRIBUTE OBJ "_set_digits" OMG.ORG/CORBA:TC_USHORT NEWVAL))

(DEFINE-INTERFACE OMG.ORG/CORBA:WSTRINGDEF (OMG.ORG/CORBA:IDLTYPE)
 :PROXY (OMG.ORG/CORBA:WSTRINGDEF-PROXY OMG.ORG/CORBA:WSTRINGDEF
         OMG.ORG/CORBA:IDLTYPE-PROXY)
 :ID "IDL:omg.org/CORBA/WstringDef:1.0"
 :NAME "WstringDef")

(DEFINE-METHOD "BOUND" ((OBJ OMG.ORG/CORBA:WSTRINGDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_bound" OMG.ORG/CORBA:TC_ULONG))

(DEFINE-METHOD (SETF "BOUND") (NEWVAL (OBJ OMG.ORG/CORBA:WSTRINGDEF-PROXY))
  (SET-ATTRIBUTE OBJ "_set_bound" OMG.ORG/CORBA:TC_ULONG NEWVAL))

(DEFINE-INTERFACE OMG.ORG/CORBA:STRINGDEF (OMG.ORG/CORBA:IDLTYPE)
 :PROXY (OMG.ORG/CORBA:STRINGDEF-PROXY OMG.ORG/CORBA:STRINGDEF
         OMG.ORG/CORBA:IDLTYPE-PROXY)
 :ID "IDL:omg.org/CORBA/StringDef:1.0"
 :NAME "StringDef")

(DEFINE-METHOD "BOUND" ((OBJ OMG.ORG/CORBA:STRINGDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_bound" OMG.ORG/CORBA:TC_ULONG))

(DEFINE-METHOD (SETF "BOUND") (NEWVAL (OBJ OMG.ORG/CORBA:STRINGDEF-PROXY))
  (SET-ATTRIBUTE OBJ "_set_bound" OMG.ORG/CORBA:TC_ULONG NEWVAL))

(DEFINE-INTERFACE OMG.ORG/CORBA:PRIMITIVEDEF (OMG.ORG/CORBA:IDLTYPE)
 :PROXY (OMG.ORG/CORBA:PRIMITIVEDEF-PROXY OMG.ORG/CORBA:PRIMITIVEDEF
         OMG.ORG/CORBA:IDLTYPE-PROXY)
 :ID "IDL:omg.org/CORBA/PrimitiveDef:1.0"
 :NAME "PrimitiveDef")

(DEFINE-METHOD "KIND" ((OBJ OMG.ORG/CORBA:PRIMITIVEDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_kind"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:PRIMITIVEKIND)))

(DEFINE-INTERFACE OMG.ORG/CORBA:TYPEDEFDEF (OMG.ORG/CORBA:CONTAINED
                                            OMG.ORG/CORBA:IDLTYPE)
 :PROXY (OMG.ORG/CORBA:TYPEDEFDEF-PROXY OMG.ORG/CORBA:TYPEDEFDEF
         OMG.ORG/CORBA:CONTAINED-PROXY OMG.ORG/CORBA:IDLTYPE-PROXY)
 :ID "IDL:omg.org/CORBA/TypedefDef:1.0"
 :NAME "TypedefDef")

(DEFINE-INTERFACE OMG.ORG/CORBA:CONSTANTDEF (OMG.ORG/CORBA:CONTAINED)
 :PROXY (OMG.ORG/CORBA:CONSTANTDEF-PROXY OMG.ORG/CORBA:CONSTANTDEF
         OMG.ORG/CORBA:CONTAINED-PROXY)
 :ID "IDL:omg.org/CORBA/ConstantDef:1.0"
 :NAME "ConstantDef")

(DEFINE-METHOD "VALUE" ((OBJ OMG.ORG/CORBA:CONSTANTDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_value" OMG.ORG/CORBA:TC_ANY))

(DEFINE-METHOD (SETF "VALUE") (NEWVAL (OBJ OMG.ORG/CORBA:CONSTANTDEF-PROXY))
  (SET-ATTRIBUTE OBJ "_set_value" OMG.ORG/CORBA:TC_ANY NEWVAL))

(DEFINE-METHOD "TYPE_DEF" ((OBJ OMG.ORG/CORBA:CONSTANTDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_type_def" (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)))

(DEFINE-METHOD (SETF "TYPE_DEF") (NEWVAL (OBJ OMG.ORG/CORBA:CONSTANTDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_type_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
    NEWVAL))

(DEFINE-METHOD "TYPE" ((OBJ OMG.ORG/CORBA:CONSTANTDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_type" OMG.ORG/CORBA:TC_TYPECODE))

(DEFINE-INTERFACE OMG.ORG/CORBA:MODULEDEF (OMG.ORG/CORBA:CONTAINER
                                           OMG.ORG/CORBA:CONTAINED)
 :PROXY (OMG.ORG/CORBA:MODULEDEF-PROXY OMG.ORG/CORBA:MODULEDEF
         OMG.ORG/CORBA:CONTAINER-PROXY OMG.ORG/CORBA:CONTAINED-PROXY)
 :ID "IDL:omg.org/CORBA/ModuleDef:1.0"
 :NAME "ModuleDef")

(DEFINE-INTERFACE OMG.ORG/CORBA:REPOSITORY (OMG.ORG/CORBA:CONTAINER)
 :PROXY (OMG.ORG/CORBA:REPOSITORY-PROXY OMG.ORG/CORBA:REPOSITORY
         OMG.ORG/CORBA:CONTAINER-PROXY)
 :ID "IDL:omg.org/CORBA/Repository:1.0"
 :NAME "Repository")

(DEFINE-METHOD "CREATE_FIXED" ((OBJ OMG.ORG/CORBA:REPOSITORY-PROXY) _DIGITS
                               _SCALE)
  (STATIC-CALL ("create_fixed" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-USHORT _DIGITS OUTPUT)
            (MARSHAL-SHORT _SCALE OUTPUT))
   :INPUT ((INPUT) (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:FIXEDDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_ARRAY" ((OBJ OMG.ORG/CORBA:REPOSITORY-PROXY) _LENGTH
                               _ELEMENT_TYPE)
  (STATIC-CALL ("create_array" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-ULONG _LENGTH OUTPUT)
            (MARSHAL _ELEMENT_TYPE
                     (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
                     OUTPUT))
   :INPUT ((INPUT) (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ARRAYDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_SEQUENCE" ((OBJ OMG.ORG/CORBA:REPOSITORY-PROXY) _BOUND
                                  _ELEMENT_TYPE)
  (STATIC-CALL ("create_sequence" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-ULONG _BOUND OUTPUT)
            (MARSHAL _ELEMENT_TYPE
                     (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
                     OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:SEQUENCEDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_WSTRING" ((OBJ OMG.ORG/CORBA:REPOSITORY-PROXY) _BOUND)
  (STATIC-CALL ("create_wstring" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-ULONG _BOUND OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:WSTRINGDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "CREATE_STRING" ((OBJ OMG.ORG/CORBA:REPOSITORY-PROXY) _BOUND)
  (STATIC-CALL ("create_string" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-ULONG _BOUND OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:STRINGDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "GET_PRIMITIVE" ((OBJ OMG.ORG/CORBA:REPOSITORY-PROXY) _KIND)
  (STATIC-CALL ("get_primitive" OBJ)
   :OUTPUT ((OUTPUT)
            (MARSHAL _KIND
                     (SYMBOL-TYPECODE 'OMG.ORG/CORBA:PRIMITIVEKIND)
                     OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:PRIMITIVEDEF) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "LOOKUP_ID" ((OBJ OMG.ORG/CORBA:REPOSITORY-PROXY) _SEARCH_ID)
  (STATIC-CALL ("lookup_id" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _SEARCH_ID OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'OMG.ORG/CORBA:CONTAINED) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-INTERFACE OMG.ORG/CORBA:ALIASDEF (OMG.ORG/CORBA:TYPEDEFDEF)
 :PROXY (OMG.ORG/CORBA:ALIASDEF-PROXY OMG.ORG/CORBA:ALIASDEF
         OMG.ORG/CORBA:TYPEDEFDEF-PROXY)
 :ID "IDL:omg.org/CORBA/AliasDef:1.0"
 :NAME "AliasDef")

(DEFINE-METHOD "ORIGINAL_TYPE_DEF" ((OBJ OMG.ORG/CORBA:ALIASDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_original_type_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)))

(DEFINE-METHOD (SETF "ORIGINAL_TYPE_DEF") (NEWVAL
                                           (OBJ OMG.ORG/CORBA:ALIASDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_original_type_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
    NEWVAL))

(DEFINE-INTERFACE OMG.ORG/CORBA:ENUMDEF (OMG.ORG/CORBA:TYPEDEFDEF)
 :PROXY (OMG.ORG/CORBA:ENUMDEF-PROXY OMG.ORG/CORBA:ENUMDEF
         OMG.ORG/CORBA:TYPEDEFDEF-PROXY)
 :ID "IDL:omg.org/CORBA/EnumDef:1.0"
 :NAME "EnumDef")

(DEFINE-METHOD "MEMBERS" ((OBJ OMG.ORG/CORBA:ENUMDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_members"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ENUMMEMBERSEQ)))

(DEFINE-METHOD (SETF "MEMBERS") (NEWVAL (OBJ OMG.ORG/CORBA:ENUMDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_members"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:ENUMMEMBERSEQ)
    NEWVAL))

(DEFINE-INTERFACE OMG.ORG/CORBA:UNIONDEF (OMG.ORG/CORBA:TYPEDEFDEF)
 :PROXY (OMG.ORG/CORBA:UNIONDEF-PROXY OMG.ORG/CORBA:UNIONDEF
         OMG.ORG/CORBA:TYPEDEFDEF-PROXY)
 :ID "IDL:omg.org/CORBA/UnionDef:1.0"
 :NAME "UnionDef")

(DEFINE-METHOD "MEMBERS" ((OBJ OMG.ORG/CORBA:UNIONDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_members"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:UNIONMEMBERSEQ)))

(DEFINE-METHOD (SETF "MEMBERS") (NEWVAL (OBJ OMG.ORG/CORBA:UNIONDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_members"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:UNIONMEMBERSEQ)
    NEWVAL))

(DEFINE-METHOD "DISCRIMINATOR_TYPE_DEF" ((OBJ OMG.ORG/CORBA:UNIONDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_discriminator_type_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)))

(DEFINE-METHOD (SETF "DISCRIMINATOR_TYPE_DEF") (NEWVAL
                                                (OBJ
                                                 OMG.ORG/CORBA:UNIONDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_discriminator_type_def"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:IDLTYPE)
    NEWVAL))

(DEFINE-METHOD "DISCRIMINATOR_TYPE" ((OBJ OMG.ORG/CORBA:UNIONDEF-PROXY))
  (GET-ATTRIBUTE OBJ "_get_discriminator_type" OMG.ORG/CORBA:TC_TYPECODE))

(DEFINE-INTERFACE OMG.ORG/CORBA:STRUCTDEF (OMG.ORG/CORBA:TYPEDEFDEF)
 :PROXY (OMG.ORG/CORBA:STRUCTDEF-PROXY OMG.ORG/CORBA:STRUCTDEF
         OMG.ORG/CORBA:TYPEDEFDEF-PROXY)
 :ID "IDL:omg.org/CORBA/StructDef:1.0"
 :NAME "StructDef")

(DEFINE-METHOD "MEMBERS" ((OBJ OMG.ORG/CORBA:STRUCTDEF-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_members"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:STRUCTMEMBERSEQ)))

(DEFINE-METHOD (SETF "MEMBERS") (NEWVAL (OBJ OMG.ORG/CORBA:STRUCTDEF-PROXY))
  (SET-ATTRIBUTE
    OBJ
    "_set_members"
    (SYMBOL-TYPECODE 'OMG.ORG/CORBA:STRUCTMEMBERSEQ)
    NEWVAL))
