(in-package :cl-user)

(defpackage "OMG.ORG/CORBA"
  (:use)
  (:nicknames "CORBA")
  (:export
   ServerRequest "SECCONSTRUCTION" "TYPECODEFACTORY" "TC_OBJECT"
   "ALIASDEF" "ALIASDEF-PROXY" "ANY" "ANY-TYPECODE" "ANY-VALUE" "ARG_IN"
   "ARG_INOUT" "ARG_OUT" "ARRAYDEF" "ARRAYDEF-PROXY" "ATTRDESCRIPTIONSEQ"
   "ATTRIBUTEDEF" "ATTRIBUTEDEF-PROXY" "ATTRIBUTEDESCRIPTION" "ATTRIBUTEMODE"
   "BAD_CONTEXT" "BAD_INV_ORDER" "BAD_OPERATION" "BAD_PARAM" "BAD_POLICY"
   "BAD_POLICY_TYPE" "BAD_POLICY_VALUE" "BAD_TYPECODE" "BOOLEAN" "CHAR"
   "COMM_FAILURE" "COMPLETION_STATUS" "CONSTANTDEF" "CONSTANTDEF-PROXY"
   "CONSTANTDESCRIPTION" "CONTAINED" "CONTAINED-PROXY" "CONTAINED/DESCRIPTION"
   "CONTAINEDSEQ" "CONTAINER" "CONTAINER-PROXY" "CONTAINER/DESCRIPTION"
   "CONTAINER/DESCRIPTIONSEQ" "CONTEXTIDENTIFIER" "CONTEXTIDSEQ"
   "CTX_RESTRICT_SCOPE" "CURRENT" "DATA_CONVERSION" "DEFINE-METHOD"
   "DEFINITIONKIND" "DOUBLE" "ENUMDEF" "ENUMDEF-PROXY" "ENUMMEMBERSEQ"
   "ENVIRONMENT" "EXCDESCRIPTIONSEQ" "EXCEPTION" "EXCEPTIONDEF"
   "EXCEPTIONDEF-PROXY" "EXCEPTIONDEFSEQ" "EXCEPTIONDESCRIPTION" "FIXED"
   "FIXEDDEF" "FIXEDDEF-PROXY" "FLAGS" "FLOAT" "FREE_MEM" "FUNCALL"
   "IDENTIFIER" "IDL" "IDLTYPE" "IDLTYPE-PROXY" "IDLTYPESEQ" "IMP_LIMIT"
   "INITIALIZE" "INTERFACEDEF" "INTERFACEDEF-PROXY"
   "INTERFACEDEF/FULLINTERFACEDESCRIPTION" "INTERFACEDEFSEQ"
   "INTERFACEDESCRIPTION" "INTERNAL" "INTF_REPOS" "INVALID_TRANSACTION"
   "INV_FLAG" "INV_IDENT" "INV_OBJREF" "IROBJECT" "IROBJECT-PROXY" "LONG"
   "LONGDOUBLE" "LONGLONG" "MARSHAL" "MODULEDEF" "MODULEDEF-PROXY"
   "MODULEDESCRIPTION" "NAMEDVALUE" "NO_IMPLEMENT" "NO_MEMORY" "NO_PERMISSION"
   "NO_RESOURCES" "NO_RESPONSE" "OBJECT" "OBJECT_NOT_EXIST" "OBJ_ADAPTER"
   "OCTET" "OPDESCRIPTIONSEQ" "OPERATIONDEF" "OPERATIONDEF-PROXY"
   "OPERATIONDESCRIPTION" "OPERATIONMODE" "ORB" "ORB/INVALIDNAME" "ORB_INIT"
   "PARAMETERDESCRIPTION" "PARAMETERMODE" "PARDESCRIPTIONSEQ" "PERSIST_STORE"
   "POLICY" "POLICY-PROXY" "POLICYERROR" "POLICYERRORCODE" "POLICYLIST"
   "POLICYTYPE" "PRIMITIVEDEF" "PRIMITIVEDEF-PROXY" "PRIMITIVEKIND" "PROXY"
   "REPOSITORY" "REPOSITORY-PROXY" "REPOSITORYID" "REPOSITORYIDSEQ" "REQUEST"
   "SCOPEDNAME" "SECURITY" "SEQUENCEDEF" "SEQUENCEDEF-PROXY" "SERVICEDETAIL"
   "SERVICEDETAILTYPE" "SERVICEINFORMATION" "SERVICEOPTION" "SERVICETYPE"
   "SHORT" "STRING" "STRINGDEF" "STRINGDEF-PROXY" "STRUCT" "STRUCTDEF"
   "STRUCTDEF-PROXY" "STRUCTMEMBER" "STRUCTMEMBERSEQ" "SYSTEMEXCEPTION"
   "TCKIND" "TC_ALIAS" "TC_ANY" "TC_ARRAY" "TC_BOOLEAN" "TC_CHAR" "TC_DOUBLE"
   "TC_ENUM" "TC_EXCEPT" "TC_FIXED" "TC_FLOAT" "TC_LONG" "TC_LONGDOUBLE"
   "TC_LONGLONG" "TC_NULL"  "TC_OCTET" "TC_PRINCIPAL" "TC_SEQUENCE"
   "TC_SHORT" "TC_STRING" "TC_STRUCT" "TC_TYPECODE" "TC_ULONG" "TC_ULONGLONG"
   "TC_UNION" "TC_USHORT" "TC_VOID" "TC_WCHAR" "TC_WSTRING"
   "TRANSACTION_REQUIRED" "TRANSACTION_ROLLEDBACK" "TRANSIENT" "TYPECODE"
   "TYPECODE/BADKIND" "TYPECODE/BOUNDS" "TYPEDEFDEF" "TYPEDEFDEF-PROXY"
   "TYPEDESCRIPTION" "ULONG" "ULONGLONG" "UNION" "UNIONDEF" "UNIONDEF-PROXY"
   "UNIONMEMBER" "UNIONMEMBERSEQ" "UNKNOWN" "UNSUPPORTED_POLICY"
   "UNSUPPORTED_POLICY_VALUE" "USEREXCEPTION" "USHORT" "VERSIONSPEC" "WCHAR"
   "WSTRING" "WSTRINGDEF" "WSTRINGDEF-PROXY"))


(defpackage "IOP"
  (:use)
  (:export
   "BI_DIR_IIOP" "CHAINBYPASSCHECK" "CHAINBYPASSINFO" "CODESETS" "COMPONENTID"
   "FORWARDED_IDENTITY" "INVOCATION_POLICIES" "IOR" "LOGICALTHREADID"
   "MULTIPLECOMPONENTPROFILE" "PROFILEID" "SENDINGCONTEXTRUNTIME"
   "SERVICECONTEXT" "SERVICECONTEXTLIST" "SERVICEID" "TAGGEDCOMPONENT"
   "TAGGEDPROFILE" "TAG_ALTERNATE_IIOP_ADDRESS" "TAG_ASSOCIATION_OPTIONS"
   "TAG_CODE_SETS" "TAG_COMPLETE_OBJECT_KEY" "TAG_CSI_ECMA_HYBRID_SEC_MECH"
   "TAG_CSI_ECMA_PUBLIC_SEC_MECH" "TAG_CSI_ECMA_SECRET_SEC_MECH"
   "TAG_DCE_BINDING_NAME" "TAG_DCE_NO_PIPES" "TAG_DCE_SEC_MECH"
   "TAG_DCE_STRING_BINDING" "TAG_ENDPOINT_ID_POSITION" "TAG_GENERIC_SEC_MECH"
   "TAG_INTERNET_IOP" "TAG_JAVA_CODEBASE" "TAG_KERBEROSV5_SEC_MECH"
   "TAG_LOCATION_POLICY" "TAG_MULTIPLE_COMPONENTS" "TAG_ORB_TYPE"
   "TAG_POLICIES" "TAG_SEC_NAME" "TAG_SPKM_1_SEC_MECH" "TAG_SPKM_2_SEC_MECH"
   "TAG_SSL_SEC_TRANS" "TRANSACTIONSERVICE" "UNKNOWNEXCEPTIONINFO"))

(defpackage "GIOP"
  (:use)
  (:export
   "CANCELREQUESTHEADER" "LOCATEREPLYHEADER" "LOCATEREQUESTHEADER"
   "LOCATESTATUSTYPE" "MESSAGEHEADER_1_0" "MESSAGEHEADER_1_1" "MSGTYPE_1_0"
   "PRINCIPAL" "REPLYHEADER" "REPLYSTATUSTYPE" "REQUESTHEADER_1_0"
   "REQUESTHEADER_1_1" "VERSION"))

(defpackage "OMG.ORG/FEATURES"
  (:use)
  (:nicknames "OP")
  (:export
   "ABSOLUTE_NAME" "ACTIVATE" "ACTIVATE_OBJECT" "ACTIVATE_OBJECT_WITH_ID"
   "ADD_CONTAINED" "ADD_INOUT_ARG" "ADD_IN_ARG" "ADD_NAMED_INOUT_ARG"
   "ADD_NAMED_IN_ARG" "ADD_NAMED_OUT_ARG" "ADD_OUT_ARG" "ARGUMENT" "ARGUMENTS"
   "ARG_MODES" "ATTRIBUTES" "BASE_INTERFACES" "BIND" "BINDING_NAME"
   "BINDING_TYPE" "BIND_CONTEXT" "BIND_NEW_CONTEXT" "BOUND" "CLEAR"
   "COMPONENT_DATA" "CONNECT_PULL_CONSUMER" "CONNECT_PULL_SUPPLIER"
   "CONNECT_PUSH_CONSUMER" "CONNECT_PUSH_SUPPLIER" "CONTAINED_OBJECT"
   "CONTAINING_REPOSITORY" "CONTENTS" "CONTENT_TYPE" "CONTEXTS" "CONTEXT_DATA"
   "CONTEXT_ID" "COPY" "CREATE_ALIAS" "CREATE_ARRAY" "CREATE_ATTRIBUTE"
   "CREATE_CONSTANT" "CREATE_ENUM" "CREATE_EXCEPTION" "CREATE_FIXED"
   "CREATE_INTERFACE" "CREATE_MODULE" "CREATE_OPERATION" "CREATE_POA"
   "CREATE_REFERENCE" "CREATE_REFERENCE_WITH_ID" "CREATE_REQUEST"
   "CREATE_SEQUENCE" "CREATE_STRING" "CREATE_STRUCT" "CREATE_UNION"
   "CREATE_WSTRING" "CTX" "DEACTIVATE" "DEACTIVATE_OBJECT" "DEFAULT_FILTER"
   "DEFAULT_INDEX" "DEFINED_IN" "DEF_KIND" "DESCRIBE" "DESCRIBE_CONTENTS"
   "DESCRIBE_INTERFACE" "DESTROY" "DIGITS" "DISCARD_REQUESTS"
   "DISCONNECT_PULL_CONSUMER" "DISCONNECT_PULL_SUPPLIER"
   "DISCONNECT_PUSH_CONSUMER" "DISCONNECT_PUSH_SUPPLIER" "DISCRIMINATOR_TYPE"
   "DISCRIMINATOR_TYPE_DEF" "ELEMENT_TYPE" "ELEMENT_TYPE_DEF" "EQUAL"
   "ETHEREALIZE" "EXCEPTIONS" "FIND_POA" "FOO" "FOR_CONSUMERS" "FOR_SUPPLIERS"
   "GET-STATE" "GET_ANONYMOUS_TYPES" "GET_OBJECT_ID" "GET_POA" "GET_PRIMITIVE"
   "GET_RESPONSE" "GET_SERVANT" "GET_SERVANT_MANAGER" "GET_STATE" "GREET"
   "HOLD_REQUESTS" "ID" "ID_TO_REFERENCE" "ID_TO_SERVANT" "INCARNATE" "INVOKE"
   "IS_A" "KIND" "LABEL" "LENGTH" "LIST" "LIST_INITIAL_REFERENCES" "LOCATE_ID"
   "LOCATE_NAME" "LOOKUP" "LOOKUP_ID" "LOOKUP_NAME" "MEMBERS" "MEMBER_COUNT"
   "MEMBER_LABEL" "MEMBER_NAME" "MEMBER_TYPE" "MODE" "MOVE" "NAME"
   "NEW_CHANNEL" "NEW_CONTEXT" "NEXT_N" "NEXT_ONE" "OBJECT_TO_STRING"
   "OBTAIN_PULL_CONSUMER" "OBTAIN_PULL_SUPPLIER" "OBTAIN_PUSH_CONSUMER"
   "OBTAIN_PUSH_SUPPLIER" "OPERATION" "OPERATIONS" "ORIGINAL_TYPE_DEF"
   "PARAMETERS" "PARAMS" "PERFORM_WORK" "POLICY_TYPE" "POLL_RESPONSE"
   "POSTINVOKE" "PREINVOKE" "PRIMARY_INTERFACE" "PROFILES" "PROFILE_DATA"
   "PULL" "PUSH" "PUT_LONG" "PUT_STRING" "REBIND" "REBIND_CONTEXT"
   "REFERENCE_TO_ID" "REFERENCE_TO_SERVANT" "REMOVE_CONTAINED" "RESOLVE"
   "RESOLVE_INITIAL_REFERENCES" "RESULT" "RESULT_DEF" "RETURN_VALUE" "RUN"
   "SCALE" "SEND_DEFERRED" "SEND_ONEWAY" "SERVANT_TO_ID" "SERVANT_TO_REFERENCE"
   "SERVICE_DETAIL" "SERVICE_DETAILS" "SERVICE_DETAIL_TYPE" "SERVICE_OPTIONS"
   "SET_EXCEPTION" "SET_RESULT" "SET_RETURN_TYPE" "SET_SERVANT"
   "SET_SERVANT_MANAGER" "SHUTDOWN" "STRING_TO_OBJECT" "TAG" "TARGET"
   "THE_ACTIVATOR" "THE_NAME" "THE_PARENT" "THE_POAMANAGER" "TRY_PULL" "TYPE"
   "TYPE_DEF" "TYPE_ID" "UNBIND" "VALUE" "VERSION" "WORK_PENDING"
   "_CREATE_REQUEST" "_DEFAULT_POA" "_GET_ABSOLUTE_NAME" "_GET_ARGUMENT"
   "_GET_ARGUMENTS" "_GET_ARG_MODES" "_GET_BASE_INTERFACES" "_GET_BOUND"
   "_GET_CONTAINING_REPOSITORY" "_GET_CONTEXTS" "_GET_CTX" "_GET_DEFINED_IN"
   "_GET_DEF_KIND" "_GET_DISCRIMINATOR_TYPE_DEF" "_GET_ELEMENT_TYPE_DEF"
   "_GET_EXCEPTIONS" "_GET_ID" "_GET_INTERFACE" "_GET_KIND" "_GET_MEMBERS"
   "_GET_MODE" "_GET_NAME" "_GET_OPERATION" "_GET_ORIGINAL_TYPE_DEF"
   "_GET_PARAMS" "_GET_RESULT" "_GET_RESULT_DEF" "_GET_TARGET"
   "_GET_THE_ACTIVATOR" "_GET_THE_NAME" "_GET_THE_PARENT" "_GET_THE_POAMANAGER"
   "_GET_TYPE" "_GET_TYPE_DEF" "_GET_VALUE" "_GET_VERSION" "_HASH" "_INTERFACE"
   "_IS_A" "_IS_EQUIVALENT" "_IS_NIL" "_NON_EXISTENT" "_SET_ARGUMENT"
   "_SET_ARG_MODES" "_SET_BASE_INTERFACES" "_SET_BOUND" "_SET_CONTEXTS"
   "_SET_CTX" "_SET_DISCRIMINATOR_TYPE_DEF" "_SET_ELEMENT_TYPE_DEF"
   "_SET_EXCEPTIONS" "_SET_KIND" "_SET_MEMBERS" "_SET_MODE" "_SET_NAME"
   "_SET_ORIGINAL_TYPE_DEF" "_SET_PARAMS" "_SET_RESULT_DEF"
   "_SET_THE_ACTIVATOR" "_SET_TYPE_DEF" "_SET_VALUE" "_SET_VERSION" "_THIS"))


(defpackage "OMG.ORG/ROOT"
  (:use))

(defpackage "OMG.ORG/PORTABLESERVER"
  (:use)
  (:nicknames "PORTABLESERVER")
  (:export
   "ADAPTERACTIVATOR"  "CURRENT"
   "CURRENT/NOCONTEXT" "DYNAMICIMPLEMENTATION" "FORWARDREQUEST"
   "IDASSIGNMENTPOLICY" "IDASSIGNMENTPOLICY-PROXY" "IDASSIGNMENTPOLICY-SERVANT"
   "IDASSIGNMENTPOLICYVALUE" "IDUNIQUENESSPOLICY" "IDUNIQUENESSPOLICY-PROXY"
   "IDUNIQUENESSPOLICY-SERVANT" "IDUNIQUENESSPOLICYVALUE" "ID_ASSIGNMENT_POLICY_ID"
   "ID_UNIQUENESS_POLICY_ID" "IMPLICITACTIVATIONPOLICY" "IMPLICITACTIVATIONPOLICY-PROXY"
   "IMPLICITACTIVATIONPOLICY-SERVANT" "IMPLICITACTIVATIONPOLICYVALUE"
   "IMPLICIT_ACTIVATION_POLICY_ID" "LIFESPANPOLICY" "LIFESPANPOLICY-PROXY"
   "LIFESPANPOLICY-SERVANT" "LIFESPANPOLICYVALUE" "LIFESPAN_POLICY_ID" "OBJECTID" "OID-TO-STRING"
   "POA"  "POA/ADAPTERALREADYEXISTS" "POA/ADAPTERINACTIVE"
   "POA/ADAPTERNONEXISTENT" "POA/INVALIDPOLICY" "POA/NOSERVANT" "POA/OBJECTALREADYACTIVE"
   "POA/OBJECTNOTACTIVE" "POA/SERVANTALREADYACTIVE" "POA/SERVANTNOTACTIVE" "POA/WRONGADAPTER"
   "POA/WRONGPOLICY" "POALIST" "POAMANAGER" "POAMANAGER-PROXY" "POAMANAGER-SERVANT"
   "POAMANAGER/ADAPTERINACTIVE" "POAMANAGER/STATE" "REQUESTPROCESSINGPOLICY"
   "REQUESTPROCESSINGPOLICY-PROXY" "REQUESTPROCESSINGPOLICY-SERVANT" "REQUESTPROCESSINGPOLICYVALUE"
   "REQUEST_PROCESSING_POLICY_ID" "SERVANT" "SERVANTACTIVATOR" "SERVANTLOCATOR"
   "SERVANTLOCATOR/COOKIE" "SERVANTMANAGER"  "SERVANTRETENTIONPOLICY" "SERVANTRETENTIONPOLICY-PROXY"
   "SERVANTRETENTIONPOLICY-SERVANT" "SERVANTRETENTIONPOLICYVALUE" "SERVANT_RETENTION_POLICY_ID"
   "STRING-TO-OID" "THREADPOLICY" "THREADPOLICY-PROXY" "THREADPOLICY-SERVANT" "THREADPOLICYVALUE"
   "THREAD_POLICY_ID"))

(defpackage "IOP_N"
  (:use)
  (:export
   "ENCODING" "ENCODINGFORMAT" "ENCODING_CDR_ENCAPS" "TAGGEDCOMPONENTSEQ"))

(defpackage "PORTABLEINTERCEPTOR"
  (:use)
  (:export register_orb_initializer
   "CLIENTREQUESTINFO" "CLIENTREQUESTINTERCEPTOR"
   "CONTEXTLIST" "CURRENT" "EXCEPTIONLIST" "FORWARDREQUEST"
   "INTERCEPTOR" "INVALIDSLOT" "IORINFO" "IORINTERCEPTOR" 
   "LOCATION_FORWARD" "ORBINITIALIZER"
   "ORBINITINFO" "ORBINITINFO/DUPLICATENAME"
   "ORBINITINFO/INVALIDNAME" "ORBINITINFO/OBJECTID" "PARAMETER" "PARAMETERLIST" 
   "POLICYFACTORY" "REPLYSTATUS" "REQUESTCONTEXT" "REQUESTINFO"
   "SERVERREQUESTINFO" "SERVERREQUESTINTERCEPTOR"
   "SLOTID" "SUCCESSFUL" "SYSTEM_EXCEPTION" "TRANSPORT_RETRY"
   "USER_EXCEPTION"))


;;;; Implementation Packages

(defpackage "NET.CDDR.CLORB.INTERNALS"
  (:use "COMMON-LISP")
  (:export idl-compiler load-repository *default-idl-compiler*
           *default-include-directories*
           ;; idlcpp
           using-cpp-stream read-cpp-line
           idl-prefix idl-source-position idl-repositoryid-pragmas
           ;; idef
           idef-read 
           ;; sysdep
           shell-to-string-or-stream external-namestring))

(defpackage "NET.CDDR.CLORB"
  (:nicknames "CLORB")
  (:use "COMMON-LISP" "NET.CDDR.CLORB.INTERNALS"
        #+:use-my-idlparser "NET.CDDR.REDPAS"
        #+clorb-dev "NET.CDDR.CLORB.SYSTEM"
        #+clorb-dev "NET.CDDR.LUNA"
        #+cmu "MOP" #-(or sbcl cmu mcl) "CLOS")
  #+cmu
  (:shadowing-import-from "MOP"
              "CLASS-NAME" "BUILT-IN-CLASS" "CLASS-OF" "FIND-CLASS")
  (:export "STRUCT-GET"
           ;; Utilities
           "INVOKE" "RESOLVE" "REBIND" "PATHNAME-URL"
           ;; Development tools
           #+clorb-dev "RELOAD"
           ;; Useful internals
           "LOAD-IR" "*RUNNING-ORB*" "ROOT-POA"
           "*HOST*" "*PORT*" )
  (:import-from "OMG.ORG/PORTABLESERVER"
                "POA" "STRING-TO-OID" "OID-TO-STRING")
  #+clisp
  (:import-from USER
                SOCKET-ACCEPT SOCKET-CONNECT SOCKET-SERVER SOCKET-SERVER-CLOSE
                SOCKET-SERVER-HOST SOCKET-SERVER-PORT SOCKET-SERVICE-PORT
                SOCKET-STREAM-HANDLE SOCKET-STREAM-HOST SOCKET-STREAM-LOCAL
                SOCKET-STREAM-PEER SOCKET-STREAM-PORT SOCKET-WAIT)
  (:import-from "OMG.ORG/CORBA"
                "ORB_INIT" "ORB" "REQUEST" "OBJECT"
                "DEFINE-METHOD" "STRUCT"
                ;; Exceptions
                "EXCEPTION" "SYSTEMEXCEPTION" "USEREXCEPTION"
                ;; NamedValue
                "ARG_IN" "ARG_OUT" "ARG_INOUT" "CTX_RESTRICT_SCOPE"
                "ANY" "ANY-VALUE" "ANY-TYPECODE"))

(defpackage "NET.CDDR.CLORB.PERSISTENT-NAMING"
  (:nicknames "PERSISTENT-NAMING")
  (:use "COMMON-LISP")
  (:import-from "CORBA" "DEFINE-METHOD")
  (:export "*NAMING-IOR-FILE*" "*NAMING-BASE-PATH*" "*NAMING-POA*"
           "SETUP-PNS" "SETUP-NAMING-POA"))

(defpackage "NET.CDDR.CLORB.IDLCOMP"
  (:nicknames "CLORB.IDLCOMP")
  (:use "COMMON-LISP" "NET.CDDR.CLORB" "NET.CDDR.CLORB.INTERNALS"))
