
(IN-PACKAGE :CLORB)

(DEFCONSTANT IOP:UNKNOWNEXCEPTIONINFO (QUOTE 9))

(DEFCONSTANT IOP:FORWARDED_IDENTITY (QUOTE 8))

(DEFCONSTANT IOP:INVOCATION_POLICIES (QUOTE 7))

(DEFCONSTANT IOP:SENDINGCONTEXTRUNTIME (QUOTE 6))

(DEFCONSTANT IOP:BI_DIR_IIOP (QUOTE 5))

(DEFCONSTANT IOP:LOGICALTHREADID (QUOTE 4))

(DEFCONSTANT IOP:CHAINBYPASSINFO (QUOTE 3))

(DEFCONSTANT IOP:CHAINBYPASSCHECK (QUOTE 2))

(DEFCONSTANT IOP:CODESETS (QUOTE 1))

(DEFCONSTANT IOP:TRANSACTIONSERVICE (QUOTE 0))

(DEFINE-ALIAS IOP:SERVICECONTEXTLIST
 :ID "IDL:IOP/ServiceContextList:1.0"
 :NAME "ServiceContextList"
 :TYPE SEQUENCE
 :TYPECODE (MAKE-SEQUENCE-TYPECODE (SYMBOL-TYPECODE 'IOP:SERVICECONTEXT) 0))

(DEFINE-STRUCT IOP:SERVICECONTEXT
 :ID "IDL:IOP/ServiceContext:1.0"
 :NAME "ServiceContext"
 :MEMBERS (("context_id" (SYMBOL-TYPECODE 'IOP:SERVICEID) CONTEXT_ID)
           ("context_data" (MAKE-SEQUENCE-TYPECODE OMG.ORG/CORBA:TC_OCTET 0)
            CONTEXT_DATA))
 :READ ((BUFFER)
        (IOP:SERVICECONTEXT
          :CONTEXT_ID
          (UNMARSHAL-ULONG BUFFER)
          :CONTEXT_DATA
          (UNMARSHAL-OSEQUENCE BUFFER)))
 :WRITE ((OBJ BUFFER) (MARSHAL-ULONG (OMG.ORG/FEATURES:CONTEXT_ID OBJ) BUFFER)
         (MARSHAL-OSEQUENCE (OMG.ORG/FEATURES:CONTEXT_DATA OBJ) BUFFER)))

(DEFINE-ALIAS IOP:SERVICEID
 :ID "IDL:IOP/ServiceId:1.0"
 :NAME "ServiceId"
 :TYPE OMG.ORG/CORBA:ULONG
 :TYPECODE OMG.ORG/CORBA:TC_ULONG)

(DEFCONSTANT IOP:TAG_DCE_SEC_MECH (QUOTE 103))

(DEFCONSTANT IOP:TAG_DCE_NO_PIPES (QUOTE 102))

(DEFCONSTANT IOP:TAG_DCE_BINDING_NAME (QUOTE 101))

(DEFCONSTANT IOP:TAG_DCE_STRING_BINDING (QUOTE 100))

(DEFCONSTANT IOP:TAG_LOCATION_POLICY (QUOTE 12))

(DEFCONSTANT IOP:TAG_ENDPOINT_ID_POSITION (QUOTE 6))

(DEFCONSTANT IOP:TAG_COMPLETE_OBJECT_KEY (QUOTE 5))

(DEFCONSTANT IOP:TAG_JAVA_CODEBASE (QUOTE 25))

(DEFCONSTANT IOP:TAG_GENERIC_SEC_MECH (QUOTE 22))

(DEFCONSTANT IOP:TAG_CSI_ECMA_PUBLIC_SEC_MECH (QUOTE 21))

(DEFCONSTANT IOP:TAG_SSL_SEC_TRANS (QUOTE 20))

(DEFCONSTANT IOP:TAG_CSI_ECMA_HYBRID_SEC_MECH (QUOTE 19))

(DEFCONSTANT IOP:TAG_CSI_ECMA_SECRET_SEC_MECH (QUOTE 18))

(DEFCONSTANT IOP:TAG_KERBEROSV5_SEC_MECH (QUOTE 17))

(DEFCONSTANT IOP:TAG_SPKM_2_SEC_MECH (QUOTE 16))

(DEFCONSTANT IOP:TAG_SPKM_1_SEC_MECH (QUOTE 15))

(DEFCONSTANT IOP:TAG_SEC_NAME (QUOTE 14))

(DEFCONSTANT IOP:TAG_ASSOCIATION_OPTIONS (QUOTE 13))

(DEFCONSTANT IOP:TAG_ALTERNATE_IIOP_ADDRESS (QUOTE 3))

(DEFCONSTANT IOP:TAG_POLICIES (QUOTE 2))

(DEFCONSTANT IOP:TAG_CODE_SETS (QUOTE 1))

(DEFCONSTANT IOP:TAG_ORB_TYPE (QUOTE 0))

(DEFINE-ALIAS IOP:MULTIPLECOMPONENTPROFILE
 :ID "IDL:IOP/MultipleComponentProfile:1.0"
 :NAME "MultipleComponentProfile"
 :TYPE SEQUENCE
 :TYPECODE (MAKE-SEQUENCE-TYPECODE (SYMBOL-TYPECODE 'IOP:TAGGEDCOMPONENT) 0))

(DEFINE-STRUCT IOP:TAGGEDCOMPONENT
 :ID "IDL:IOP/TaggedComponent:1.0"
 :NAME "TaggedComponent"
 :MEMBERS (("tag" (SYMBOL-TYPECODE 'IOP:COMPONENTID) TAG)
           ("component_data" (MAKE-SEQUENCE-TYPECODE OMG.ORG/CORBA:TC_OCTET 0)
            COMPONENT_DATA))
 :READ ((BUFFER)
        (IOP:TAGGEDCOMPONENT
          :TAG
          (UNMARSHAL-ULONG BUFFER)
          :COMPONENT_DATA
          (UNMARSHAL-OSEQUENCE BUFFER)))
 :WRITE ((OBJ BUFFER) (MARSHAL-ULONG (OMG.ORG/FEATURES:TAG OBJ) BUFFER)
         (MARSHAL-OSEQUENCE (OMG.ORG/FEATURES:COMPONENT_DATA OBJ) BUFFER)))

(DEFINE-ALIAS IOP:COMPONENTID
 :ID "IDL:IOP/ComponentId:1.0"
 :NAME "ComponentId"
 :TYPE OMG.ORG/CORBA:ULONG
 :TYPECODE OMG.ORG/CORBA:TC_ULONG)

(DEFINE-STRUCT IOP:IOR
 :ID "IDL:IOP/IOR:1.0"
 :NAME "IOR"
 :MEMBERS (("type_id" OMG.ORG/CORBA:TC_STRING TYPE_ID)
           ("profiles"
            (MAKE-SEQUENCE-TYPECODE (SYMBOL-TYPECODE 'IOP:TAGGEDPROFILE) 0)
            PROFILES))
 :READ ((BUFFER)
        (IOP:IOR :TYPE_ID
                 (UNMARSHAL-STRING BUFFER)
                 :PROFILES
                 (UNMARSHAL-SEQUENCE
                   (LAMBDA (BUFFER) (STRUCT-READ 'IOP:TAGGEDPROFILE BUFFER))
                   BUFFER)))
 :WRITE ((OBJ BUFFER) (MARSHAL-STRING (OMG.ORG/FEATURES:TYPE_ID OBJ) BUFFER)
         (MARSHAL-SEQUENCE
           (OMG.ORG/FEATURES:PROFILES OBJ)
           (LAMBDA (OBJ BUFFER) (STRUCT-WRITE OBJ 'IOP:TAGGEDPROFILE BUFFER))
           BUFFER)))

(DEFINE-STRUCT IOP:TAGGEDPROFILE
 :ID "IDL:IOP/TaggedProfile:1.0"
 :NAME "TaggedProfile"
 :MEMBERS (("tag" (SYMBOL-TYPECODE 'IOP:PROFILEID) TAG)
           ("profile_data" (MAKE-SEQUENCE-TYPECODE OMG.ORG/CORBA:TC_OCTET 0)
            PROFILE_DATA))
 :READ ((BUFFER)
        (IOP:TAGGEDPROFILE
          :TAG
          (UNMARSHAL-ULONG BUFFER)
          :PROFILE_DATA
          (UNMARSHAL-OSEQUENCE BUFFER)))
 :WRITE ((OBJ BUFFER) (MARSHAL-ULONG (OMG.ORG/FEATURES:TAG OBJ) BUFFER)
         (MARSHAL-OSEQUENCE (OMG.ORG/FEATURES:PROFILE_DATA OBJ) BUFFER)))

(DEFCONSTANT IOP:TAG_MULTIPLE_COMPONENTS (QUOTE 1))

(DEFCONSTANT IOP:TAG_INTERNET_IOP (QUOTE 0))

(DEFINE-ALIAS IOP:PROFILEID
 :ID "IDL:IOP/ProfileId:1.0"
 :NAME "ProfileId"
 :TYPE OMG.ORG/CORBA:ULONG
 :TYPECODE OMG.ORG/CORBA:TC_ULONG)
