;;;; clorb-poa-base.lisp -- basic types in PortablServer Module
;;
;; Most of this code has been generated.
;;

(in-package :clorb)


(DEFINE-ALIAS OMG.ORG/PORTABLESERVER:OBJECTID
 :ID "IDL:omg.org/PortableServer/ObjectId:1.0"
 :NAME "ObjectId"
 :TYPE SEQUENCE
 :TYPECODE (MAKE-SEQUENCE-TYPECODE OMG.ORG/CORBA:TC_OCTET 0))

(DEFINE-ALIAS OMG.ORG/PORTABLESERVER:POALIST
 :ID "IDL:omg.org/PortableServer/POAList:1.0"
 :NAME "POAList"
 :TYPE SEQUENCE)

(DEFINE-USER-EXCEPTION OMG.ORG/PORTABLESERVER:FORWARDREQUEST
 :ID "IDL:omg.org/PortableServer/ForwardRequest:1.0"
 :NAME "ForwardRequest"
 :MEMBERS (("forward_reference" OMG.ORG/CORBA:TC_OBJREF)))


(DEFINE-ENUM OMG.ORG/PORTABLESERVER:REQUESTPROCESSINGPOLICYVALUE
 :ID "IDL:omg.org/PortableServer/RequestProcessingPolicyValue:1.0"
 :NAME "RequestProcessingPolicyValue"
 :MEMBERS ("USE_ACTIVE_OBJECT_MAP_ONLY" "USE_DEFAULT_SERVANT"
           "USE_SERVANT_MANAGER"))

(DEFINE-ENUM OMG.ORG/PORTABLESERVER:SERVANTRETENTIONPOLICYVALUE
 :ID "IDL:omg.org/PortableServer/ServantRetentionPolicyValue:1.0"
 :NAME "ServantRetentionPolicyValue"
 :MEMBERS ("RETAIN" "NON_RETAIN"))

(DEFINE-ENUM OMG.ORG/PORTABLESERVER:IMPLICITACTIVATIONPOLICYVALUE
 :ID "IDL:omg.org/PortableServer/ImplicitActivationPolicyValue:1.0"
 :NAME "ImplicitActivationPolicyValue"
 :MEMBERS ("IMPLICIT_ACTIVATION" "NO_IMPLICIT_ACTIVATION"))

(DEFINE-ENUM OMG.ORG/PORTABLESERVER:IDASSIGNMENTPOLICYVALUE
 :ID "IDL:omg.org/PortableServer/IdAssignmentPolicyValue:1.0"
 :NAME "IdAssignmentPolicyValue"
 :MEMBERS ("USER_ID" "SYSTEM_ID"))

(DEFINE-ENUM OMG.ORG/PORTABLESERVER:IDUNIQUENESSPOLICYVALUE
 :ID "IDL:omg.org/PortableServer/IdUniquenessPolicyValue:1.0"
 :NAME "IdUniquenessPolicyValue"
 :MEMBERS ("UNIQUE_ID" "MULTIPLE_ID"))

(DEFINE-ENUM OMG.ORG/PORTABLESERVER:LIFESPANPOLICYVALUE
 :ID "IDL:omg.org/PortableServer/LifespanPolicyValue:1.0"
 :NAME "LifespanPolicyValue"
 :MEMBERS ("TRANSIENT" "PERSISTENT"))

(DEFINE-ENUM OMG.ORG/PORTABLESERVER:THREADPOLICYVALUE
 :ID "IDL:omg.org/PortableServer/ThreadPolicyValue:1.0"
 :NAME "ThreadPolicyValue"
 :MEMBERS ("ORB_CTRL_MODEL" "SINGLE_THREAD_MODEL"))




(DEFINE-INTERFACE OMG.ORG/PORTABLESERVER:REQUESTPROCESSINGPOLICY (OMG.ORG/CORBA:POLICY)
 :PROXY (OMG.ORG/PORTABLESERVER:REQUESTPROCESSINGPOLICY-PROXY
         OMG.ORG/PORTABLESERVER:REQUESTPROCESSINGPOLICY
         OMG.ORG/CORBA:POLICY-PROXY)
 :ID "IDL:omg.org/PortableServer/RequestProcessingPolicy:1.0"
 :NAME "RequestProcessingPolicy")

(DEFINE-METHOD "VALUE" ((OBJ
                         OMG.ORG/PORTABLESERVER:REQUESTPROCESSINGPOLICY-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_value"
    (SYMBOL-TYPECODE 'OMG.ORG/PORTABLESERVER:REQUESTPROCESSINGPOLICYVALUE)))

(DEFINE-INTERFACE OMG.ORG/PORTABLESERVER:SERVANTRETENTIONPOLICY (OMG.ORG/CORBA:POLICY)
 :PROXY (OMG.ORG/PORTABLESERVER:SERVANTRETENTIONPOLICY-PROXY
         OMG.ORG/PORTABLESERVER:SERVANTRETENTIONPOLICY
         OMG.ORG/CORBA:POLICY-PROXY)
 :ID "IDL:omg.org/PortableServer/ServantRetentionPolicy:1.0"
 :NAME "ServantRetentionPolicy")

(DEFINE-METHOD "VALUE" ((OBJ
                         OMG.ORG/PORTABLESERVER:SERVANTRETENTIONPOLICY-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_value"
    (SYMBOL-TYPECODE 'OMG.ORG/PORTABLESERVER:SERVANTRETENTIONPOLICYVALUE)))

(DEFINE-INTERFACE OMG.ORG/PORTABLESERVER:IMPLICITACTIVATIONPOLICY(OMG.ORG/CORBA:POLICY)
 :PROXY (OMG.ORG/PORTABLESERVER:IMPLICITACTIVATIONPOLICY-PROXY
         OMG.ORG/PORTABLESERVER:IMPLICITACTIVATIONPOLICY
         OMG.ORG/CORBA:POLICY-PROXY)
 :ID "IDL:omg.org/PortableServer/ImplicitActivationPolicy:1.0"
 :NAME "ImplicitActivationPolicy")

(DEFINE-METHOD "VALUE" ((OBJ
                         OMG.ORG/PORTABLESERVER:IMPLICITACTIVATIONPOLICY-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_value"
    (SYMBOL-TYPECODE 'OMG.ORG/PORTABLESERVER:IMPLICITACTIVATIONPOLICYVALUE)))

(DEFINE-INTERFACE OMG.ORG/PORTABLESERVER:IDASSIGNMENTPOLICY (OMG.ORG/CORBA:POLICY)
 :PROXY (OMG.ORG/PORTABLESERVER:IDASSIGNMENTPOLICY-PROXY
         OMG.ORG/PORTABLESERVER:IDASSIGNMENTPOLICY OMG.ORG/CORBA:POLICY-PROXY)
 :ID "IDL:omg.org/PortableServer/IdAssignmentPolicy:1.0"
 :NAME "IdAssignmentPolicy")

(DEFINE-METHOD "VALUE" ((OBJ OMG.ORG/PORTABLESERVER:IDASSIGNMENTPOLICY-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_value"
    (SYMBOL-TYPECODE 'OMG.ORG/PORTABLESERVER:IDASSIGNMENTPOLICYVALUE)))

(DEFINE-INTERFACE OMG.ORG/PORTABLESERVER:IDUNIQUENESSPOLICY (OMG.ORG/CORBA:POLICY)
 :PROXY (OMG.ORG/PORTABLESERVER:IDUNIQUENESSPOLICY-PROXY
         OMG.ORG/PORTABLESERVER:IDUNIQUENESSPOLICY OMG.ORG/CORBA:POLICY-PROXY)
 :ID "IDL:omg.org/PortableServer/IdUniquenessPolicy:1.0"
 :NAME "IdUniquenessPolicy")

(DEFINE-METHOD "VALUE" ((OBJ OMG.ORG/PORTABLESERVER:IDUNIQUENESSPOLICY-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_value"
    (SYMBOL-TYPECODE 'OMG.ORG/PORTABLESERVER:IDUNIQUENESSPOLICYVALUE)))

(DEFINE-INTERFACE OMG.ORG/PORTABLESERVER:LIFESPANPOLICY (OMG.ORG/CORBA:POLICY)
 :PROXY (OMG.ORG/PORTABLESERVER:LIFESPANPOLICY-PROXY
         OMG.ORG/PORTABLESERVER:LIFESPANPOLICY OMG.ORG/CORBA:POLICY-PROXY)
 :ID "IDL:omg.org/PortableServer/LifespanPolicy:1.0"
 :NAME "LifespanPolicy")

(DEFINE-METHOD "VALUE" ((OBJ OMG.ORG/PORTABLESERVER:LIFESPANPOLICY-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_value"
    (SYMBOL-TYPECODE 'OMG.ORG/PORTABLESERVER:LIFESPANPOLICYVALUE)))

(DEFINE-INTERFACE OMG.ORG/PORTABLESERVER:THREADPOLICY (OMG.ORG/CORBA:POLICY)
 :PROXY (OMG.ORG/PORTABLESERVER:THREADPOLICY-PROXY
         OMG.ORG/PORTABLESERVER:THREADPOLICY OMG.ORG/CORBA:POLICY-PROXY)
 :ID "IDL:omg.org/PortableServer/ThreadPolicy:1.0"
 :NAME "ThreadPolicy")

(DEFINE-METHOD "VALUE" ((OBJ OMG.ORG/PORTABLESERVER:THREADPOLICY-PROXY))
  (GET-ATTRIBUTE
    OBJ
    "_get_value"
    (SYMBOL-TYPECODE 'OMG.ORG/PORTABLESERVER:THREADPOLICYVALUE)))



(DEFCONSTANT OMG.ORG/PORTABLESERVER:REQUEST_PROCESSING_POLICY_ID (QUOTE 22))

(DEFCONSTANT OMG.ORG/PORTABLESERVER:SERVANT_RETENTION_POLICY_ID (QUOTE 21))

(DEFCONSTANT OMG.ORG/PORTABLESERVER:IMPLICIT_ACTIVATION_POLICY_ID (QUOTE 20))

(DEFCONSTANT OMG.ORG/PORTABLESERVER:ID_ASSIGNMENT_POLICY_ID (QUOTE 19))

(DEFCONSTANT OMG.ORG/PORTABLESERVER:ID_UNIQUENESS_POLICY_ID (QUOTE 18))

(DEFCONSTANT OMG.ORG/PORTABLESERVER:LIFESPAN_POLICY_ID (QUOTE 17))

(DEFCONSTANT OMG.ORG/PORTABLESERVER:THREAD_POLICY_ID (QUOTE 16))






(DEFINE-USER-EXCEPTION OMG.ORG/PORTABLESERVER:POA/WRONGPOLICY
 :ID "IDL:omg.org/PortableServer/POA/WrongPolicy:1.0"
 :NAME "WrongPolicy"
 :MEMBERS NIL)

(DEFINE-USER-EXCEPTION OMG.ORG/PORTABLESERVER:POA/WRONGADAPTER
 :ID "IDL:omg.org/PortableServer/POA/WrongAdapter:1.0"
 :NAME "WrongAdapter"
 :MEMBERS NIL)

(DEFINE-USER-EXCEPTION OMG.ORG/PORTABLESERVER:POA/SERVANTNOTACTIVE
 :ID "IDL:omg.org/PortableServer/POA/ServantNotActive:1.0"
 :NAME "ServantNotActive"
 :MEMBERS NIL)

(DEFINE-USER-EXCEPTION OMG.ORG/PORTABLESERVER:POA/SERVANTALREADYACTIVE
 :ID "IDL:omg.org/PortableServer/POA/ServantAlreadyActive:1.0"
 :NAME "ServantAlreadyActive"
 :MEMBERS NIL)

(DEFINE-USER-EXCEPTION OMG.ORG/PORTABLESERVER:POA/OBJECTNOTACTIVE
 :ID "IDL:omg.org/PortableServer/POA/ObjectNotActive:1.0"
 :NAME "ObjectNotActive"
 :MEMBERS NIL)

(DEFINE-USER-EXCEPTION OMG.ORG/PORTABLESERVER:POA/OBJECTALREADYACTIVE
 :ID "IDL:omg.org/PortableServer/POA/ObjectAlreadyActive:1.0"
 :NAME "ObjectAlreadyActive"
 :MEMBERS NIL)

(DEFINE-USER-EXCEPTION OMG.ORG/PORTABLESERVER:POA/NOSERVANT
 :ID "IDL:omg.org/PortableServer/POA/NoServant:1.0"
 :NAME "NoServant"
 :MEMBERS NIL)

(DEFINE-USER-EXCEPTION OMG.ORG/PORTABLESERVER:POA/INVALIDPOLICY
 :ID "IDL:omg.org/PortableServer/POA/InvalidPolicy:1.0"
 :NAME "InvalidPolicy"
 :MEMBERS (("index" OMG.ORG/CORBA:TC_USHORT)))

(DEFINE-USER-EXCEPTION OMG.ORG/PORTABLESERVER:POA/ADAPTERNONEXISTENT
 :ID "IDL:omg.org/PortableServer/POA/AdapterNonExistent:1.0"
 :NAME "AdapterNonExistent"
 :MEMBERS NIL)

(DEFINE-USER-EXCEPTION OMG.ORG/PORTABLESERVER:POA/ADAPTERALREADYEXISTS
 :ID "IDL:omg.org/PortableServer/POA/AdapterAlreadyExists:1.0"
 :NAME "AdapterAlreadyExists"
 :MEMBERS NIL)


(DEFINE-USER-EXCEPTION OMG.ORG/PORTABLESERVER:CURRENT/NOCONTEXT
 :ID "IDL:omg.org/PortableServer/Current/NoContext:1.0"
 :NAME "NoContext"
 :MEMBERS NIL)