
(IN-PACKAGE :CLORB)

(DEFCONSTANT IOP:UNKNOWNEXCEPTIONINFO (QUOTE 9))

(DEFCONSTANT IOP:FORWARDED_IDENTITY (QUOTE 8))

(DEFCONSTANT IOP:INVOCATION_POLICIES (QUOTE 7))

(DEFCONSTANT IOP:SENDINGCONTEXTRUNTIME (QUOTE 6))

(DEFCONSTANT IOP:BI_DIR_IIOP (QUOTE 5))

(DEFCONSTANT IOP:LOGICALTHREADID (QUOTE 4))

(DEFCONSTANT IOP:CHAINBYPASSINFO (QUOTE 3))

(DEFCONSTANT IOP:CHAINBYPASSCHECK (QUOTE 2))

(DEFCONSTANT IOP:CODESETS (QUOTE 1))

(DEFCONSTANT IOP:TRANSACTIONSERVICE (QUOTE 0))

(SET-SYMBOL-IFR-ID 'IOP:SERVICECONTEXTLIST "IDL:IOP/ServiceContextList:1.0")

(SET-SYMBOL-TYPECODE
  'IOP:SERVICECONTEXTLIST
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:IOP/ServiceContextList:1.0"
      "ServiceContextList"
      (MAKE-SEQUENCE-TYPECODE (SYMBOL-TYPECODE 'IOP:SERVICECONTEXT) 0))))

(DEFTYPE IOP:SERVICECONTEXTLIST () 'SEQUENCE)

(SET-SYMBOL-IFR-ID 'IOP:SERVICECONTEXT "IDL:IOP/ServiceContext:1.0")

(SET-SYMBOL-TYPECODE
  'IOP:SERVICECONTEXT
  (LAMBDA NIL
    (STRUCT-TYPECODE
      "IDL:IOP/ServiceContext:1.0"
      "ServiceContext"
      "context_id"
      (SYMBOL-TYPECODE 'IOP:SERVICEID)
      "context_data"
      (MAKE-SEQUENCE-TYPECODE OMG.ORG/CORBA:TC_OCTET 0))))

(DEFINE-CORBA-STRUCT IOP:SERVICECONTEXT
 :ID "IDL:IOP/ServiceContext:1.0"
 :MEMBERS ((CONTEXT_ID NIL) (CONTEXT_DATA NIL)))

(SET-SYMBOL-IFR-ID 'IOP:SERVICEID "IDL:IOP/ServiceId:1.0")

(SET-SYMBOL-TYPECODE
  'IOP:SERVICEID
  (LAMBDA NIL
    (MAKE-TC-ALIAS "IDL:IOP/ServiceId:1.0" "ServiceId" OMG.ORG/CORBA:TC_ULONG)))

(DEFTYPE IOP:SERVICEID () 'OMG.ORG/CORBA:ULONG)

(DEFCONSTANT IOP:TAG_DCE_SEC_MECH (QUOTE 103))

(DEFCONSTANT IOP:TAG_DCE_NO_PIPES (QUOTE 102))

(DEFCONSTANT IOP:TAG_DCE_BINDING_NAME (QUOTE 101))

(DEFCONSTANT IOP:TAG_DCE_STRING_BINDING (QUOTE 100))

(DEFCONSTANT IOP:TAG_LOCATION_POLICY (QUOTE 12))

(DEFCONSTANT IOP:TAG_ENDPOINT_ID_POSITION (QUOTE 6))

(DEFCONSTANT IOP:TAG_COMPLETE_OBJECT_KEY (QUOTE 5))

(DEFCONSTANT IOP:TAG_JAVA_CODEBASE (QUOTE 25))

(DEFCONSTANT IOP:TAG_GENERIC_SEC_MECH (QUOTE 22))

(DEFCONSTANT IOP:TAG_CSI_ECMA_PUBLIC_SEC_MECH (QUOTE 21))

(DEFCONSTANT IOP:TAG_SSL_SEC_TRANS (QUOTE 20))

(DEFCONSTANT IOP:TAG_CSI_ECMA_HYBRID_SEC_MECH (QUOTE 19))

(DEFCONSTANT IOP:TAG_CSI_ECMA_SECRET_SEC_MECH (QUOTE 18))

(DEFCONSTANT IOP:TAG_KERBEROSV5_SEC_MECH (QUOTE 17))

(DEFCONSTANT IOP:TAG_SPKM_2_SEC_MECH (QUOTE 16))

(DEFCONSTANT IOP:TAG_SPKM_1_SEC_MECH (QUOTE 15))

(DEFCONSTANT IOP:TAG_SEC_NAME (QUOTE 14))

(DEFCONSTANT IOP:TAG_ASSOCIATION_OPTIONS (QUOTE 13))

(DEFCONSTANT IOP:TAG_ALTERNATE_IIOP_ADDRESS (QUOTE 3))

(DEFCONSTANT IOP:TAG_POLICIES (QUOTE 2))

(DEFCONSTANT IOP:TAG_CODE_SETS (QUOTE 1))

(DEFCONSTANT IOP:TAG_ORB_TYPE (QUOTE 0))

(SET-SYMBOL-IFR-ID
  'IOP:MULTIPLECOMPONENTPROFILE
  "IDL:IOP/MultipleComponentProfile:1.0")

(SET-SYMBOL-TYPECODE
  'IOP:MULTIPLECOMPONENTPROFILE
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:IOP/MultipleComponentProfile:1.0"
      "MultipleComponentProfile"
      (MAKE-SEQUENCE-TYPECODE (SYMBOL-TYPECODE 'IOP:TAGGEDCOMPONENT) 0))))

(DEFTYPE IOP:MULTIPLECOMPONENTPROFILE () 'SEQUENCE)

(SET-SYMBOL-IFR-ID 'IOP:TAGGEDCOMPONENT "IDL:IOP/TaggedComponent:1.0")

(SET-SYMBOL-TYPECODE
  'IOP:TAGGEDCOMPONENT
  (LAMBDA NIL
    (STRUCT-TYPECODE
      "IDL:IOP/TaggedComponent:1.0"
      "TaggedComponent"
      "tag"
      (SYMBOL-TYPECODE 'IOP:COMPONENTID)
      "component_data"
      (MAKE-SEQUENCE-TYPECODE OMG.ORG/CORBA:TC_OCTET 0))))

(DEFINE-CORBA-STRUCT IOP:TAGGEDCOMPONENT
 :ID "IDL:IOP/TaggedComponent:1.0"
 :MEMBERS ((TAG NIL) (COMPONENT_DATA NIL)))

(SET-SYMBOL-IFR-ID 'IOP:COMPONENTID "IDL:IOP/ComponentId:1.0")

(SET-SYMBOL-TYPECODE
  'IOP:COMPONENTID
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:IOP/ComponentId:1.0"
      "ComponentId"
      OMG.ORG/CORBA:TC_ULONG)))

(DEFTYPE IOP:COMPONENTID () 'OMG.ORG/CORBA:ULONG)

(SET-SYMBOL-IFR-ID 'IOP:IOR "IDL:IOP/IOR:1.0")

(SET-SYMBOL-TYPECODE
  'IOP:IOR
  (LAMBDA NIL
    (STRUCT-TYPECODE
      "IDL:IOP/IOR:1.0"
      "IOR"
      "type_id"
      OMG.ORG/CORBA:TC_STRING
      "profiles"
      (MAKE-SEQUENCE-TYPECODE (SYMBOL-TYPECODE 'IOP:TAGGEDPROFILE) 0))))

(DEFINE-CORBA-STRUCT IOP:IOR
 :ID "IDL:IOP/IOR:1.0"
 :MEMBERS ((TYPE_ID NIL) (PROFILES NIL)))

(SET-SYMBOL-IFR-ID 'IOP:TAGGEDPROFILE "IDL:IOP/TaggedProfile:1.0")

(SET-SYMBOL-TYPECODE
  'IOP:TAGGEDPROFILE
  (LAMBDA NIL
    (STRUCT-TYPECODE
      "IDL:IOP/TaggedProfile:1.0"
      "TaggedProfile"
      "tag"
      (SYMBOL-TYPECODE 'IOP:PROFILEID)
      "profile_data"
      (MAKE-SEQUENCE-TYPECODE OMG.ORG/CORBA:TC_OCTET 0))))

(DEFINE-CORBA-STRUCT IOP:TAGGEDPROFILE
 :ID "IDL:IOP/TaggedProfile:1.0"
 :MEMBERS ((TAG NIL) (PROFILE_DATA NIL)))

(DEFCONSTANT IOP:TAG_MULTIPLE_COMPONENTS (QUOTE 1))

(DEFCONSTANT IOP:TAG_INTERNET_IOP (QUOTE 0))

(SET-SYMBOL-IFR-ID 'IOP:PROFILEID "IDL:IOP/ProfileId:1.0")

(SET-SYMBOL-TYPECODE
  'IOP:PROFILEID
  (LAMBDA NIL
    (MAKE-TC-ALIAS "IDL:IOP/ProfileId:1.0" "ProfileId" OMG.ORG/CORBA:TC_ULONG)))

(DEFTYPE IOP:PROFILEID () 'OMG.ORG/CORBA:ULONG)
