(in-package :clorb)

(defpackage "COSEVENTCOMM"
  (:use)
  (:export
   DISCONNECTED PULLCONSUMER PULLCONSUMER-PROXY 
   PULLSUPPLIER PULLSUPPLIER-PROXY PUSHCONSUMER 
   PUSHCONSUMER-PROXY PUSHSUPPLIER PUSHSUPPLIER-PROXY ))


(DEFCLASS COSEVENTCOMM:PULLCONSUMER (OBJECT) NIL)
(DEFCLASS COSEVENTCOMM:PULLCONSUMER-PROXY
 (COSEVENTCOMM:PULLCONSUMER OMG.ORG/CORBA:PROXY) NIL)
(REGISTER-PROXY-CLASS "IDL:omg.org/CosEventComm/PullConsumer:1.0"
 'COSEVENTCOMM:PULLCONSUMER-PROXY)
(DEFMETHOD OMG.ORG/FEATURES:DISCONNECT_PULL_CONSUMER
 ((OBJ COSEVENTCOMM:PULLCONSUMER-PROXY) &REST ARGS)
 (APPLY 'INVOKE OBJ "disconnect_pull_consumer" ARGS))
(DEFCLASS COSEVENTCOMM:PULLSUPPLIER (OBJECT) NIL)
(DEFCLASS COSEVENTCOMM:PULLSUPPLIER-PROXY
 (COSEVENTCOMM:PULLSUPPLIER OMG.ORG/CORBA:PROXY) NIL)
(REGISTER-PROXY-CLASS "IDL:omg.org/CosEventComm/PullSupplier:1.0"
 'COSEVENTCOMM:PULLSUPPLIER-PROXY)
(DEFMETHOD OMG.ORG/FEATURES:DISCONNECT_PULL_SUPPLIER
 ((OBJ COSEVENTCOMM:PULLSUPPLIER-PROXY) &REST ARGS)
 (APPLY 'INVOKE OBJ "disconnect_pull_supplier" ARGS))
(DEFMETHOD OMG.ORG/FEATURES:TRY_PULL
 ((OBJ COSEVENTCOMM:PULLSUPPLIER-PROXY) &REST ARGS)
 (APPLY 'INVOKE OBJ "try_pull" ARGS))
(DEFMETHOD OMG.ORG/FEATURES:PULL
 ((OBJ COSEVENTCOMM:PULLSUPPLIER-PROXY) &REST ARGS)
 (APPLY 'INVOKE OBJ "pull" ARGS))
(DEFCLASS COSEVENTCOMM:PUSHSUPPLIER (OBJECT) NIL)
(DEFCLASS COSEVENTCOMM:PUSHSUPPLIER-PROXY
 (COSEVENTCOMM:PUSHSUPPLIER OMG.ORG/CORBA:PROXY) NIL)
(REGISTER-PROXY-CLASS "IDL:omg.org/CosEventComm/PushSupplier:1.0"
 'COSEVENTCOMM:PUSHSUPPLIER-PROXY)
(DEFMETHOD OMG.ORG/FEATURES:DISCONNECT_PUSH_SUPPLIER
 ((OBJ COSEVENTCOMM:PUSHSUPPLIER-PROXY) &REST ARGS)
 (APPLY 'INVOKE OBJ "disconnect_push_supplier" ARGS))
(DEFCLASS COSEVENTCOMM:PUSHCONSUMER (OBJECT) NIL)
(DEFCLASS COSEVENTCOMM:PUSHCONSUMER-PROXY
 (COSEVENTCOMM:PUSHCONSUMER OMG.ORG/CORBA:PROXY) NIL)
(REGISTER-PROXY-CLASS "IDL:omg.org/CosEventComm/PushConsumer:1.0"
 'COSEVENTCOMM:PUSHCONSUMER-PROXY)
(DEFMETHOD OMG.ORG/FEATURES:DISCONNECT_PUSH_CONSUMER
 ((OBJ COSEVENTCOMM:PUSHCONSUMER-PROXY) &REST ARGS)
 (APPLY 'INVOKE OBJ "disconnect_push_consumer" ARGS))
(DEFMETHOD OMG.ORG/FEATURES:PUSH
 ((OBJ COSEVENTCOMM:PUSHCONSUMER-PROXY) &REST ARGS)
 (APPLY 'INVOKE OBJ "push" ARGS))
(DEFINE-USER-EXCEPTION COSEVENTCOMM:DISCONNECTED :ID
 "IDL:omg.org/CosEventComm/Disconnected:1.0" :SLOTS NIL)
