
(IN-PACKAGE :CLORB)

(EVAL-WHEN (:COMPILE-TOPLEVEL :LOAD-TOPLEVEL :EXECUTE)
  (ENSURE-CORBA-PACKAGE
    "COSNAMING"
    :EXPORT
    '("NAMINGCONTEXTEXT/INVALIDADDRESS" "NAMINGCONTEXTEXT/ADDRESS"
      "NAMINGCONTEXTEXT/URLSTRING" "NAMINGCONTEXTEXT/STRINGNAME"
      "NAMINGCONTEXTEXT-PROXY" "NAMINGCONTEXTEXT"
      "NAMINGCONTEXT/NOTFOUNDREASON" "NAMINGCONTEXT/INVALIDNAME"
      "NAMINGCONTEXT/CANNOTPROCEED" "NAMINGCONTEXT/ALREADYBOUND"
      "NAMINGCONTEXT/NOTFOUND" "NAMINGCONTEXT/NOTEMPTY" "NAMINGCONTEXT-PROXY"
      "NAMINGCONTEXT" "BINDINGITERATOR-PROXY" "BINDINGITERATOR" "ISTRING"
      "NAMECOMPONENT" "BINDINGTYPE" "NAME" "BINDING" "BINDINGLIST")))

(SET-SYMBOL-ID/TYPECODE
  'COSNAMING:BINDINGLIST
  "IDL:omg.org/CosNaming/BindingList:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CosNaming/BindingList:1.0"
      "BindingList"
      (MAKE-SEQUENCE-TYPECODE (SYMBOL-TYPECODE 'COSNAMING:BINDING) 0))))

(DEFTYPE COSNAMING:BINDINGLIST () 'SEQUENCE)

(DEFINE-STRUCT COSNAMING:BINDING
 :ID "IDL:omg.org/CosNaming/Binding:1.0"
 :NAME "Binding"
 :MEMBERS (("binding_name" (SYMBOL-TYPECODE 'COSNAMING:NAME) BINDING_NAME)
           ("binding_type" (SYMBOL-TYPECODE 'COSNAMING:BINDINGTYPE)
            BINDING_TYPE)))

(SET-SYMBOL-ID/TYPECODE
  'COSNAMING:BINDINGTYPE
  "IDL:omg.org/CosNaming/BindingType:1.0"
  (MAKE-TYPECODE
    :TK_ENUM
    "IDL:omg.org/CosNaming/BindingType:1.0"
    "BindingType"
    '("nobject" "ncontext")))

(DEFTYPE COSNAMING:BINDINGTYPE () '(MEMBER :NOBJECT :NCONTEXT))

(SET-SYMBOL-ID/TYPECODE
  'COSNAMING:NAME
  "IDL:omg.org/CosNaming/Name:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CosNaming/Name:1.0"
      "Name"
      (MAKE-SEQUENCE-TYPECODE (SYMBOL-TYPECODE 'COSNAMING:NAMECOMPONENT) 0))))

(DEFTYPE COSNAMING:NAME () 'SEQUENCE)

(DEFINE-STRUCT COSNAMING:NAMECOMPONENT
 :ID "IDL:omg.org/CosNaming/NameComponent:1.0"
 :NAME "NameComponent"
 :MEMBERS (("id" (SYMBOL-TYPECODE 'COSNAMING:ISTRING) ID)
           ("kind" (SYMBOL-TYPECODE 'COSNAMING:ISTRING) KIND)))

(SET-SYMBOL-ID/TYPECODE
  'COSNAMING:ISTRING
  "IDL:omg.org/CosNaming/Istring:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CosNaming/Istring:1.0"
      "Istring"
      OMG.ORG/CORBA:TC_STRING)))

(DEFTYPE COSNAMING:ISTRING () 'OMG.ORG/CORBA:STRING)

(SET-SYMBOL-ID/TYPECODE
  'COSNAMING:BINDINGITERATOR
  "IDL:omg.org/CosNaming/BindingIterator:1.0"
  (MAKE-TYPECODE
    :TK_OBJREF
    "IDL:omg.org/CosNaming/BindingIterator:1.0"
    "BindingIterator"))

(DEFCLASS COSNAMING:BINDINGITERATOR (OBJECT) NIL)

(DEFCLASS COSNAMING:BINDINGITERATOR-PROXY (COSNAMING:BINDINGITERATOR
                                           OMG.ORG/CORBA:PROXY)
  NIL)

(REGISTER-PROXY-CLASS
  "IDL:omg.org/CosNaming/BindingIterator:1.0"
  'COSNAMING:BINDINGITERATOR-PROXY)

(DEFINE-METHOD "DESTROY" ((OBJ COSNAMING:BINDINGITERATOR-PROXY))
  (LET ((_REQUEST (REQUEST-CREATE OBJ "destroy" OMG.ORG/CORBA:TC_VOID)))
    (REQUEST-FUNCALL _REQUEST)))

(DEFINE-METHOD "NEXT_N" ((OBJ COSNAMING:BINDINGITERATOR-PROXY) HOW_MANY)
  (LET ((_REQUEST (REQUEST-CREATE OBJ "next_n" OMG.ORG/CORBA:TC_BOOLEAN)))
    (ADD-ARG _REQUEST "how_many" ARG_IN OMG.ORG/CORBA:TC_ULONG HOW_MANY)
    (ADD-ARG _REQUEST "bl" ARG_OUT (SYMBOL-TYPECODE 'COSNAMING:BINDINGLIST))
    (REQUEST-FUNCALL _REQUEST)))

(DEFINE-METHOD "NEXT_ONE" ((OBJ COSNAMING:BINDINGITERATOR-PROXY))
  (LET ((_REQUEST (REQUEST-CREATE OBJ "next_one" OMG.ORG/CORBA:TC_BOOLEAN)))
    (ADD-ARG _REQUEST "b" ARG_OUT (SYMBOL-TYPECODE 'COSNAMING:BINDING))
    (REQUEST-FUNCALL _REQUEST)))

(SET-SYMBOL-ID/TYPECODE
  'COSNAMING:NAMINGCONTEXT
  "IDL:omg.org/CosNaming/NamingContext:1.0"
  (MAKE-TYPECODE
    :TK_OBJREF
    "IDL:omg.org/CosNaming/NamingContext:1.0"
    "NamingContext"))

(DEFCLASS COSNAMING:NAMINGCONTEXT (OBJECT) NIL)

(DEFCLASS COSNAMING:NAMINGCONTEXT-PROXY (COSNAMING:NAMINGCONTEXT
                                         OMG.ORG/CORBA:PROXY)
  NIL)

(REGISTER-PROXY-CLASS
  "IDL:omg.org/CosNaming/NamingContext:1.0"
  'COSNAMING:NAMINGCONTEXT-PROXY)

(DEFINE-METHOD "LIST" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) HOW_MANY)
  (LET ((_REQUEST (REQUEST-CREATE OBJ "list" OMG.ORG/CORBA:TC_VOID)))
    (ADD-ARG _REQUEST "how_many" ARG_IN OMG.ORG/CORBA:TC_ULONG HOW_MANY)
    (ADD-ARG _REQUEST "bl" ARG_OUT (SYMBOL-TYPECODE 'COSNAMING:BINDINGLIST))
    (ADD-ARG _REQUEST
             "bi"
             ARG_OUT
             (SYMBOL-TYPECODE 'COSNAMING:BINDINGITERATOR))
    (REQUEST-FUNCALL _REQUEST)))

(DEFINE-METHOD "DESTROY" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY))
  (LET ((_REQUEST (REQUEST-CREATE OBJ "destroy" OMG.ORG/CORBA:TC_VOID)))
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/NOTEMPTY))
    (REQUEST-FUNCALL _REQUEST)))

(DEFINE-METHOD "BIND_NEW_CONTEXT" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) N)
  (LET ((_REQUEST
         (REQUEST-CREATE
           OBJ
           "bind_new_context"
           (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT))))
    (ADD-ARG _REQUEST "n" ARG_IN (SYMBOL-TYPECODE 'COSNAMING:NAME) N)
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/NOTFOUND))
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/ALREADYBOUND))
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/CANNOTPROCEED))
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/INVALIDNAME))
    (REQUEST-FUNCALL _REQUEST)))

(DEFINE-METHOD "NEW_CONTEXT" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY))
  (LET ((_REQUEST
         (REQUEST-CREATE
           OBJ
           "new_context"
           (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT))))
    (REQUEST-FUNCALL _REQUEST)))

(DEFINE-METHOD "UNBIND" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) N)
  (LET ((_REQUEST (REQUEST-CREATE OBJ "unbind" OMG.ORG/CORBA:TC_VOID)))
    (ADD-ARG _REQUEST "n" ARG_IN (SYMBOL-TYPECODE 'COSNAMING:NAME) N)
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/NOTFOUND))
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/CANNOTPROCEED))
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/INVALIDNAME))
    (REQUEST-FUNCALL _REQUEST)))

(DEFINE-METHOD "RESOLVE" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) N)
  (LET ((_REQUEST (REQUEST-CREATE OBJ "resolve" OMG.ORG/CORBA:TC_OBJREF)))
    (ADD-ARG _REQUEST "n" ARG_IN (SYMBOL-TYPECODE 'COSNAMING:NAME) N)
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/NOTFOUND))
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/CANNOTPROCEED))
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/INVALIDNAME))
    (REQUEST-FUNCALL _REQUEST)))

(DEFINE-METHOD "REBIND_CONTEXT" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) N NC)
  (LET ((_REQUEST (REQUEST-CREATE OBJ "rebind_context" OMG.ORG/CORBA:TC_VOID)))
    (ADD-ARG _REQUEST "n" ARG_IN (SYMBOL-TYPECODE 'COSNAMING:NAME) N)
    (ADD-ARG _REQUEST
             "nc"
             ARG_IN
             (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT)
             NC)
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/NOTFOUND))
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/CANNOTPROCEED))
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/INVALIDNAME))
    (REQUEST-FUNCALL _REQUEST)))

(DEFINE-METHOD "BIND_CONTEXT" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) N NC)
  (LET ((_REQUEST (REQUEST-CREATE OBJ "bind_context" OMG.ORG/CORBA:TC_VOID)))
    (ADD-ARG _REQUEST "n" ARG_IN (SYMBOL-TYPECODE 'COSNAMING:NAME) N)
    (ADD-ARG _REQUEST
             "nc"
             ARG_IN
             (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT)
             NC)
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/NOTFOUND))
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/CANNOTPROCEED))
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/INVALIDNAME))
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/ALREADYBOUND))
    (REQUEST-FUNCALL _REQUEST)))

(DEFINE-METHOD "REBIND" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) N OBJ)
  (LET ((_REQUEST (REQUEST-CREATE OBJ "rebind" OMG.ORG/CORBA:TC_VOID)))
    (ADD-ARG _REQUEST "n" ARG_IN (SYMBOL-TYPECODE 'COSNAMING:NAME) N)
    (ADD-ARG _REQUEST "obj" ARG_IN OMG.ORG/CORBA:TC_OBJREF OBJ)
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/NOTFOUND))
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/CANNOTPROCEED))
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/INVALIDNAME))
    (REQUEST-FUNCALL _REQUEST)))

(DEFINE-METHOD "BIND" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) N OBJ)
  (LET ((_REQUEST (REQUEST-CREATE OBJ "bind" OMG.ORG/CORBA:TC_VOID)))
    (ADD-ARG _REQUEST "n" ARG_IN (SYMBOL-TYPECODE 'COSNAMING:NAME) N)
    (ADD-ARG _REQUEST "obj" ARG_IN OMG.ORG/CORBA:TC_OBJREF OBJ)
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/NOTFOUND))
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/CANNOTPROCEED))
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/INVALIDNAME))
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/ALREADYBOUND))
    (REQUEST-FUNCALL _REQUEST)))

(DEFINE-USER-EXCEPTION COSNAMING:NAMINGCONTEXT/NOTEMPTY
 :ID "IDL:omg.org/CosNaming/NamingContext/NotEmpty:1.0"
 :NAME "NotEmpty"
 :MEMBERS NIL)

(DEFINE-USER-EXCEPTION COSNAMING:NAMINGCONTEXT/ALREADYBOUND
 :ID "IDL:omg.org/CosNaming/NamingContext/AlreadyBound:1.0"
 :NAME "AlreadyBound"
 :MEMBERS NIL)

(DEFINE-USER-EXCEPTION COSNAMING:NAMINGCONTEXT/INVALIDNAME
 :ID "IDL:omg.org/CosNaming/NamingContext/InvalidName:1.0"
 :NAME "InvalidName"
 :MEMBERS NIL)

(DEFINE-USER-EXCEPTION COSNAMING:NAMINGCONTEXT/CANNOTPROCEED
 :ID "IDL:omg.org/CosNaming/NamingContext/CannotProceed:1.0"
 :NAME "CannotProceed"
 :MEMBERS (("cxt" (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT))
           ("rest_of_name" (SYMBOL-TYPECODE 'COSNAMING:NAME))))

(DEFINE-USER-EXCEPTION COSNAMING:NAMINGCONTEXT/NOTFOUND
 :ID "IDL:omg.org/CosNaming/NamingContext/NotFound:1.0"
 :NAME "NotFound"
 :MEMBERS (("why" (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/NOTFOUNDREASON))
           ("rest_of_name" (SYMBOL-TYPECODE 'COSNAMING:NAME))))

(SET-SYMBOL-ID/TYPECODE
  'COSNAMING:NAMINGCONTEXT/NOTFOUNDREASON
  "IDL:omg.org/CosNaming/NamingContext/NotFoundReason:1.0"
  (MAKE-TYPECODE
    :TK_ENUM
    "IDL:omg.org/CosNaming/NamingContext/NotFoundReason:1.0"
    "NotFoundReason"
    '("missing_node" "not_context" "not_object")))

(DEFTYPE COSNAMING:NAMINGCONTEXT/NOTFOUNDREASON ()
  '(MEMBER :MISSING_NODE :NOT_CONTEXT :NOT_OBJECT))

(SET-SYMBOL-ID/TYPECODE
  'COSNAMING:NAMINGCONTEXTEXT
  "IDL:omg.org/CosNaming/NamingContextExt:1.0"
  (MAKE-TYPECODE
    :TK_OBJREF
    "IDL:omg.org/CosNaming/NamingContextExt:1.0"
    "NamingContextExt"))

(DEFCLASS COSNAMING:NAMINGCONTEXTEXT (COSNAMING:NAMINGCONTEXT) NIL)

(DEFCLASS COSNAMING:NAMINGCONTEXTEXT-PROXY (COSNAMING:NAMINGCONTEXTEXT
                                            COSNAMING:NAMINGCONTEXT-PROXY)
  NIL)

(REGISTER-PROXY-CLASS
  "IDL:omg.org/CosNaming/NamingContextExt:1.0"
  'COSNAMING:NAMINGCONTEXTEXT-PROXY)

(DEFINE-METHOD "RESOLVE_STR" ((OBJ COSNAMING:NAMINGCONTEXTEXT-PROXY) N)
  (LET ((_REQUEST (REQUEST-CREATE OBJ "resolve_str" OMG.ORG/CORBA:TC_OBJREF)))
    (ADD-ARG _REQUEST
             "n"
             ARG_IN
             (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXTEXT/STRINGNAME)
             N)
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/NOTFOUND))
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/CANNOTPROCEED))
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/INVALIDNAME))
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/ALREADYBOUND))
    (REQUEST-FUNCALL _REQUEST)))

(DEFINE-METHOD "TO_URL" ((OBJ COSNAMING:NAMINGCONTEXTEXT-PROXY) ADDR SN)
  (LET ((_REQUEST
         (REQUEST-CREATE
           OBJ
           "to_url"
           (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXTEXT/URLSTRING))))
    (ADD-ARG _REQUEST
             "addr"
             ARG_IN
             (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXTEXT/ADDRESS)
             ADDR)
    (ADD-ARG _REQUEST
             "sn"
             ARG_IN
             (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXTEXT/STRINGNAME)
             SN)
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXTEXT/INVALIDADDRESS))
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/INVALIDNAME))
    (REQUEST-FUNCALL _REQUEST)))

(DEFINE-USER-EXCEPTION COSNAMING:NAMINGCONTEXTEXT/INVALIDADDRESS
 :ID "IDL:omg.org/CosNaming/NamingContextExt/InvalidAddress:1.0"
 :NAME "InvalidAddress"
 :MEMBERS NIL)

(DEFINE-METHOD "TO_NAME" ((OBJ COSNAMING:NAMINGCONTEXTEXT-PROXY) SN)
  (LET ((_REQUEST
         (REQUEST-CREATE OBJ "to_name" (SYMBOL-TYPECODE 'COSNAMING:NAME))))
    (ADD-ARG _REQUEST
             "sn"
             ARG_IN
             (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXTEXT/STRINGNAME)
             SN)
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/INVALIDNAME))
    (REQUEST-FUNCALL _REQUEST)))

(DEFINE-METHOD "TO_STRING" ((OBJ COSNAMING:NAMINGCONTEXTEXT-PROXY) N)
  (LET ((_REQUEST
         (REQUEST-CREATE
           OBJ
           "to_string"
           (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXTEXT/STRINGNAME))))
    (ADD-ARG _REQUEST "n" ARG_IN (SYMBOL-TYPECODE 'COSNAMING:NAME) N)
    (ADD-EXCEPTION
      _REQUEST
      (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/INVALIDNAME))
    (REQUEST-FUNCALL _REQUEST)))

(SET-SYMBOL-ID/TYPECODE
  'COSNAMING:NAMINGCONTEXTEXT/URLSTRING
  "IDL:omg.org/CosNaming/NamingContextExt/URLString:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CosNaming/NamingContextExt/URLString:1.0"
      "URLString"
      OMG.ORG/CORBA:TC_STRING)))

(DEFTYPE COSNAMING:NAMINGCONTEXTEXT/URLSTRING () 'OMG.ORG/CORBA:STRING)

(SET-SYMBOL-ID/TYPECODE
  'COSNAMING:NAMINGCONTEXTEXT/ADDRESS
  "IDL:omg.org/CosNaming/NamingContextExt/Address:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CosNaming/NamingContextExt/Address:1.0"
      "Address"
      OMG.ORG/CORBA:TC_STRING)))

(DEFTYPE COSNAMING:NAMINGCONTEXTEXT/ADDRESS () 'OMG.ORG/CORBA:STRING)

(SET-SYMBOL-ID/TYPECODE
  'COSNAMING:NAMINGCONTEXTEXT/STRINGNAME
  "IDL:omg.org/CosNaming/NamingContextExt/StringName:1.0"
  (LAMBDA NIL
    (MAKE-TC-ALIAS
      "IDL:omg.org/CosNaming/NamingContextExt/StringName:1.0"
      "StringName"
      OMG.ORG/CORBA:TC_STRING)))

(DEFTYPE COSNAMING:NAMINGCONTEXTEXT/STRINGNAME () 'OMG.ORG/CORBA:STRING)
