
(in-package :clorb)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (ENSURE-CORBA-PACKAGE
    "COSNAMING"
    :export
    '("NAMINGCONTEXTEXT/STRINGNAME" "NAMINGCONTEXTEXT/ADDRESS"
      "NAMINGCONTEXTEXT/URLSTRING" "NAMINGCONTEXTEXT/INVALIDADDRESS"
      "NAMINGCONTEXTEXT-PROXY" "NAMINGCONTEXTEXT"
      "NAMINGCONTEXT/NOTFOUNDREASON" "NAMINGCONTEXT/INVALIDNAME"
      "NAMINGCONTEXT/CANNOTPROCEED" "NAMINGCONTEXT/ALREADYBOUND"
      "NAMINGCONTEXT/NOTFOUND" "NAMINGCONTEXT/NOTEMPTY" "NAMINGCONTEXT-PROXY"
      "NAMINGCONTEXT" "BINDINGITERATOR-PROXY" "BINDINGITERATOR" "ISTRING"
      "NAMECOMPONENT" "BINDINGTYPE" "NAME" "BINDING" "BINDINGLIST")))

(DEFINE-ALIAS COSNAMING:BINDINGLIST
 :id "IDL:omg.org/CosNaming/BindingList:1.0"
 :name "BindingList"
 :type SEQUENCE
 :typecode (create-sequence-tc 0 (SYMBOL-TYPECODE 'COSNAMING:BINDING)))

(DEFINE-STRUCT COSNAMING:BINDING
 :id "IDL:omg.org/CosNaming/Binding:1.0"
 :name "Binding"
 :members (("binding_name" (SYMBOL-TYPECODE 'COSNAMING:NAME) BINDING_NAME)
           ("binding_type" (SYMBOL-TYPECODE 'COSNAMING:BINDINGTYPE)
            BINDING_TYPE))
 :read ((BUFFER)
        (COSNAMING:BINDING :binding_name
                           (UNMARSHAL-SEQUENCE
                             (lambda (buffer)
                               (STRUCT-READ 'COSNAMING:NAMECOMPONENT BUFFER))
                             BUFFER)
                           :binding_type
                           (UNMARSHAL (SYMBOL-TYPECODE 'COSNAMING:BINDINGTYPE)
                                      BUFFER)))
 :write ((OBJ BUFFER)
         (MARSHAL-SEQUENCE
           (OMG.ORG/FEATURES:BINDING_NAME OBJ)
           (lambda (obj buffer)
             (STRUCT-WRITE OBJ 'COSNAMING:NAMECOMPONENT BUFFER))
           BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:BINDING_TYPE OBJ)
                  (SYMBOL-TYPECODE 'COSNAMING:BINDINGTYPE)
                  BUFFER)))

(DEFINE-ENUM COSNAMING:BINDINGTYPE
 :id "IDL:omg.org/CosNaming/BindingType:1.0"
 :name "BindingType"
 :members ("nobject" "ncontext"))

(DEFINE-ALIAS COSNAMING:NAME
 :id "IDL:omg.org/CosNaming/Name:1.0"
 :name "Name"
 :type SEQUENCE
 :typecode (create-sequence-tc
             0
             (SYMBOL-TYPECODE 'COSNAMING:NAMECOMPONENT)))

(DEFINE-STRUCT COSNAMING:NAMECOMPONENT
 :id "IDL:omg.org/CosNaming/NameComponent:1.0"
 :name "NameComponent"
 :members (("id" (SYMBOL-TYPECODE 'COSNAMING:ISTRING) ID)
           ("kind" (SYMBOL-TYPECODE 'COSNAMING:ISTRING) KIND))
 :read ((BUFFER)
        (COSNAMING:NAMECOMPONENT
          :id
          (UNMARSHAL-STRING BUFFER)
          :kind
          (UNMARSHAL-STRING BUFFER)))
 :write ((OBJ BUFFER) (MARSHAL-STRING (OMG.ORG/FEATURES:ID OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:KIND OBJ) BUFFER)))

(DEFINE-ALIAS COSNAMING:ISTRING
 :id "IDL:omg.org/CosNaming/Istring:1.0"
 :name "Istring"
 :type OMG.ORG/CORBA:STRING
 :typecode OMG.ORG/CORBA:TC_STRING)

(DEFINE-INTERFACE COSNAMING:BINDINGITERATOR (OBJECT)
 :proxy (COSNAMING:BINDINGITERATOR-PROXY COSNAMING:BINDINGITERATOR
         OMG.ORG/CORBA:PROXY)
 :id "IDL:omg.org/CosNaming/BindingIterator:1.0"
 :name "BindingIterator")

(DEFINE-METHOD "DESTROY" ((OBJ COSNAMING:BINDINGITERATOR-PROXY))
  (STATIC-CALL ("destroy" OBJ)
   :output ((OUTPUT))
   :input ((INPUT))
   :exceptions NIL))

(DEFINE-METHOD "NEXT_N" ((OBJ COSNAMING:BINDINGITERATOR-PROXY) _HOW_MANY)
  (STATIC-CALL ("next_n" OBJ)
   :output ((OUTPUT) (MARSHAL-ULONG _HOW_MANY OUTPUT))
   :input ((INPUT) (UNMARSHAL-BOOL INPUT)
           (UNMARSHAL-SEQUENCE
             (lambda (buffer) (STRUCT-READ 'COSNAMING:BINDING BUFFER))
             INPUT))
   :exceptions NIL))

(DEFINE-METHOD "NEXT_ONE" ((OBJ COSNAMING:BINDINGITERATOR-PROXY))
  (STATIC-CALL ("next_one" OBJ)
   :output ((OUTPUT))
   :input ((INPUT) (UNMARSHAL-BOOL INPUT)
           (STRUCT-READ 'COSNAMING:BINDING INPUT))
   :exceptions NIL))

(DEFINE-INTERFACE COSNAMING:NAMINGCONTEXT (OBJECT)
 :proxy (COSNAMING:NAMINGCONTEXT-PROXY COSNAMING:NAMINGCONTEXT
         OMG.ORG/CORBA:PROXY)
 :id "IDL:omg.org/CosNaming/NamingContext:1.0"
 :name "NamingContext")

(DEFINE-METHOD "LIST" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) _HOW_MANY)
  (STATIC-CALL ("list" OBJ)
   :output ((OUTPUT) (MARSHAL-ULONG _HOW_MANY OUTPUT))
   :input ((INPUT)
           (UNMARSHAL-SEQUENCE
             (lambda (buffer) (STRUCT-READ 'COSNAMING:BINDING BUFFER))
             INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'COSNAMING:BINDINGITERATOR) INPUT))
   :exceptions NIL))

(DEFINE-METHOD "DESTROY" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY))
  (STATIC-CALL ("destroy" OBJ)
   :output ((OUTPUT))
   :input ((INPUT))
   :exceptions (COSNAMING:NAMINGCONTEXT/NOTEMPTY)))

(DEFINE-METHOD "BIND_NEW_CONTEXT" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) _N)
  (STATIC-CALL ("bind_new_context" OBJ)
   :output ((OUTPUT)
            (MARSHAL-SEQUENCE
              _N
              (lambda (obj buffer)
                (STRUCT-WRITE OBJ 'COSNAMING:NAMECOMPONENT BUFFER))
              OUTPUT))
   :input ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT) INPUT))
   :exceptions (COSNAMING:NAMINGCONTEXT/NOTFOUND
                 COSNAMING:NAMINGCONTEXT/ALREADYBOUND
                 COSNAMING:NAMINGCONTEXT/CANNOTPROCEED
                 COSNAMING:NAMINGCONTEXT/INVALIDNAME)))

(DEFINE-METHOD "NEW_CONTEXT" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY))
  (STATIC-CALL ("new_context" OBJ)
   :output ((OUTPUT))
   :input ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT) INPUT))
   :exceptions NIL))

(DEFINE-METHOD "UNBIND" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) _N)
  (STATIC-CALL ("unbind" OBJ)
   :output ((OUTPUT)
            (MARSHAL-SEQUENCE
              _N
              (lambda (obj buffer)
                (STRUCT-WRITE OBJ 'COSNAMING:NAMECOMPONENT BUFFER))
              OUTPUT))
   :input ((INPUT))
   :exceptions (COSNAMING:NAMINGCONTEXT/NOTFOUND
                 COSNAMING:NAMINGCONTEXT/CANNOTPROCEED
                 COSNAMING:NAMINGCONTEXT/INVALIDNAME)))

(DEFINE-METHOD "RESOLVE" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) _N)
  (STATIC-CALL ("resolve" OBJ)
   :output ((OUTPUT)
            (MARSHAL-SEQUENCE
              _N
              (lambda (obj buffer)
                (STRUCT-WRITE OBJ 'COSNAMING:NAMECOMPONENT BUFFER))
              OUTPUT))
   :input ((INPUT) (UNMARSHAL OMG.ORG/CORBA:tc_object INPUT))
   :exceptions (COSNAMING:NAMINGCONTEXT/NOTFOUND
                 COSNAMING:NAMINGCONTEXT/CANNOTPROCEED
                 COSNAMING:NAMINGCONTEXT/INVALIDNAME)))

(DEFINE-METHOD "REBIND_CONTEXT" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) _N _NC)
  (STATIC-CALL ("rebind_context" OBJ)
   :output ((OUTPUT)
            (MARSHAL-SEQUENCE
              _N
              (lambda (obj buffer)
                (STRUCT-WRITE OBJ 'COSNAMING:NAMECOMPONENT BUFFER))
              OUTPUT)
            (MARSHAL _NC (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT) OUTPUT))
   :input ((INPUT))
   :exceptions (COSNAMING:NAMINGCONTEXT/NOTFOUND
                 COSNAMING:NAMINGCONTEXT/CANNOTPROCEED
                 COSNAMING:NAMINGCONTEXT/INVALIDNAME)))

(DEFINE-METHOD "BIND_CONTEXT" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) _N _NC)
  (STATIC-CALL ("bind_context" OBJ)
   :output ((OUTPUT)
            (MARSHAL-SEQUENCE
              _N
              (lambda (obj buffer)
                (STRUCT-WRITE OBJ 'COSNAMING:NAMECOMPONENT BUFFER))
              OUTPUT)
            (MARSHAL _NC (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT) OUTPUT))
   :input ((INPUT))
   :exceptions (COSNAMING:NAMINGCONTEXT/NOTFOUND
                 COSNAMING:NAMINGCONTEXT/CANNOTPROCEED
                 COSNAMING:NAMINGCONTEXT/INVALIDNAME
                 COSNAMING:NAMINGCONTEXT/ALREADYBOUND)))

(DEFINE-METHOD "REBIND" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) _N _OBJ)
  (STATIC-CALL ("rebind" OBJ)
   :output ((OUTPUT)
            (MARSHAL-SEQUENCE
              _N
              (lambda (obj buffer)
                (STRUCT-WRITE OBJ 'COSNAMING:NAMECOMPONENT BUFFER))
              OUTPUT)
            (MARSHAL _OBJ OMG.ORG/CORBA:tc_object OUTPUT))
   :input ((INPUT))
   :exceptions (COSNAMING:NAMINGCONTEXT/NOTFOUND
                 COSNAMING:NAMINGCONTEXT/CANNOTPROCEED
                 COSNAMING:NAMINGCONTEXT/INVALIDNAME)))

(DEFINE-METHOD "BIND" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) _N _OBJ)
  (STATIC-CALL ("bind" OBJ)
   :output ((OUTPUT)
            (MARSHAL-SEQUENCE
              _N
              (lambda (obj buffer)
                (STRUCT-WRITE OBJ 'COSNAMING:NAMECOMPONENT BUFFER))
              OUTPUT)
            (MARSHAL _OBJ OMG.ORG/CORBA:tc_object OUTPUT))
   :input ((INPUT))
   :exceptions (COSNAMING:NAMINGCONTEXT/NOTFOUND
                 COSNAMING:NAMINGCONTEXT/CANNOTPROCEED
                 COSNAMING:NAMINGCONTEXT/INVALIDNAME
                 COSNAMING:NAMINGCONTEXT/ALREADYBOUND)))

(DEFINE-USER-EXCEPTION COSNAMING:NAMINGCONTEXT/NOTEMPTY
 :id "IDL:omg.org/CosNaming/NamingContext/NotEmpty:1.0"
 :name "NotEmpty"
 :members NIL)

(DEFINE-USER-EXCEPTION COSNAMING:NAMINGCONTEXT/ALREADYBOUND
 :id "IDL:omg.org/CosNaming/NamingContext/AlreadyBound:1.0"
 :name "AlreadyBound"
 :members NIL)

(DEFINE-USER-EXCEPTION COSNAMING:NAMINGCONTEXT/INVALIDNAME
 :id "IDL:omg.org/CosNaming/NamingContext/InvalidName:1.0"
 :name "InvalidName"
 :members NIL)

(DEFINE-USER-EXCEPTION COSNAMING:NAMINGCONTEXT/CANNOTPROCEED
 :id "IDL:omg.org/CosNaming/NamingContext/CannotProceed:1.0"
 :name "CannotProceed"
 :members (("cxt" (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT))
           ("rest_of_name" (SYMBOL-TYPECODE 'COSNAMING:NAME))))

(DEFINE-USER-EXCEPTION COSNAMING:NAMINGCONTEXT/NOTFOUND
 :id "IDL:omg.org/CosNaming/NamingContext/NotFound:1.0"
 :name "NotFound"
 :members (("why" (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/NOTFOUNDREASON))
           ("rest_of_name" (SYMBOL-TYPECODE 'COSNAMING:NAME))))

(DEFINE-ENUM COSNAMING:NAMINGCONTEXT/NOTFOUNDREASON
 :id "IDL:omg.org/CosNaming/NamingContext/NotFoundReason:1.0"
 :name "NotFoundReason"
 :members ("missing_node" "not_context" "not_object"))

(DEFINE-INTERFACE COSNAMING:NAMINGCONTEXTEXT (COSNAMING:NAMINGCONTEXT)
 :proxy (COSNAMING:NAMINGCONTEXTEXT-PROXY COSNAMING:NAMINGCONTEXTEXT
         COSNAMING:NAMINGCONTEXT-PROXY)
 :id "IDL:omg.org/CosNaming/NamingContextExt:1.0"
 :name "NamingContextExt")

(DEFINE-METHOD "RESOLVE_STR" ((OBJ COSNAMING:NAMINGCONTEXTEXT-PROXY) _N)
  (STATIC-CALL ("resolve_str" OBJ)
   :output ((OUTPUT) (MARSHAL-STRING _N OUTPUT))
   :input ((INPUT) (UNMARSHAL OMG.ORG/CORBA:tc_object INPUT))
   :exceptions (COSNAMING:NAMINGCONTEXT/NOTFOUND
                 COSNAMING:NAMINGCONTEXT/CANNOTPROCEED
                 COSNAMING:NAMINGCONTEXT/INVALIDNAME
                 COSNAMING:NAMINGCONTEXT/ALREADYBOUND)))

(DEFINE-METHOD "TO_URL" ((OBJ COSNAMING:NAMINGCONTEXTEXT-PROXY) _ADDR _SN)
  (STATIC-CALL ("to_url" OBJ)
   :output ((OUTPUT) (MARSHAL-STRING _ADDR OUTPUT) (MARSHAL-STRING _SN OUTPUT))
   :input ((INPUT) (UNMARSHAL-STRING INPUT))
   :exceptions (COSNAMING:NAMINGCONTEXTEXT/INVALIDADDRESS
                 COSNAMING:NAMINGCONTEXT/INVALIDNAME)))

(DEFINE-USER-EXCEPTION COSNAMING:NAMINGCONTEXTEXT/INVALIDADDRESS
 :id "IDL:omg.org/CosNaming/NamingContextExt/InvalidAddress:1.0"
 :name "InvalidAddress"
 :members NIL)

(DEFINE-METHOD "TO_NAME" ((OBJ COSNAMING:NAMINGCONTEXTEXT-PROXY) _SN)
  (STATIC-CALL ("to_name" OBJ)
   :output ((OUTPUT) (MARSHAL-STRING _SN OUTPUT))
   :input ((INPUT)
           (UNMARSHAL-SEQUENCE
             (lambda (buffer) (STRUCT-READ 'COSNAMING:NAMECOMPONENT BUFFER))
             INPUT))
   :exceptions (COSNAMING:NAMINGCONTEXT/INVALIDNAME)))

(DEFINE-METHOD "TO_STRING" ((OBJ COSNAMING:NAMINGCONTEXTEXT-PROXY) _N)
  (STATIC-CALL ("to_string" OBJ)
   :output ((OUTPUT)
            (MARSHAL-SEQUENCE
              _N
              (lambda (obj buffer)
                (STRUCT-WRITE OBJ 'COSNAMING:NAMECOMPONENT BUFFER))
              OUTPUT))
   :input ((INPUT) (UNMARSHAL-STRING INPUT))
   :exceptions (COSNAMING:NAMINGCONTEXT/INVALIDNAME)))

(DEFINE-ALIAS COSNAMING:NAMINGCONTEXTEXT/URLSTRING
 :id "IDL:omg.org/CosNaming/NamingContextExt/URLString:1.0"
 :name "URLString"
 :type OMG.ORG/CORBA:STRING
 :typecode OMG.ORG/CORBA:TC_STRING)

(DEFINE-ALIAS COSNAMING:NAMINGCONTEXTEXT/ADDRESS
 :id "IDL:omg.org/CosNaming/NamingContextExt/Address:1.0"
 :name "Address"
 :type OMG.ORG/CORBA:STRING
 :typecode OMG.ORG/CORBA:TC_STRING)

(DEFINE-ALIAS COSNAMING:NAMINGCONTEXTEXT/STRINGNAME
 :id "IDL:omg.org/CosNaming/NamingContextExt/StringName:1.0"
 :name "StringName"
 :type OMG.ORG/CORBA:STRING
 :typecode OMG.ORG/CORBA:TC_STRING)
