
(IN-PACKAGE :CLORB)

(EVAL-WHEN (:COMPILE-TOPLEVEL :LOAD-TOPLEVEL :EXECUTE)
  (ENSURE-CORBA-PACKAGE
    "COSNAMING"
    :EXPORT
    '("NAMINGCONTEXTEXT/STRINGNAME" "NAMINGCONTEXTEXT/ADDRESS"
      "NAMINGCONTEXTEXT/URLSTRING" "NAMINGCONTEXTEXT/INVALIDADDRESS"
      "NAMINGCONTEXTEXT-PROXY" "NAMINGCONTEXTEXT"
      "NAMINGCONTEXT/NOTFOUNDREASON" "NAMINGCONTEXT/INVALIDNAME"
      "NAMINGCONTEXT/CANNOTPROCEED" "NAMINGCONTEXT/ALREADYBOUND"
      "NAMINGCONTEXT/NOTFOUND" "NAMINGCONTEXT/NOTEMPTY" "NAMINGCONTEXT-PROXY"
      "NAMINGCONTEXT" "BINDINGITERATOR-PROXY" "BINDINGITERATOR" "ISTRING"
      "NAMECOMPONENT" "BINDINGTYPE" "NAME" "BINDING" "BINDINGLIST")))

(DEFINE-ALIAS COSNAMING:BINDINGLIST
 :ID "IDL:omg.org/CosNaming/BindingList:1.0"
 :NAME "BindingList"
 :TYPE SEQUENCE
 :TYPECODE (MAKE-SEQUENCE-TYPECODE (SYMBOL-TYPECODE 'COSNAMING:BINDING) 0))

(DEFINE-STRUCT COSNAMING:BINDING
 :ID "IDL:omg.org/CosNaming/Binding:1.0"
 :NAME "Binding"
 :MEMBERS (("binding_name" (SYMBOL-TYPECODE 'COSNAMING:NAME) BINDING_NAME)
           ("binding_type" (SYMBOL-TYPECODE 'COSNAMING:BINDINGTYPE)
            BINDING_TYPE))
 :READ ((BUFFER)
        (COSNAMING:BINDING :BINDING_NAME
                           (UNMARSHAL-SEQUENCE
                             (LAMBDA (BUFFER)
                               (STRUCT-READ 'COSNAMING:NAMECOMPONENT BUFFER))
                             BUFFER)
                           :BINDING_TYPE
                           (UNMARSHAL (SYMBOL-TYPECODE 'COSNAMING:BINDINGTYPE)
                                      BUFFER)))
 :WRITE ((OBJ BUFFER)
         (MARSHAL-SEQUENCE
           (OMG.ORG/FEATURES:BINDING_NAME OBJ)
           (LAMBDA (OBJ BUFFER)
             (STRUCT-WRITE OBJ 'COSNAMING:NAMECOMPONENT BUFFER))
           BUFFER)
         (MARSHAL (OMG.ORG/FEATURES:BINDING_TYPE OBJ)
                  (SYMBOL-TYPECODE 'COSNAMING:BINDINGTYPE)
                  BUFFER)))

(DEFINE-ENUM COSNAMING:BINDINGTYPE
 :ID "IDL:omg.org/CosNaming/BindingType:1.0"
 :NAME "BindingType"
 :MEMBERS ("nobject" "ncontext"))

(DEFINE-ALIAS COSNAMING:NAME
 :ID "IDL:omg.org/CosNaming/Name:1.0"
 :NAME "Name"
 :TYPE SEQUENCE
 :TYPECODE (MAKE-SEQUENCE-TYPECODE
             (SYMBOL-TYPECODE 'COSNAMING:NAMECOMPONENT)
             0))

(DEFINE-STRUCT COSNAMING:NAMECOMPONENT
 :ID "IDL:omg.org/CosNaming/NameComponent:1.0"
 :NAME "NameComponent"
 :MEMBERS (("id" (SYMBOL-TYPECODE 'COSNAMING:ISTRING) ID)
           ("kind" (SYMBOL-TYPECODE 'COSNAMING:ISTRING) KIND))
 :READ ((BUFFER)
        (COSNAMING:NAMECOMPONENT
          :ID
          (UNMARSHAL-STRING BUFFER)
          :KIND
          (UNMARSHAL-STRING BUFFER)))
 :WRITE ((OBJ BUFFER) (MARSHAL-STRING (OMG.ORG/FEATURES:ID OBJ) BUFFER)
         (MARSHAL-STRING (OMG.ORG/FEATURES:KIND OBJ) BUFFER)))

(DEFINE-ALIAS COSNAMING:ISTRING
 :ID "IDL:omg.org/CosNaming/Istring:1.0"
 :NAME "Istring"
 :TYPE OMG.ORG/CORBA:STRING
 :TYPECODE OMG.ORG/CORBA:TC_STRING)

(DEFINE-INTERFACE COSNAMING:BINDINGITERATOR (OBJECT)
 :PROXY (COSNAMING:BINDINGITERATOR-PROXY COSNAMING:BINDINGITERATOR
         OMG.ORG/CORBA:PROXY)
 :ID "IDL:omg.org/CosNaming/BindingIterator:1.0"
 :NAME "BindingIterator")

(DEFINE-METHOD "DESTROY" ((OBJ COSNAMING:BINDINGITERATOR-PROXY))
  (STATIC-CALL ("destroy" OBJ)
   :OUTPUT ((OUTPUT))
   :INPUT ((INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "NEXT_N" ((OBJ COSNAMING:BINDINGITERATOR-PROXY) _HOW_MANY)
  (STATIC-CALL ("next_n" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-ULONG _HOW_MANY OUTPUT))
   :INPUT ((INPUT) (UNMARSHAL-BOOL INPUT)
           (UNMARSHAL-SEQUENCE
             (LAMBDA (BUFFER) (STRUCT-READ 'COSNAMING:BINDING BUFFER))
             INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "NEXT_ONE" ((OBJ COSNAMING:BINDINGITERATOR-PROXY))
  (STATIC-CALL ("next_one" OBJ)
   :OUTPUT ((OUTPUT))
   :INPUT ((INPUT) (UNMARSHAL-BOOL INPUT)
           (STRUCT-READ 'COSNAMING:BINDING INPUT))
   :EXCEPTIONS NIL))

(DEFINE-INTERFACE COSNAMING:NAMINGCONTEXT (OBJECT)
 :PROXY (COSNAMING:NAMINGCONTEXT-PROXY COSNAMING:NAMINGCONTEXT
         OMG.ORG/CORBA:PROXY)
 :ID "IDL:omg.org/CosNaming/NamingContext:1.0"
 :NAME "NamingContext")

(DEFINE-METHOD "LIST" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) _HOW_MANY)
  (STATIC-CALL ("list" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-ULONG _HOW_MANY OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL-SEQUENCE
             (LAMBDA (BUFFER) (STRUCT-READ 'COSNAMING:BINDING BUFFER))
             INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'COSNAMING:BINDINGITERATOR) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "DESTROY" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY))
  (STATIC-CALL ("destroy" OBJ)
   :OUTPUT ((OUTPUT))
   :INPUT ((INPUT))
   :EXCEPTIONS (COSNAMING:NAMINGCONTEXT/NOTEMPTY)))

(DEFINE-METHOD "BIND_NEW_CONTEXT" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) _N)
  (STATIC-CALL ("bind_new_context" OBJ)
   :OUTPUT ((OUTPUT)
            (MARSHAL-SEQUENCE
              _N
              (LAMBDA (OBJ BUFFER)
                (STRUCT-WRITE OBJ 'COSNAMING:NAMECOMPONENT BUFFER))
              OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT) INPUT))
   :EXCEPTIONS (COSNAMING:NAMINGCONTEXT/NOTFOUND
                 COSNAMING:NAMINGCONTEXT/ALREADYBOUND
                 COSNAMING:NAMINGCONTEXT/CANNOTPROCEED
                 COSNAMING:NAMINGCONTEXT/INVALIDNAME)))

(DEFINE-METHOD "NEW_CONTEXT" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY))
  (STATIC-CALL ("new_context" OBJ)
   :OUTPUT ((OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT) INPUT))
   :EXCEPTIONS NIL))

(DEFINE-METHOD "UNBIND" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) _N)
  (STATIC-CALL ("unbind" OBJ)
   :OUTPUT ((OUTPUT)
            (MARSHAL-SEQUENCE
              _N
              (LAMBDA (OBJ BUFFER)
                (STRUCT-WRITE OBJ 'COSNAMING:NAMECOMPONENT BUFFER))
              OUTPUT))
   :INPUT ((INPUT))
   :EXCEPTIONS (COSNAMING:NAMINGCONTEXT/NOTFOUND
                 COSNAMING:NAMINGCONTEXT/CANNOTPROCEED
                 COSNAMING:NAMINGCONTEXT/INVALIDNAME)))

(DEFINE-METHOD "RESOLVE" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) _N)
  (STATIC-CALL ("resolve" OBJ)
   :OUTPUT ((OUTPUT)
            (MARSHAL-SEQUENCE
              _N
              (LAMBDA (OBJ BUFFER)
                (STRUCT-WRITE OBJ 'COSNAMING:NAMECOMPONENT BUFFER))
              OUTPUT))
   :INPUT ((INPUT) (UNMARSHAL OMG.ORG/CORBA:TC_OBJREF INPUT))
   :EXCEPTIONS (COSNAMING:NAMINGCONTEXT/NOTFOUND
                 COSNAMING:NAMINGCONTEXT/CANNOTPROCEED
                 COSNAMING:NAMINGCONTEXT/INVALIDNAME)))

(DEFINE-METHOD "REBIND_CONTEXT" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) _N _NC)
  (STATIC-CALL ("rebind_context" OBJ)
   :OUTPUT ((OUTPUT)
            (MARSHAL-SEQUENCE
              _N
              (LAMBDA (OBJ BUFFER)
                (STRUCT-WRITE OBJ 'COSNAMING:NAMECOMPONENT BUFFER))
              OUTPUT)
            (MARSHAL _NC (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT) OUTPUT))
   :INPUT ((INPUT))
   :EXCEPTIONS (COSNAMING:NAMINGCONTEXT/NOTFOUND
                 COSNAMING:NAMINGCONTEXT/CANNOTPROCEED
                 COSNAMING:NAMINGCONTEXT/INVALIDNAME)))

(DEFINE-METHOD "BIND_CONTEXT" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) _N _NC)
  (STATIC-CALL ("bind_context" OBJ)
   :OUTPUT ((OUTPUT)
            (MARSHAL-SEQUENCE
              _N
              (LAMBDA (OBJ BUFFER)
                (STRUCT-WRITE OBJ 'COSNAMING:NAMECOMPONENT BUFFER))
              OUTPUT)
            (MARSHAL _NC (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT) OUTPUT))
   :INPUT ((INPUT))
   :EXCEPTIONS (COSNAMING:NAMINGCONTEXT/NOTFOUND
                 COSNAMING:NAMINGCONTEXT/CANNOTPROCEED
                 COSNAMING:NAMINGCONTEXT/INVALIDNAME
                 COSNAMING:NAMINGCONTEXT/ALREADYBOUND)))

(DEFINE-METHOD "REBIND" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) _N _OBJ)
  (STATIC-CALL ("rebind" OBJ)
   :OUTPUT ((OUTPUT)
            (MARSHAL-SEQUENCE
              _N
              (LAMBDA (OBJ BUFFER)
                (STRUCT-WRITE OBJ 'COSNAMING:NAMECOMPONENT BUFFER))
              OUTPUT)
            (MARSHAL _OBJ OMG.ORG/CORBA:TC_OBJREF OUTPUT))
   :INPUT ((INPUT))
   :EXCEPTIONS (COSNAMING:NAMINGCONTEXT/NOTFOUND
                 COSNAMING:NAMINGCONTEXT/CANNOTPROCEED
                 COSNAMING:NAMINGCONTEXT/INVALIDNAME)))

(DEFINE-METHOD "BIND" ((OBJ COSNAMING:NAMINGCONTEXT-PROXY) _N _OBJ)
  (STATIC-CALL ("bind" OBJ)
   :OUTPUT ((OUTPUT)
            (MARSHAL-SEQUENCE
              _N
              (LAMBDA (OBJ BUFFER)
                (STRUCT-WRITE OBJ 'COSNAMING:NAMECOMPONENT BUFFER))
              OUTPUT)
            (MARSHAL _OBJ OMG.ORG/CORBA:TC_OBJREF OUTPUT))
   :INPUT ((INPUT))
   :EXCEPTIONS (COSNAMING:NAMINGCONTEXT/NOTFOUND
                 COSNAMING:NAMINGCONTEXT/CANNOTPROCEED
                 COSNAMING:NAMINGCONTEXT/INVALIDNAME
                 COSNAMING:NAMINGCONTEXT/ALREADYBOUND)))

(DEFINE-USER-EXCEPTION COSNAMING:NAMINGCONTEXT/NOTEMPTY
 :ID "IDL:omg.org/CosNaming/NamingContext/NotEmpty:1.0"
 :NAME "NotEmpty"
 :MEMBERS NIL)

(DEFINE-USER-EXCEPTION COSNAMING:NAMINGCONTEXT/ALREADYBOUND
 :ID "IDL:omg.org/CosNaming/NamingContext/AlreadyBound:1.0"
 :NAME "AlreadyBound"
 :MEMBERS NIL)

(DEFINE-USER-EXCEPTION COSNAMING:NAMINGCONTEXT/INVALIDNAME
 :ID "IDL:omg.org/CosNaming/NamingContext/InvalidName:1.0"
 :NAME "InvalidName"
 :MEMBERS NIL)

(DEFINE-USER-EXCEPTION COSNAMING:NAMINGCONTEXT/CANNOTPROCEED
 :ID "IDL:omg.org/CosNaming/NamingContext/CannotProceed:1.0"
 :NAME "CannotProceed"
 :MEMBERS (("cxt" (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT))
           ("rest_of_name" (SYMBOL-TYPECODE 'COSNAMING:NAME))))

(DEFINE-USER-EXCEPTION COSNAMING:NAMINGCONTEXT/NOTFOUND
 :ID "IDL:omg.org/CosNaming/NamingContext/NotFound:1.0"
 :NAME "NotFound"
 :MEMBERS (("why" (SYMBOL-TYPECODE 'COSNAMING:NAMINGCONTEXT/NOTFOUNDREASON))
           ("rest_of_name" (SYMBOL-TYPECODE 'COSNAMING:NAME))))

(DEFINE-ENUM COSNAMING:NAMINGCONTEXT/NOTFOUNDREASON
 :ID "IDL:omg.org/CosNaming/NamingContext/NotFoundReason:1.0"
 :NAME "NotFoundReason"
 :MEMBERS ("missing_node" "not_context" "not_object"))

(DEFINE-INTERFACE COSNAMING:NAMINGCONTEXTEXT (COSNAMING:NAMINGCONTEXT)
 :PROXY (COSNAMING:NAMINGCONTEXTEXT-PROXY COSNAMING:NAMINGCONTEXTEXT
         COSNAMING:NAMINGCONTEXT-PROXY)
 :ID "IDL:omg.org/CosNaming/NamingContextExt:1.0"
 :NAME "NamingContextExt")

(DEFINE-METHOD "RESOLVE_STR" ((OBJ COSNAMING:NAMINGCONTEXTEXT-PROXY) _N)
  (STATIC-CALL ("resolve_str" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _N OUTPUT))
   :INPUT ((INPUT) (UNMARSHAL OMG.ORG/CORBA:TC_OBJREF INPUT))
   :EXCEPTIONS (COSNAMING:NAMINGCONTEXT/NOTFOUND
                 COSNAMING:NAMINGCONTEXT/CANNOTPROCEED
                 COSNAMING:NAMINGCONTEXT/INVALIDNAME
                 COSNAMING:NAMINGCONTEXT/ALREADYBOUND)))

(DEFINE-METHOD "TO_URL" ((OBJ COSNAMING:NAMINGCONTEXTEXT-PROXY) _ADDR _SN)
  (STATIC-CALL ("to_url" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _ADDR OUTPUT) (MARSHAL-STRING _SN OUTPUT))
   :INPUT ((INPUT) (UNMARSHAL-STRING INPUT))
   :EXCEPTIONS (COSNAMING:NAMINGCONTEXTEXT/INVALIDADDRESS
                 COSNAMING:NAMINGCONTEXT/INVALIDNAME)))

(DEFINE-USER-EXCEPTION COSNAMING:NAMINGCONTEXTEXT/INVALIDADDRESS
 :ID "IDL:omg.org/CosNaming/NamingContextExt/InvalidAddress:1.0"
 :NAME "InvalidAddress"
 :MEMBERS NIL)

(DEFINE-METHOD "TO_NAME" ((OBJ COSNAMING:NAMINGCONTEXTEXT-PROXY) _SN)
  (STATIC-CALL ("to_name" OBJ)
   :OUTPUT ((OUTPUT) (MARSHAL-STRING _SN OUTPUT))
   :INPUT ((INPUT)
           (UNMARSHAL-SEQUENCE
             (LAMBDA (BUFFER) (STRUCT-READ 'COSNAMING:NAMECOMPONENT BUFFER))
             INPUT))
   :EXCEPTIONS (COSNAMING:NAMINGCONTEXT/INVALIDNAME)))

(DEFINE-METHOD "TO_STRING" ((OBJ COSNAMING:NAMINGCONTEXTEXT-PROXY) _N)
  (STATIC-CALL ("to_string" OBJ)
   :OUTPUT ((OUTPUT)
            (MARSHAL-SEQUENCE
              _N
              (LAMBDA (OBJ BUFFER)
                (STRUCT-WRITE OBJ 'COSNAMING:NAMECOMPONENT BUFFER))
              OUTPUT))
   :INPUT ((INPUT) (UNMARSHAL-STRING INPUT))
   :EXCEPTIONS (COSNAMING:NAMINGCONTEXT/INVALIDNAME)))

(DEFINE-ALIAS COSNAMING:NAMINGCONTEXTEXT/URLSTRING
 :ID "IDL:omg.org/CosNaming/NamingContextExt/URLString:1.0"
 :NAME "URLString"
 :TYPE OMG.ORG/CORBA:STRING
 :TYPECODE OMG.ORG/CORBA:TC_STRING)

(DEFINE-ALIAS COSNAMING:NAMINGCONTEXTEXT/ADDRESS
 :ID "IDL:omg.org/CosNaming/NamingContextExt/Address:1.0"
 :NAME "Address"
 :TYPE OMG.ORG/CORBA:STRING
 :TYPECODE OMG.ORG/CORBA:TC_STRING)

(DEFINE-ALIAS COSNAMING:NAMINGCONTEXTEXT/STRINGNAME
 :ID "IDL:omg.org/CosNaming/NamingContextExt/StringName:1.0"
 :NAME "StringName"
 :TYPE OMG.ORG/CORBA:STRING
 :TYPECODE OMG.ORG/CORBA:TC_STRING)
