(cl:in-package "OMG.ORG/CORBA")
(cl:export
 '(CONTAINED/DESCRIPTION
   repositoryid definitionkind
   STRUCTMEMBER
   scopedname
   UNIONMEMBER
   CONTAINER/DESCRIPTION
   MODULEDESCRIPTION
   CONSTANTDESCRIPTION
   TYPEDESCRIPTION
   EXCEPTIONDESCRIPTION
   ATTRIBUTEDESCRIPTION
   PARAMETERDESCRIPTION
   OPERATIONDESCRIPTION
   INTERFACEDEF/FULLINTERFACEDESCRIPTION
   INTERFACEDESCRIPTION))

