(in-package "OMG.ORG/CORBA")
(cl:export
 '(CONTAINED/DESCRIPTION
   STRUCTMEMBER
   UNIONMEMBER
   CONTAINER/DESCRIPTION
   MODULEDESCRIPTION
   CONSTANTDESCRIPTION
   TYPEDESCRIPTION
   EXCEPTIONDESCRIPTION
   ATTRIBUTEDESCRIPTION
   PARAMETERDESCRIPTION
   OPERATIONDESCRIPTION
   INTERFACEDEF/FULLINTERFACEDESCRIPTION
   INTERFACEDESCRIPTION))

